### ISSUE TITLE
If saml is not configured, don't show link to idp

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_saml2#10]
ie if the idp.xml file isn't made

**Comment by brendanheywood** [comment]
Implement is_configured() if the plugin is on, and the idp file and the sp file metadata exist.

**Comment by brendanheywood** [comment]
If is_configured() returns flase then return then return nothing in loginpage_idp_list()

**Comment by nhoobin** [comment]
Closed with merge #50.
