### ISSUE TITLE
Moodle users that have been suspended or deleted can still login?

### ISSUE THREAD

**Issue by praj** [catalyst/moodle-auth_saml2#101]
Currently the plugin allows users that have been suspended to login to Moodle (particularly problematic as it doesn't stop them accessing the site after being suspended).

Similarly it allows deleted users to login to Moodle but then throws a PHP catchable fatal error (tested by setting deleted flag to 1) as it can't instantiate the user object properly.

Suggest adding a check for the value of 1 for either the suspended or deleted flags in auth/saml2/auth.php as part of the saml_login() function.

**Comment by brendanheywood** [comment]
hi @praj, thanks - are you able to put together a pull request?
