### ISSUE TITLE
IDP initiated SSO only scenario / unsolicited / idp first flow

### ISSUE THREAD

**Issue by samchaffee** [catalyst/moodle-auth_saml2#105]
We're experiencing an issue where a site is using IDP initiated SSO only, i.e. they do not have a "SingleSignOnService" element in the idp-remote metadata.

The SimpleSAMLSession looks like it is created and the browser is redirected to the provided RelayState (in this case a url for a Moodle course), but when the require login redirects to the login page and the auth/saml2 hooks are called it can't find a valid session and tries to initiate a SP solicited SSO. Of course, that fails because there is no SignSignOnService metadata.

From the stack trace: "Exception - saml20-idp-remote/'<entity-id>'['SingleSignOnService']:Could not find a supported SingleSignOnService endpoint."

We are using the 2016090801 version of the plugin.

I'm actively working on finding the root cause, but I was wondering if you had seen anything similar. Thanks.

**Comment by brendanheywood** [comment]
Thanks @sam-moodle, no I haven't had any clients who have wanted idp initiated sso yet, so this is a new feature. As always pr's are welcome

**Comment by bmiller-tam** [comment]
Another vote for IdP-initiated SSO support here.

**Comment by mccork91** [comment]
@brendanheywood - could you let me know if this feature is still not supported? 

If not could you PM to let me know if your team would be interested in development of this and approx cost of implementation thanks

**Comment by brendanheywood** [comment]
@mccork91 sorry I missed this in the noise. Can you please email presales@catalyst-au.net and we'll get that rolling.

**Comment by brendanheywood** [comment]
I've added support for IdP first flow
