### ISSUE TITLE
Plugin doesn't work on Moodle 2.8.x

### ISSUE THREAD

**Issue by ghost** [catalyst/moodle-auth_saml2#106]
I configured plugin both Moodle 3.x and 2.8.x.  When plugin works fine on Moodle 3.x we got a HTTP 500 error on IdP when request is send from Moodle 2.8.x (we are using Google Apps).  Same configuration used.

**Comment by brendanheywood** [comment]
thanks @jmanuelemus2, so to clarify your *idp* is serving a 500? can you please dump a trace from the error log while saml debugging is turned on. and what idp are you using?

**Comment by brendanheywood** [comment]
Also please keep in mind that 2.8 has been completely out of support for full a year, so I'm unlikely to worry about this issue too much unless it also applies to other supported versions or unless you want some paid commercial support.

**Comment by roperto** [comment]
I am closing this one due to recent updates and it currently works on Moodle 27+

If you are still experiencing issues please provide more information.
