### ISSUE TITLE
ADFS Asking for Endpoints

### ISSUE THREAD

**Issue by daemonhunt** [catalyst/moodle-auth_saml2#114]
We are attempting to migrate to this plugin (from OneLogin and SimpleSAMLphp), but we can't get it working properly. We succesfully manage to get redirected from Moodle to ADFS (v3.0) to enter our credentials, however upon adding our credentials and continuing with the submission an error is shown on the ADFS server and we are not sent back to Moodle.

It's as if ADFS has nowhere to return to upon succesful auth. Our IT department has sent me an email indicating that no endpoints appear to be defined in the SP Metadata, and have shown me a screenshot indicating that the endpoint fields in ADFS are indeed blank. I am wondering if we have to enter these endpoints into ADFS manually or whether I have missed something?

The instructions for using your plugin almost make the whole setup sound exceedingly simple, although when we set up both ends for SimpleSAMLphp (which still exists in your plugin), there was a lot more work involved, including defining claim and transformation rules on the ADFS server.

The displayed ADFS error on the login page doesn't seem particularly scary, so I am confident it's an easy fix:

    Activity ID: 00000000-0000-0000-d869-0080000000eb
    Relying party: [site].ac.nz
    Error time: Tue, 13 Jun 2017 21:45:39 GMT
    Cookie: enabled
    User agent string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by brendanheywood** [comment]
@daemonhunt can you please provide more details? This sounds like it's just missing setup on the adfs side and we are not ADSF experts. In particular please follow the steps here and dump the output of the error log with the saml debugging on:

https://github.com/catalyst/moodle-auth_saml2#debugging

> although when we set up both ends for SimpleSAMLphp (which still exists in your plugin)

SimpleSamlPHP is an internal dependancy of this plugin, you shouldn't attempt to interact with it directly but only ever via the moodle admin page which provides links to the SP metadata urls etc. I don't know if this is what you've one but if you can provide examples of all the sp and idp xml urls that would be a great start to debugging this.

**Comment by daemonhunt** [comment]
Hello Brendan

We successfully managed to get the SAML2 plugin working with ADFS. The error was caused by a minor oversight.

Many Thanks!

**Comment by brendanheywood** [comment]
thanks @daemonhunt - even though it wasn't a code issue with this plugin, if you can provide any hints and tips for ADFS gotchas I'll put them into the README file - or if want you can open a pull request and write the help directly yourself and I'll merge it in
