### ISSUE TITLE
ADFS 3 - Decryption with key #0 failed with exception: Missing <saml:NameID> or <saml:EncryptedID> in <saml:Subject>.

### ISSUE THREAD

**Issue by rjacques** [catalyst/moodle-auth_saml2#118]
Hi,

I've been trying to get an ADFS integration working.

The error message after I run the SAML test page gave me:

```
`Default exception handler: Exception - Missing  or  in . Debug:
Error code: generalexceptionmessage
* line 277 of /auth/saml2/extlib/saml2/src/SAML2/Assertion.php: Exception thrown
* line 246 of /auth/saml2/extlib/saml2/src/SAML2/Assertion.php: call to SAML2_Assertion->parseSubject()
* line 92 of /auth/saml2/extlib/saml2/src/SAML2/EncryptedAssertion.php: call to SAML2_Assertion->__construct()
* line 371 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php: call to SAML2_EncryptedAssertion->getAssertion()
* line 550 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php: call to sspmod_saml_Message::decryptAssertion()
* line 524 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php: call to sspmod_saml_Message::processAssertion()
* line 120 of /auth/saml2/extlib/simplesamlphp/modules/saml/www/sp/saml2-acs.php: call to sspmod_saml_Message::processResponse()
````

I have set IdP to Moodle mapping to http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn mapping to email address.

When I inspect my error logs I can see the following: 'Decryption with key #0 failed with exception: `Missing <saml:NameID> or <saml:EncryptedID> in <saml:Subject>`.'

I have since tested the plugin with SSOcircle and it works great. 

I have attached a sanitised moodle log file. [saml2_log_2.txt](https://github.com/catalyst/moodle-auth_saml2/files/1106623/saml2_log_2.txt)

Thanks a lot!

**Comment by brendanheywood** [comment]
@rjacques we are not ADFS experts but this looks like a missing attribute on the adfs setup side, can you see is this comment helps you?

https://github.com/catalyst/moodle-auth_saml2/issues/27#issuecomment-236141847

If it does please summarize the solution as best you and I'll copy it into the readme as this seems to be coming up a bit with ADFS, thanks

**Comment by rjacques** [comment]
@brendanheywood thanks, I am going to see if they can have a further look into on the ADFS side. I will report back if there is any progress.

**Comment by LoveBug** [comment]
Hi everyone,
Just chiming in that I have troubleshooted this issue with an ADFS IDP and changing the ADFS claims to include a NameID as specified in: 
http://www.lewisroberts.com/2015/09/06/integrating-simplesamlphp-with-adfs-2012r2/
Under the heading: Create the Relying Party Trust in ADFS 2012R2

These instructions obviously are for ADFS 2012R2 but the taking the equivalent action in ADFS 3.0 would probably help!

**Comment by brendanheywood** [comment]
Closing, there is a new feature will when turned on makes the name id appear as though it was a normal attribute called 'nameid'
