### ISSUE TITLE
Config in Moodle 3.2

### ISSUE THREAD

**Issue by icsbcn** [catalyst/moodle-auth_saml2#120]
2 questions...

Can we change saml2 config in order to do calls by GET or POST?

Can we config saml2 plugin in order to set when token is regenerated?

Thank you so much!

**Comment by brendanheywood** [comment]
> Can we change saml2 config in order to do calls by GET or POST?

What exactly do you want and why? Roughly speaking if SimpleSAMLphp supports it then it's relatively easy to support it in this plugin. As a general rule doing stuff by POST is a pain as it requires a form to be submitted via javascript and it's ugly, the default bindings which use GET / redirects work better.

> Can we config saml2 plugin in order to set when token is regenerated?

Can you be more specific? Most tokens in saml are single use and it doesn't make sense to regenerate them. Do you mean the rolling the certificates?
