### ISSUE TITLE
Login overwrites description field with 1

### ISSUE THREAD

**Issue by jtsafran** [catalyst/moodle-auth_saml2#129]
When doing a login, if a user has any fields configured to update on every login, the description gets overwritten with a 1.

This occurs at line 318: https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_33PLUS/auth.php#L318 on the call to get_complete_user_data.  Moodle defines that method as being used for getting session info and not for truly pulling user data.  Please see the following for exact line this occurs:
https://github.com/moodle/moodle/blob/8146b1f06de51d1ca6b4043bc524ed2fe26aaa72/lib/moodlelib.php#L4717

For a temporary fix, I have commented out lines 318 and 393 as profile_save_data requires the full user data that is not fetched by removing 318.  This works for this site as we have no custom fields being populated, but is not ideal.

I wanted to log this here so anyone else having the issue can see it.  I will work some more to find a full fix, unless someone already has an idea!

Thanks!

**Comment by brendanheywood** [comment]
Ah curious, we've never used that field so never noticed. If you can provide a PR thats great. I'm not sure the best way to approach this, perhaps just ignoring that one field so we never overwrite it.
