### ISSUE TITLE
Single Logout with ADFS 3.0 as IdP not working as expected

### ISSUE THREAD

**Issue by 0p3r4t4** [catalyst/moodle-auth_saml2#138]
We have configured a test environment with ADFS 3.0 as IdP and two SP: Office 365 and Moodle with SAML2 plugin.

SSO works flawlessly but with SLO things start to get weird.

If SLO is started from Moodle, everything seems to work fine; Moodle SP issues a LogoutRequest and receives a LogoutResponse. After Moodle is logged out Office 365 is also logged out as well.

But if SLO is started from Office 365, Moodle, as stated in debugging info, only receives a LogoutRequest from Office 365 SP and do not issue a response, without any messages; no error, no warning, no cause. Office 365 then silently redirects to Moodle dashboard already logged in (I suspect this is an ADFS behaviour; redirect to the SP that has been unable to logout).

I expected Moodle to issue a LogoutResponse or, at least, print a debug message saying what is wrong.

I'm actually a newbie in this field so I don't know where to start digging into this problem or what information will be valuable to diagnose it. Also, SLO, as it is working, seems to take the front-channel way. SAML2 plugin states that it supports back-channel SLO, and it will be interesting to test it, but I don't know how to configure it, neither in the IdP or the SP.

Thanks in advance.

**Comment by brendanheywood** [comment]
Try turning on the full saml debugging in the moodle auth saml admin gui and see what comes out in the moodle error log? Idp initiated SLO should work but I haven't tested it myself with Office365 so there might be something slightly funky with its flavor of saml.

Other than that I'd need to see some details and get some test credentials etc - if you want commercial support please contact us here: https://www.catalyst-au.net/contact-us

**Comment by 0p3r4t4** [comment]
Currently debug in SAML2 plugin is turned on. In the SSP configuration link those values appear:
- debug = 1
- logging.level = 7
- logging.handler = errorLog

Is this what you refer as full saml debugging?
I've also turned PHP logging to E_ALL.

In this situation, the complete error log when SLO is initiated in O365 SP, seems like this (URLs and user anonymazed, and Apache timestamp, client, pid and so on deleted for clarity) :

    SimpleSAMLphp DEBUG [142493cf3d] Received message:, referer: https://login.microsoftonline.com/common/oauth2/logout
    SimpleSAMLphp DEBUG [142493cf3d] <samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_927eec67-560f-4769-9e30-7682c6c2e2a1" Version="2.0" IssueInstant="2017-09-13T08:48:56.102Z" Destination="https://mymoodle/site/auth/saml2/sp/saml2-logout.php/mymoodle" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" NotOnOrAfter="20 17-09-13T08:53:56.102Z">, referer: https://login.microsoftonline.com/common/oauth2/logout
    SimpleSAMLphp DEBUG [142493cf3d]   <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://mydomain/adfs/services/trust</Issuer>, referer : https://login.microsoftonline.com/common/oauth2/logout
    SimpleSAMLphp DEBUG [142493cf3d]   <NameID xmlns="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">myuser@mydomain</NameID>, referer: https://login.microsoftonline.com/common/oauth2/logout
    SimpleSAMLphp DEBUG [142493cf3d]   <samlp:SessionIndex>_8156a06b-e8ad-4022-91ed-676854edb3ff</samlp:SessionIndex>, referer: https://login.microsoftonline.com/common/oauth2/logout
    SimpleSAMLphp DEBUG [142493cf3d] </samlp:LogoutRequest>, referer: https://login.microsoftonline.com/common/oauth2/logout

Just these lines and nothing more.

**Comment by 0p3r4t4** [comment]
I added a line to print what does SSP expect as destination (\SimpleSAML\Utils\HTTP::getSelfURLNoQuery()) and it is:

    https://mymoodle:443/site/auth/saml2/sp/saml2-logout.php/mymoodle

The only difference is the explicit 443 port.

**Comment by brendanheywood** [comment]
Is this literally exactly what you see?

https://mymoodle:443/site/auth/saml2/sp/saml2-logout.php/mymoodle

If so try:

1) setting a more realsitic domain like mymoodle.local.com - there are some edge cases issues which hosts which don't look like real domains

2) Make sure $CFG->sslproxy = true; is set in your moodle config.php file to fix the :443 port which may be an issue. Depends on your test stack

**Comment by 0p3r4t4** [comment]
Of course it's not. As I said it's anonymised. Perhaps I've done it a bit much; my fault.
In origin 'mymoodle' is a valid and working host.domain name. Perhaps I should fake it as myhost.mydomain. Note that the environment is being tested by users and working perfectly, as far as Moodle itself and SAML2 SSO go, with the exception of SLO.

$CFG->sslproxy is set to true from the beginning since, with the current infrastructure configuration, Moodle will refuse to work otherwise.

**Comment by 0p3r4t4** [comment]
I'm in a hurry so perhaps I will explain this poorly. Sorry.

It seems that SimpleSAML\Utils\HTTP functions have had a bit of movement since one year ago: https://github.com/simplesamlphp/simplesamlphp/issues/419

This forces me to investigate further and see what SimpleSAML\Utils\HTTP::getSelfURLNoQuery() does, and consequently, SimpleSAML\Utils\HTTP::getSelfURL(). This function stands as:

    This method will try to see if the current script is part of SimpleSAMLphp. In that case, it will use the
    'baseurlpath' configuration option to rebuild the current URL based on that. If the current script is NOT
    part of SimpleSAMLphp, it will just return the current URL.

It basically does it by searching the "/www/" string into $_SERVER['SCRIPT_NAME'].

So, there are two 'saml2-logout.php' scripts, one from SAML2 and one from SSP. The SAML Logout endpoint is defined in terms of the first one. And this one executes the SSP one by a require statement. So $_SERVER['SCRIPT_NAME'], in case, '/data/htdocs/site/auth/saml2/sp/saml2-logout.php' (no "/www/" at all) will not be considered part of SSP. This is right, since it's just part of SAML2.

But this causes SimpleSAML\Utils\HTTP::getSelfURL() to rebuild the URL from scratch, adding the port. As I understand SimpleSAML\Utils\HTTP::getServerPort(), it shouldn't, but definitely it does.

No more time left, sorry. Tomorrow I will go deeper in these.

**Comment by 0p3r4t4** [comment]
So, all my investigation leads to this: https://github.com/simplesamlphp/simplesamlphp/issues/594

I don't know why but also in my case $_SERVER['SERVER_PORT'] is an integer and SimpleSAML\Utils\HTTP::getServerPort() compares it to a string with `!==` operator, effectively failing as types differ.
In the [SimpleSAMLphp issue](https://github.com/simplesamlphp/simplesamlphp/issues/594) it's said that properly setting `baseurlpath` could be a solution, but it's not the case with moodle-auth_saml2 since it wraps SSP scripts and SimpleSAML\Utils\HTTP::getSelfURL() dismisses `baseurlpath` to build the URL.

I will dare to say, if you excuse me, that moodle-auth_saml2 IdP (or another SP) initiated Logout capability is broken and it could have gone unnoticed by a bunch of factors, like:
- moodle-auth_saml2 `saml2-logout.php` swallows exceptions thrown by SSP `saml2-logout.php`
- once SSO works almost nobody gives a cent about SLO (this is a sensation I've developed these days while looking into Google to solve my issue).

As moodle-auth_saml2 depends on SSP I don't know if you want to raise the voice abut the [issue](https://github.com/simplesamlphp/simplesamlphp/issues/594), but I'm sure you have more weight than me to draw attention about the problem.

**Comment by roperto** [comment]
Can you still reproduce this problem? We have instances running ADFS 3 and 4 without problems.

**Comment by 0p3r4t4** [comment]
Hi.

ADFS turns out not to be the problem. Perhaps the issue title should be rewritten.

The problem originates on PHP $_SERVER['SERVER_PORT'] to be an integer instead of a string. In fact, I haven't been able to find out why an integer since string seems to be the standard behaviour. But I'm not alone as  
[SimpleSAMLphp issue](https://github.com/simplesamlphp/simplesamlphp/issues/594) denotes. The current workaround is to manually apply changes proposed on that issue to SSP code distributed with auth-saml2.

**Comment by brendanheywood** [comment]
Front channel SLO is now fully implemented
