### ISSUE TITLE
Site Administration > Mobile settings page timeout when auth_saml2 enabled

### ISSUE THREAD

**Issue by chrisshearing** [catalyst/moodle-auth_saml2#146]
We've found a really odd issue with accessing the Site Administration > Mobile app > Mobile settings page in moodle after enabling enablemobilewebservice.  The page would just hang and eventually we would get a timeout message.

its taken me most of the day to try and find what was causing the issue as the only error messages moodle was giving were:

[Wed Oct 11 15:42:35.574744 2017] [proxy_fcgi:error] [pid 3373:tid 139901051766528] (70007)The timeout specified has expired: [client 10.0.110.172:48182] AH01075: Error dispatching request to : (polling), referer: https://moodle2test.colchsfc.ac.uk/

catch_workers_output is enabled in php-fpm7.0 as are all the debug options, but nothing else except for a timeout had occured,

I chanced upon https://shubhamjain.co/2015/09/10/debugging-stuck-php-fpm-process-with-strace/ who had some great details on how he managed to debug a php-fpm timeout issue and following the same path led me to this error in strace

[pid  3446] poll([{fd=10, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)

and lsof lead me to 

php-fpm7. 3446 www-data   10u  IPv4              38486      0t0    TCP moodle2testwww2.colchester.local:41596->svr-adfs.colchester.local:https (ESTABLISHED)

I was confused at this point as I didnt see what our saml2 setup had to do with visiting a page in  site admin when we were already authenticated, but I tried disabling auth_saml2, afterwards I was able to visit the page without issue! re-enabling and again timeout errors.

I enabled debug in auth_saml2 checked the apache error.log before and after clicking on the link and this message appeared in the logs

I was using the moodle built-in  administrator user

[Wed Oct 11 16:07:26.713329 2017] [proxy_fcgi:error] [pid 3372:tid 139901219620608] [client 10.0.110.172:48340] AH01071: Got error 'PHP message: auth_saml2: loginpage_hook enter\nPHP message: auth_saml2: should_login_redirect enter\nPHP message: SimpleSAMLphp DEBUG [055e135cc5] Session: 'moodle2test.colchsfc.ac.uk' not valid because we are not authenticated.\nPHP message: SimpleSAMLphp DEBUG [055e135cc5] Saved state: '_12b4558a26f678cffb6fd79c5197a9a6756cf1f35e'\nPHP message: SimpleSAMLphp DEBUG [055e135cc5] Sending SAML 2 AuthnRequest to 'http://adfs.colchsfc.ac.uk/adfs/services/trust'\nPHP message: SimpleSAMLphp DEBUG [055e135cc5] Sending message:\nPHP message: SimpleSAMLphp DEBUG [055e135cc5] <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_12b4558a26f678cffb6fd79c5197a9a6756cf1f35e" Version="2.0" IssueInstant="2017-10-11T15:07:26Z" Destination="https://adfs.colchsfc.ac.uk/adfs/ls/" AssertionConsumerServiceURL="https://moodle2test.colchsfc.ac.uk/auth/saml2/sp/saml2-acs.php/moodle2test.colchsfc.ac.uk" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST">\nPHP message: SimpleSAMLphp DEBUG [055e135cc5]   <saml:Issuer>https://moodle2test.colchsfc.ac.uk/auth/saml2/sp/metadata.php</saml:Issuer>\nPHP message: SimpleSAMLphp DEBUG [055e135cc5] </samlp:AuthnRequest>\nPHP message: SimpleSAMLphp DEBUG [055e135cc5] Redirect to 1007 byte URL: https://adfs.colchsfc.ac.uk/adfs/ls/?SAMLRequest=lZJRS8MwFIX&RelayState=https.colchsfc.ac.uk.php&SigAlg=http.w3.org-more-sha256&Signature=bSbBlcj (\n)\n'

so I tried changing over to a ldap server user, synchronised via moodle scheduled task and logged in via auth_saml2

[Wed Oct 11 16:13:42.605319 2017] [proxy_fcgi:error] [pid 3372:tid 139901202835200] [client 10.0.110.172:48360] AH01071: Got error 'PHP message: auth_saml2: loginpage_hook enter\nPHP message: auth_saml2: should_login_redirect enter\nPHP message: SimpleSAMLphp DEBUG [9e8bb448b3] Session: 'moodle2test.colchsfc.ac.uk' not valid because we are not authenticated.\nPHP message: SimpleSAMLphp DEBUG [9e8bb448b3] Saved state: '_81d64e6ea09d38b6a47930a8470dc4edee194210e1'\nPHP message: SimpleSAMLphp DEBUG [9e8bb448b3] Sending SAML 2 AuthnRequest to 'http://adfs.colchsfc.ac.uk/adfs/services/trust'\nPHP message: SimpleSAMLphp DEBUG [9e8bb448b3] Sending message:\nPHP message: SimpleSAMLphp DEBUG [9e8bb448b3] <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_81d64e6ea09d38b6a47930a8470dc4edee194210e1" Version="2.0" IssueInstant="2017-10-11T15:13:42Z" Destination="https://adfs.colchsfc.ac.uk/adfs/ls/" AssertionConsumerServiceURL="https://moodle2test.colchsfc.ac.uk/auth/saml2/sp/saml2-acs.php/moodle2test.colchsfc.ac.uk" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST">\nPHP message: SimpleSAMLphp DEBUG [9e8bb448b3]   <saml:Issuer>https://moodle2test.colchsfc.ac.uk/auth/saml2/sp/metadata.php</saml:Issuer>\nPHP message: SimpleSAMLphp DEBUG [9e8bb448b3] </samlp:AuthnRequest>\nPHP message: SimpleSAMLphp DEBUG [9e8bb448b3] Redirect to 985 byte URL: https://adfs.colchsfc.ac.uk/adfs/ls/?SAMLRequest=lZLNTsMwEIRfJfI9cZyG&RelayState=https.colchsfc.ac.uk.php&SigAlg=http.w3.org-more-sha256&Signature=ePOxFYlGAV71 (\n)\n'

it seems that page is causing auth_saml2 to think it isnt logged in, trying to log in and then not completing the task (probably as its already authenticated and doesnt need to be doing that?)

It seems strange to me, but hopefully its something that can be fixed.

If you need any more information, or for me to run some tests that's not a problem as this is currently in our test / dev environment.

Thanks,

**Comment by chrisshearing** [comment]
A little bit more info:

If I set dual login to Yes, I can access the Mobile Settings page without error, the same as if I disable the auth_saml2 plugin,

I don't have xdebug available in our install so I've not been able to find out what is calling loginpage_hook on the Mobile Settings page - I've had a quick look through the auth.php code for auth_saml2 and moodles admin/settings.php for anything obvious that might be calling loginpage_hook either on purpose or perhaps with a regex bug, but I'm afraid I couldnt see anything, I can only guess its a call from that page to some other function, or somehow there is confusion the user's session state which would require a real debugger or more knowledge of the moodle core files.

**Comment by danmarsden** [comment]
I think I've just run into this same issue too - but setting dual-login doesn't seem to make any difference. Hopefully we'll get a chance to track down what is going on....

**Comment by danmarsden** [comment]
I'm guessing this is because admin_setting_enablemobileservice looks like it makes a curl call to /login/index.php to check if https is supported by the server. We probably need to create a core bug as this is a pretty crappy way to check for https support.

**Comment by brendanheywood** [comment]
Given that loginhttps has been deprecated we can probably just axe that and rely purely on the wwwroot?

https://tracker.moodle.org/browse/MDL-42834

**Comment by danmarsden** [comment]
in master(3.4) they have added a check to see if the cert is valid as well - not sure if that code still has a timeout problem though.

**Comment by brendanheywood** [comment]
Actually it's just deprecated not actually removed, see also https://tracker.moodle.org/browse/MDL-46267

**Comment by danmarsden** [comment]
have created https://tracker.moodle.org/browse/MDL-60634 with the basic details of this.

workaround for this is to add "return $html" in admin_setting_enablemobileservice::output_html() under the line:
$html = parent::output_html($data, $query);

**Comment by chrisshearing** [comment]
Thanks for looking into this - seems I was quite close but not quite right on my limited investigation, and it does seem an odd way to check if https is enabled!

I've applied the workaround, will nicely stop our moodle administrators on the teaching side bringing down the server by accidentally clicking on the Mobile Settings link while we wait for Moodle core to fix the bug (and for us to then upgrade our live Moodle to a version which includes the bug fix!)

**Comment by brendanheywood** [comment]
@danmarsden nothing else to do here then so close?

**Comment by danmarsden** [comment]
yeah - I've just PR'd the fix for core so should hopefully land in next weeks integration.
