### ISSUE TITLE
single logout not working with shibboleth

### ISSUE THREAD

**Issue by blenke** [catalyst/moodle-auth_saml2#15]
Is the single logout working properly. I tried the http://www.testshib.org example saml which includes the single logout. Login works fine however  a logout does not really log me out. If I click login again then it logs me in without asking for credentials. Am I doing something wrong ? A'm using moodle 3.0 on IIS.

It would be nice to have an option for a logout property url in the configuration. I'm not sure if our saml supports the standard single logout. Usually web sites that support saml have a logout url option.

**Comment by brendanheywood** [comment]
Shibboleth itself doesn't support single signout as an idp which I find utterly bizarre, especially seeing as the saml sso spec is really old and has good support elsewhere. You can read their excuses here:

https://wiki.shibboleth.net/confluence/display/CONCEPT/SLOIssues

The main client who sponsored this work is using shib, so single sign out wasn't a focus of theirs, but that said I remember testing is against a Simplesamlphp idp instance and it *should* work. There may be some logout bindings and saml flows which it doesn't support. I haven't tested it again OpenAM or any other saml2 idp's.

In theory just calling the SSPHP logout function should handle it all and you're not really aware if it:

https://github.com/CatalystIT-AU/moodle-auth_saml2/blob/master/auth.php#L319
