### ISSUE TITLE
Certificate changes in IdP Metadata XML not automatically updated?

### ISSUE THREAD

**Issue by praj** [catalyst/moodle-auth_saml2#150]
**What happened?**

Change of the X509 certificate used by the IdP doesn't get updated until saving the auth/saml2 plugin configuration settings. 

Prior to this, an SSL certificate error appears (because it is using the old certificate):

```Exception - Unable to validate Signature Debug:
Error code: generalexceptionmessage
* line 157 of /auth/saml2/extlib/saml2/src/SAML2/Utils.php: Exception thrown
* line ? of unknownfile: call to SAML2_Utils::validateSignature()
* line 227 of /auth/saml2/extlib/saml2/src/SAML2/Message.php: call to call_user_func()
* line 201 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php: call to SAML2_Message->validate()
* line 510 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php: call to sspmod_saml_Message::checkSign()
* line 120 of /auth/saml2/extlib/simplesamlphp/modules/saml/www/sp/saml2-acs.php: call to sspmod_saml_Message::processResponse()
* line 35 of /auth/saml2/sp/saml2-acs.php: call to require()
```
**What you expected:**

I figured the IdP metadata XML would be automatically updated?

My understanding is that the updated metadata is stored in $CFG->dataroot under saml2/idp.xml.

Is the only trigger to update this file a save of the plugin settings (auth.php -> validate_form())

**Comment by praj** [comment]
Just following up on this thread to see if there is a reasonable solution to this? Perhaps a schedule task that checks the metadata XML once a day (or as frequently as required) for any updates?

**Comment by brendanheywood** [comment]
This feature has just landed, but only in the 3.3+ stable branch and not for older moodles.

What version are you using?

**Comment by praj** [comment]
Hi Brendan,

Thanks for letting me know - this was on versions prior to the 3.3+ stable
branch.

Praj

**Comment by roperto** [comment]
Closing this as the features on 3.3 are now available in the master branch.
