### ISSUE TITLE
Profile Data Mapping Issue [using Moodle 3.3.2 (Build: 20170911)]

### ISSUE THREAD

**Issue by razzak** [catalyst/moodle-auth_saml2#166]
First of all thank you so much for developing this plugin. 

I have configured the ADFS and Moodle settings as per the instructions provided. 

I got success in Authentication to Moodle. Please see the screenshots below.

![screenshot](https://user-images.githubusercontent.com/1940559/33551681-205e8288-d918-11e7-8877-dc9aa8eaf282.png)

I am able to get the connection using email Address.

![screenshot2](https://user-images.githubusercontent.com/1940559/33551715-40f8f6a4-d918-11e7-81b9-6fcaed1078ca.png)

Authenticated user can access the Moodle and can view edit profile page, but none of the attributes/fields were pre-filled. Looks like some attributes mapping issue. Please see the screenshot of edit profile page with blanks fields even though it is getting retrieved in Test.php page.

![screenshot8](https://user-images.githubusercontent.com/1940559/33551846-af13777c-d918-11e7-9a36-1cb34e75b65b.png)

Here are the mapping settings currently have:
![screenshot3](https://user-images.githubusercontent.com/1940559/33551875-d3f70220-d918-11e7-830e-ca4c1bb0f0ad.png)

I tried with direct URLs in mapping but it gives errors. Please see the screenshots below:
![screenshot4](https://user-images.githubusercontent.com/1940559/33551902-fd2e9a2c-d918-11e7-8344-5b190a7da526.png)

![screenshot6](https://user-images.githubusercontent.com/1940559/33551910-0122f98e-d919-11e7-9b77-14c3df32336c.png)

![screenshot5](https://user-images.githubusercontent.com/1940559/33551918-09040882-d919-11e7-8576-d1bf75239702.png)

Please guide me where I am doing mistake and how I can fix it. 

We need to prefil the First name , Surname and the e-mail address.

Looking forward for you help.

Regards
Razzak

**Comment by brendanheywood** [comment]
hi @razzak,

This is actually a core bug in moodle, you can see more details and a workaround here:

https://github.com/catalyst/moodle-auth_saml2/issues/124

This is coming up repeatedly so I've raised a core tracker for moodle itself here:

https://tracker.moodle.org/browse/MDL-60968

and I'll provide a patch. Please go and vote and / or comment on that, I will supply a patch shortly for it.

**Comment by roperto** [comment]
Closed, see #124
