### ISSUE TITLE
XML Parser error

### ISSUE THREAD

**Issue by raryaweb** [catalyst/moodle-auth_saml2#170]
Hi Team, we are facing an xml parser error 

Exception - Unable to parse xml - FATAL[9]: PCDATA invalid char value 11 in "string" at line 1 on column 10466

any help on how i can tackle this is much appreciated. Thx!

![image](https://user-images.githubusercontent.com/7710518/34203017-a473bbae-e59f-11e7-9251-6ca1bb28700c.png)

**Comment by brendanheywood** [comment]
That error is probably exactly what is say, try throwing your xml into a 3rd party validator and see if it's valid or not.

**Comment by raryaweb** [comment]
Hi Bren,

You are right the xml is not valid because it has a special char in it, I tried removing that special char to fix this but ended up with another error => Exception - Reference validation failed

because i manipulated the response the validation fails :( 

is there a way to clean xml and avoid this error?

#changes i made was in auth/saml2/extlib/saml2/src/SAML2/DOMDocumentFactory.php

fromString function 

return preg_replace ('/[^\x{0009}\x{000a}\x{000d}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}]+/u', ' ', $string);

**Comment by brendanheywood** [comment]
You have still not provided any details on what you are actually trying to do: How can you reproduce this issue? Is this while trying to important xml metadata or while trying to login afterwards?

I don't think you should be touching the saml library at all to workaround some invalid xml, the xml itself needs to be fixed at the source. Changing the xml could affect the signatures and encryption so probably wouldn't work anyway.

**Comment by roperto** [comment]
Closing this as not a SAML2 issue.
