### ISSUE TITLE
Returns to the course page after login

### ISSUE THREAD

**Issue by carlotafuro** [catalyst/moodle-auth_saml2#171]
Hi Brendan,

I would like to force the user to log in after following the link to one moodle course page from a different site or from his bookmarks.

For example if the link to the course page is https://moodle.example.com/course/view.php?id=19

I tried with:

https://moodle.example.com/auth/saml2/login.php?wants=https%3A%2F%2Fmoodle.example.com%2Fcourse%2Fview.php%3Fid%3D19

but after login the user returns to the moodle home page and not to the course page.

can you help me get the desired behavior?

Thank you very much
Carlo

**Comment by brendanheywood** [comment]
Just link directly to the course page, don't include anything saml or login related at all. If the course requires login they will get redirected to login and then go back to the course page. This is all just out-of-the-box behavior with moodle generally. It sounds like what you really want it to just change the course or site settings to force login.

See also:
https://docs.moodle.org/33/en/Site_policies#Force_users_to_login

You may need to disable guest mode for the site and / or course:
https://docs.moodle.org/33/en/Guest_access
