### ISSUE TITLE
Plugin cannot be configured with 2018011500

### ISSUE THREAD

**Issue by fsesterh** [catalyst/moodle-auth_saml2#174]
**What happened?**

After upgrading to version 2018011500 the plugin can no longer be set up (settings link is missing). Login via saml2 fails with error "unknown idp".

Tested with moodle 3.3.4.

**What you expected:**

Plugin still workst ;)

**Comment by mattporritt** [comment]
Hi fsesterh,
Did you download the updated version of the plugin from the Moodle plugin directory or clone it here from github?
If you got it from the plugin directory, did you download the version for Moodle 3.3? There are two new versions in the directory one for 3.3 and above and one for 3.2 and below.
If you got it from github which branch did you clone?

Cheers,
Matt P

**Comment by fsesterh** [comment]
Hi Matt,
moodle is installed via git MOODLE_33_STABLE branch. Update from there via git pull to 3.3.4. Plugin was downloaded as a ZIP and then updated via the automatic download capabilites of moodle. I guess this is the same as downloading the new version from the moodle repo manually.

I rolled back plugin version 2017112300 and its working again.
-Fabian

**Comment by mattporritt** [comment]
Hi Fabian,
Can you try installing this version from the plugins directory: https://moodle.org/plugins/download.php/15782/auth_saml2_moodle34_2018011500.zip or clone here from github and use the: MOODLE_33PLUS branch

Let me know how you go.

Matt P

**Comment by fsesterh** [comment]
Hi Matt,
I used the version from the ZIP file. This one works. Weird. Why does the moodle repo have a different version?
-Fabian

**Comment by pbettens** [comment]
Hi,
some issue for me.

- I update plugin via moodle and after update no saml conection. i see "test parameters" but no "parameters". 
- i try (re)install plugin using zip file via moodle admin and all run fine.

thanks
