### ISSUE TITLE
Setup IdP inside the saml plugin

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_saml2#175]
**What happened?**

So there is a couple angles for why this would be a good thing to have but primarily it boils down to:

1) Having a way of exposing a moodle as a proper IdP, so users can log into it as they normally would, and then can log into another moodle acting as an SP. This would be a direct conceptual replacement for mnet.

2) For regression testing. Unit testing saml only gives us very superficial coverage, we really need to have a simple way to automate setting up an idp and then running a variety of sp scenarios against that test idp. This is also a bit hairy because various IdP's have different flavors of saml, so we would want perhaps a set of various idp configurations that we can swap between and have travis run some behat tests against.

So this issue is more leaning towards the second task but should put in place some of the code to make the first easily done.

Rough checklist of tasks:

* [ ] create a set place for the various idp's with different config 'profiles's to live, something like:

```
/auth/saml2/idp/basic/
/auth/saml2/idp/nameid/
/auth/saml2/idp/signed/
/auth/saml2/idp/encrypted/
```

eg one could be configured to use a NameID and another to not, one could encrypt everything, etc. Behat would run through them in order from simple to advanced. Each directory is simply a config file, the mechanics of how the idp endpoints work would be similar to the way we 'proxy' the sp code

So a more tangible example for one of the idp configurations might be:

http://test.moodle.local/auth/saml2/idp/metadata.php/basic/

This would serve the idp xml endpoint, which would then in the behat be wired up to the sp.

This xml would declare bindings like this:

```
http://test.moodle.local/auth/saml2/idp.php/basic/SSOService.php
http://test.moodle.local/auth/saml2/idp.php/basic/SingleLogoutService.php
```

There is a bit of PATH_INFO magic going on here, the idp.php script will handle loading up the config required and then delegate to the shared service file which then does what it needs and delegates off to the internal SSP library files. One of the reasons for structuring it this way is it means that the cookies for each test idp profile can be isolated to a sub path.

The various idp configs might be something like:

```
/auth/saml2/basic/config.php
/auth/saml2/nameid/config.php
```

Each config file would be the absolute minimum needed for each test, and as much as possible shared config would contain the session handling, the certs dir, the logging dir, etc etc.

So for example the basic/config.php file contain nothing at all. The signed/config.php file might contain just one line:

```
$config = (
    'metadata.sign.enable' => true,
);
```

Shared internals:

```
/auth/saml2/idp/config-shared.php
/auth/saml2/idp/SSOService.php
/auth/saml2/idp/SingleLogoutService.php
```

* [ ] I think we would load the shared config first so that the different idp profiles can override it if desired.

* [ ] for the rest of a minimal idp config you can follow the steps here but with a couple exceptions:

https://simplesamlphp.org/docs/stable/simplesamlphp-idp

* [ ] the test idp itself will need it's own certs. These are only used for testing so I'd be happy to just generate some fixed ones and commit them into source. The other option is to autogenerate them on demand like the sp does, but it adds a few more moving parts so the simpler we can make this to more robust and deterministic the testing can be.

* [ ] for testing need to make sure that logging into the test idp, which would be under the same domain as moodle and the internal sp, gets it's own distinct cookie and session store.

* [ ] to be a bit paranoid, it would be good to have each config profile store it's sessions and have cookie names which include the profile so they are all locked down scope. ie the cookied for the 'basic' idp profile would only be accessible to pages inside:

http://test.moodle.local/auth/saml2/idp.php/basic/

* [ ] Each idp profile will have it's own login page, which like the other service page will be behind the idp.php PATH_INFO magic. 

http://test.moodle.local/auth/saml2/idp.php/basic/login.php

* [ ] the actual auth source should I think be hard coded and shared between all the test idp profiles. This is so we can hard code the passwords into behat. We need to be super careful that these identities never leak in any way into either the sp code or the moodle auth code so we don't run the risk of someone being able to log into a prod moodle via a hard coded password.

```
config/authsources.php 
<?php
$config = array(
    'userpass' => array(
        'exampleauth:UserPass',
        'student1:student1' => array(
            'uid' => array('student1'),
            'eduPersonAffiliation' => array('member', 'student'),
            'firstname' => array('Student'),
            'lastname' => array('One'),
            'email' => array('brendan+student1@examplenet'),
        ),
        'staff2:staff2' => array(
            'uid' => array('staff2'),
            'eduPersonAffiliation' => array('member', 'employee'),
            'firstname' => array('Staff'),
            'lastname' => array('Two'),
        ),
    ),
);
```

### behat testing ###

So now with all this in place, it should be as simple as in a behat test declare that the moodle sp side config should point the a particular idp profile xml, then just try and login to moodle and do the redirect dance and test it all out and then assert that you get back to the page you wanted and are logged in as X. Rinse and repeat in different behat tests with different settings.

**Comment by roperto** [comment]
I added a simple saml2 server as I needed for behat testing, not aware of this issue I implemented in a different way. We can use what I did as a starting point or not. Whoever gets this issue please have a look in the travis file first as part of that work could be there.

**Comment by roperto** [comment]
I am closing this as we achieved behat testing, which was the main objective. We can create a new ticket to optimize it the test speed (install simplesamlphp and prereqs) becomes an issue.
