### ISSUE TITLE
Specifying saml=on lands you to the standard login page

### ISSUE THREAD

**Issue by cristianomariacumer** [catalyst/moodle-auth_saml2#18]
Hello,

I'm playing around with this plugin and I did notice that specifying 

https://moodlesite.org/login/index.php?saml=on

doesn't bring you to the IdP page but on the standard moodle login form.

I think the issue is [here](https://github.com/CatalystIT-AU/moodle-auth_saml2/blob/fb25ed27fe45f23af343cdd1440bcb1bbbd1f61f/auth.php#L160-L163) why is return called at the end instead of triggering the saml authentication?

**Comment by brendanheywood** [comment]
Thanks, you are probably right but I'd like to cover all this logic with unit tests first before I actually change any of it. Feel free to have a crack but let me know if you start on it so we don't double up

**Comment by cristianomariacumer** [comment]
Hello @brendanheywood,

Please go ahead with the tests, I will wait for your fix.

**Comment by nhoobin** [comment]
This issue has been resolved with pull request #48, ?saml=on will now redirect to the IdP page.
