### ISSUE TITLE
SAML2 assumes configuration when logout hook is called

### ISSUE THREAD

**Issue by dustinbrisebois** [catalyst/moodle-auth_saml2#188]
When logging out in an unconfigured instance the LMS faults with:

> PHP message: Default exception handler: Exception - Setting secure cookie on plain HTTP is not allowed. Debug: 
> Error code: generalexceptionmessage
> * line 287 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Session.php: SimpleSAML_Error_Exception thrown
> * line 54 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML_Session::getSessionFromRequest()
> * line 461 of /auth/saml2/auth.php: call to SimpleSAML_Auth_Simple->isAuthenticated()
> * line 59 of /login/logout.php: call to auth_plugin_saml2->logoutpage_hook()" while reading response header from upstream, client: 192.168.0.160, server: _, request: "POST /moodle33/login/logout.php

Whereas this is resolved by adding:

to auth.php on line 457 (above $auth = new SimpleSAML_Auth_Simple($this->spname); )

to be:

`        if($this->defaults['idpname'] == '') { return null; }
`

**Comment by roperto** [comment]
Hi , have you tried setting `$CFG->cookiesecure` ? I could not reproduce it here.

**Comment by brendanheywood** [comment]
Can't reproduce, pretty sure this was already fixed
