### ISSUE TITLE
Issues during upgrade from UPTO32 into new master

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_saml2#200]
After the upgrade, the following errors are observed:

* Login page:

Notice: Undefined index: ... in .../auth/saml2/auth.php on line 127

* SAML login page:

Exception - Class 'Twig_Loader_Filesystem' not found

**Comment by roperto** [comment]
Closed by #201

**Comment by effebi68** [comment]
I performed the IdP metadata refresh (and manually run admin/cli/cron.php to be sure it did it), but still see

Eccezione - Class 'Twig_Loader_Filesystem' not found

Maggiori informazioni su questo errore

×Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 170 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/XHTML/Template.php: Error thrown
line 202 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/XHTML/Template.php: call to SimpleSAML_XHTML_Template->setupTwigTemplatepaths()
line 130 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/XHTML/Template.php: call to SimpleSAML_XHTML_Template->setupTwig()
line 1226 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php: call to SimpleSAML_XHTML_Template->__construct()
line 540 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Utilities.php: call to SimpleSAML\Utils\HTTP::submitPOSTData()
line 60 of /auth/saml2/extlib/saml2/src/SAML2/Compat/Ssp/Container.php: call to SimpleSAML_Utilities::postRedirect()
line 48 of /auth/saml2/extlib/saml2/src/SAML2/HTTPPost.php: call to SAML2\Compat\Ssp\Container->postRedirect()
line 314 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to SAML2\HTTPPost->send()
line 298 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->sendSAML2AuthnRequest()
line 336 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->startSSO2()
line 430 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->startSSO()
line 193 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Source.php: call to sspmod_saml_Auth_Source_SP->authenticate()
line 161 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML_Auth_Source->initLogin()
line 103 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML\Auth\Simple->login()
line 389 of /auth/saml2/auth.php: call to SimpleSAML\Auth\Simple->requireAuth()
line 267 of /auth/saml2/auth.php: call to auth_plugin_saml2->saml_login()
line 76 of /login/index.php: call to auth_plugin_saml2->loginpage_hook()

**Comment by roperto** [comment]
Hi @effebi68 

I had similar issue, it was due to SAML not finding which IDP to use therefore sending a discovery request. Our plugin does not handle that situation because Moodle is supposed to properly identify the IdP used.

Can you make sure yo uare using the latest version 2018022203 as we had released 3 versions in the last 3 days.

If you still have problems, please create a new issue here so it doesn't get forgotten.

Thank you

Daniel
