### ISSUE TITLE
still "Class 'Twig_Loader_Filesystem' not found" (Moodle 3.2.x -> 3.4.1; 20180203 SAML2 plugin)

### ISSUE THREAD

**Issue by effebi68** [catalyst/moodle-auth_saml2#202]
We wanted to upgrade our production Moodle 3.2.x installations to the latest 3.4.1 with the current SAML2 module; a test using auth_saml2_moodle34_2018020200.zip and all the other plugins we are using has been working for a few days, so I didn't expect any issue.

However, with the latest auth_saml2_moodle34_2018020203.zip I got the "Class 'Twig_Loader_Filesystem' not found" fatal error.

After a glance at the plugin KB on Github, I also set the IdP metadata refresh option (and manually run admin/cli/cron.php to be sure it did it), but still see

Eccezione - Class 'Twig_Loader_Filesystem' not found

Maggiori informazioni su questo errore

×Debug info:
Error code: generalexceptionmessage
×Stack trace:
line 170 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/XHTML/Template.php: Error thrown
line 202 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/XHTML/Template.php: call to SimpleSAML_XHTML_Template->setupTwigTemplatepaths()
line 130 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/XHTML/Template.php: call to SimpleSAML_XHTML_Template->setupTwig()
line 1226 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php: call to SimpleSAML_XHTML_Template->__construct()
line 540 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Utilities.php: call to SimpleSAML\Utils\HTTP::submitPOSTData()
line 60 of /auth/saml2/extlib/saml2/src/SAML2/Compat/Ssp/Container.php: call to SimpleSAML_Utilities::postRedirect()
line 48 of /auth/saml2/extlib/saml2/src/SAML2/HTTPPost.php: call to SAML2\Compat\Ssp\Container->postRedirect()
line 314 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to SAML2\HTTPPost->send()
line 298 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->sendSAML2AuthnRequest()
line 336 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->startSSO2()
line 430 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->startSSO()
line 193 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Source.php: call to sspmod_saml_Auth_Source_SP->authenticate()
line 161 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML_Auth_Source->initLogin()
line 103 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML\Auth\Simple->login()
line 389 of /auth/saml2/auth.php: call to SimpleSAML\Auth\Simple->requireAuth()
line 267 of /auth/saml2/auth.php: call to auth_plugin_saml2->saml_login()
line 76 of /login/index.php: call to auth_plugin_saml2->loginpage_hook()

Should it matter (though I do not think so), our VMs are either Jessie with PHP 7.0 from DotDeb or Stretch, and we are using MariaDB and nginx.

**Comment by yivi** [comment]
Having the same issue with latest version.

Twig libraries are absent, and looked for in Template.php.

Are we supposed to install Twig libraries separately from this module?

**Comment by yivi** [comment]
It never gets there, but there are going to be trouble also with `Twig\Environment` and `Twig\Extensions\Extension\I18n` as both are used on lines 12 & 13 of Template.php (inside the integrated simplesaml module), but do not exist either:

    use JaimePerez\TwigConfigurableI18n\Twig\Environment as Twig_Environment;
    use JaimePerez\TwigConfigurableI18n\Twig\Extensions\Extension\I18n as Twig_Extensions_Extension_I18n;

**Comment by yivi** [comment]
As a workaround, we've cloned Twig at `saml2/extlib/simplesamlphp/lib/Twig`, and we've added the following line at line 34 in the module's autoloader (`saml2/_autoload.php`):

    'Twig'       => 'simplesamlphp/lib/'

**Comment by roperto** [comment]
Hi @yivi -- I noticed the missing libraries, we'll probably incorporate into the plugin as its done with the other extlibs.

However, fixing that problem, did it fix your saml? In my experience, when I have the TWIG required to render something it means that there is another underlying error.

Let me know what you find, soon we'll release another version with the lib included.

**Comment by roperto** [comment]
This issue has been addressed, but it will probably expose another issue that cause twig to be required. Most likely is just a configuration problem (identity provider) but please open a new issue if something new arises.
