### ISSUE TITLE
PHP 5.5 Lint failing in extlib directory.

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_saml2#226]

**Comment by roperto** [comment]
It shouldn't bother anyone as no-one should be using PHP 5.5 ... except some people do!

**Comment by danmarsden** [comment]
we have a handful of clients still on Ubuntu 14.04 (LTI) which comes with PHP 5.5 and is supported until April 2019 - some other sites will still be in the process of moving off 14.04 to the next lti (16.04) which comes with php 7 which is really nice. :-)

**Comment by roperto** [comment]
Hi @danmarsden ... no problems, we do too :-) but I dont see the PHP 5.5 . If using PHP 5.5 we should at least try to use 5.5.38 instead of 5.5.9 but that's a conversation for another thread.

Although I haven't deployed in the Moodle Plugin Directory yet, `master` has already been fixed, if you find some other issue please let me know.

**Comment by roperto** [comment]
Fix released in v2018032600
