### ISSUE TITLE
SAML2 exception: Responder/RequestDenied

### ISSUE THREAD

**Issue by fsesterh** [catalyst/moodle-auth_saml2#230]
**What happened?**
After upgrading our test environment to Moodle 3.3.5 all I get with SAML is this error upon login:

SAML2 exception: Responder/RequestDenied

Please provide as many of the following as applies:
saml2 debug log looks like this:

[simplesaml_moodle335.txt](https://github.com/catalyst/moodle-auth_saml2/files/1828497/simplesaml_moodle335.txt)

To me it looks like SAML receives a response.

Moodle: 3.3.5
SAML2: 2018032000

**What you expected:**

SAML2 auth should still work :)

**Comment by fsesterh** [comment]
Updated to SAML 2018032900, same issue.

**Comment by brendanheywood** [comment]
No news on this one?

**Comment by redesitos** [comment]
Hi same, error moodle 3.7, with ultimate plugin version moodle.org

**Comment by brendanheywood** [comment]
That is an error from your idp and it's rather opaque and could mean a number of things. You will need someone on the idp side to debug this to see why it is denying it. It could be worth regenerating your certificates, and re-ingesting the xml metadata both ways to re-establish trust.

**Comment by brendanheywood** [comment]
Closing this, please see https://github.com/catalyst/moodle-auth_saml2/issues/488
