### ISSUE TITLE
wrong defaults in tolower and mdlattr.

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-auth_saml2#231]
https://github.com/catalyst/moodle-auth_saml2/commit/e1c66cd198ed83e851a3e3345abe183c878db8a6#diff-3a8270dae2b17999b935edc868c22cebR187

the default for tolower should be 0 - you were meaning to change the "mdlattr" from 0 -> username instead.

**Comment by roperto** [comment]
Thank you Dan

Fix released in v2018032600
