### ISSUE TITLE
Get access to moodle token

### ISSUE THREAD

**Issue by yoavst** [catalyst/moodle-auth_saml2#242]
Since the plugin eliminate the pair *Username and password* of the moodle, I can no longer use `/login/token.php` as described [here](https://stackoverflow.com/questions/44652206/getting-information-from-the-moodle-api-as-a-student). the generated `MoodleSession` is not a valid token[1]

Any idea how do I generate a token?

[1] Tried `GET http://moodle.tau.ac.il/webservice/rest/server.php?wstoken=MOODLE_SESSION&wsfunction=core_course_get_courses&moodlewsrestformat=json` but it returned invalid token exception

**Comment by danmarsden** [comment]
Hi Yovast - the best place to ask questions and get Moodle support is the community forums on moodle.org. This is the bug tracker for a 3rd party authentication plugin. please use the forums here for your question: https://moodle.org/course/view.php?id=5

**Comment by yoavst** [comment]
I thought I should ask here since the plug-in change the way authentication works.
I'll ask there, thanks!
