### ISSUE TITLE
Unable to login to MOODLE LMS using Active Directory credentials

### ISSUE THREAD

**Issue by razzak** [catalyst/moodle-auth_saml2#245]
Hi

First of all I would like to thank you for developing this plug-in. It is very simple to configure and use.

We have done the SSO configuration correctly and it worked fine. But now we are facing a critical issue maybe because of our implementation process. I need your help/suggestion in order to let me know whether our implementation process is correct or not? How can we resolve the issue?

Process we followed:
1. Installed and configured the plugin and tested the SSO which worked fine and accounts got auto created correctly.
2. After the testing we created all the user accounts with some default/dummy passwords in MOODLE manually as most of the user fields are not available in Active Directory.
3. Users were able to access the LMS using SSO button instead of entering credentials on login page and everything is working fine.

Issues:
1. Users were not able to login to LMS using the Active Directory credentials to access the LMS when they are outside of the company network.

2. How can we make the LMS to provide access using active directory credentials?

3. What is the correct way of setting it up? Basically our requirement is to provide two options to the users:
    a) Use the SSO button when they are in network.
    b) Use same Active directory credentials and enter in username and password fields of LMS login page and get access when they are not connected to network. 

We wanted to have same username and passwords of Active Directory and in MOODLE LMS.

Any help will be greatly appreciated.

Looking forward for your help.

Regards
Razzak

**Comment by danmarsden** [comment]
Hi Razzak, 
Supporting multiple methods of authentication is quite common for Moodle sites.

We can provide you with commercial level support with configuration and management of your Moodle site - you can see more about our services here: https://catalyst.net.nz/

feel free to get in touch with us privately if you would like information on our rates etc.

If you are looking for free support/help configuring your site the best place to ask for free help is the community forums on moodle.org - good luck!
