### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by anithachavva341** [catalyst/moodle-auth_saml2#248]
git clone git@github.com:catalyst/moodle-auth_saml2.git auth/saml2
Cloning into 'auth/saml2'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I am getting error and  i tried to install through this url 
https://moodle.org/plugins/auth_saml2

showing the same error Pls help me

**Comment by danmarsden** [comment]
doesn't look like you have set up access to github properly

best place to ask for this sort of help is in the community forums on moodle.org - Google might show up a link like this which might help too:
https://help.github.com/articles/error-permission-denied-publickey/

For further generic help like this please ask for help in the moodle.org community forums - good luck!

**Comment by roperto** [comment]
on a side note, if you just want to clone you may want to use the http version

git clone https://github.com/catalyst/moodle-auth_saml2.git auth/saml2
