### ISSUE TITLE
Unable to Install Plugin. 

### ISSUE THREAD

**Issue by justin-castleman** [catalyst/moodle-auth_saml2#259]
Hello. I am trying to install the plugin into my Moodle 3.4 environment. I am able to download the file from the Moodle Plugins site. When I try and install it I get an error during the validation phase. 

The error I receive is below:

Validating Auth_SAML2 ...
core_plugin/corrupted_archive_structure

Any ideas on how to resolve this?

**Comment by danmarsden** [comment]
Sounds like you are using the Moodle installer tool and I suspect you will see this error when trying to install any plugin - not just the saml2 plugin.

You are probably missing some php extensions in your site. You should go to: Administration > Site administration > Server > Environment. and check that your server meets all the right system requirements.

If that doesn't work, try asking for help in the moodle.org community forums.
