### ISSUE TITLE
Style changes messes with Define roles layout

### ISSUE THREAD

**Issue by sharpchi** [catalyst/moodle-auth_saml2#269]
The changes to styles.css (https://github.com/catalyst/moodle-auth_saml2/commit/a0b9166a42322c68e1bba78105c07ef15e405563#diff-4e7bb40584b55a44f4657b188986bff4) adds 
```
.mform .fitem div.fitemtitle {
    width: 0;
}

.mform .fitem .felement {
    margin-left: 0;
}
```
This breaks the layout on the define roles edit page (and possibly other places).

![layoutbroken](https://user-images.githubusercontent.com/3774280/42027435-9f2fcb12-7ac1-11e8-820c-a37c12fd78b6.png)

This was on Moodle 3.4 using a child theme of Boost.

**Comment by danmarsden** [comment]
Thanks for the report @sharpchi - that's definitely not correct css - we'll get someone onto that asap.

**Comment by danmarsden** [comment]
@rhell4 just pushed a fix for this - thanks!
