### ISSUE TITLE
IDP Metadata containing X509 certificate with BEGIN header leads to breaking methods getPublicKeys and checkSign

### ISSUE THREAD

**Issue by danowar2k** [catalyst/moodle-auth_saml2#272]
**What happened?**

If the IDP metadata contains a X509 certificate, e.g. for signing SAML responses, and the X509 certificate is in PEM format complete with enclosing BEGIN and END, the method getPublicKeys (https://github.com/catalyst/moodle-auth_saml2/blob/0fccd77d1bedac738429aa11b24d59bb9880d325/extlib/simplesamlphp/lib/SimpleSAML/Configuration.php#L1316)
removes the whitespace in the PEM header and footer. 
This produces "-----BEGINCERTIFICATE-----" etc. . If you try to extract a public key from the certificate with such a broken header, that doesn't work anymore.

But there is more: The then returned certificate with the wrong header is prepended and suffixed with another (!) PEM header and footer in https://github.com/catalyst/moodle-auth_saml2/blob/0fccd77d1bedac738429aa11b24d59bb9880d325/extlib/simplesamlphp/modules/saml/lib/Message.php#L168 . Note that this happens even if the old header is not broken.

The question is: Does the SAML standard or something explicitly say that an X509Certificate element must only contain headerless PEM certificates? Or is this an oversight on the part of SimpleSAMLphp?

**What you expected:**

I would expect a PEM certificate with a header and footer to not be altered by removing any whitespace from the header or footer.
I would also expect to not add the header and footer when it is already there.

**Comment by danowar2k** [comment]
Well, in the last composite version of the [SAML Metadata specification](https://www.oasis-open.org/committees/download.php/35391/sstc-saml-metadata-errata-2.0-wd-04-diff.pdf), it says that

> [E69]The <ds:KeyInfo> element is a highly generic and extensible means of communicating key
> material. This specification takes no position on the allowable or suggested content of this element, nor on
> its meaning to a relying party. As a concrete example, no implications of including an X.509 certificate by
> value or reference are to be assumed. Its validity period, extensions, revocation status, and other relevant
> content may or may not be enforced, at the discretion of the relying party. The details of such processing,
> and their security implications, are out of scope; they may, however, be addressed by other SAML profiles.

So, it probably should not be assumed anything regarding the content of X509Certificate. Therefore, it should be tested if it has a header and footer or not etc.

**Comment by danowar2k** [comment]
It occurred to me that this may be a problem/bug in the SimpleSAMLphp library. What do you think?

**Comment by brendanheywood** [comment]
Sorry for the delay, yes this seems like a bug in the upstream library. Please see if it is logged there and if not open an issue there and cross link it to here. If / when it is fixed we will pull it in.

**Comment by danowar2k** [comment]
I opened an issue at https://github.com/simplesamlphp/simplesamlphp/issues/999

**Comment by danowar2k** [comment]
I like the issue number, the end is near ;-)

**Comment by brendanheywood** [comment]
thanks @danowar2k - this looks reasonably simple, are you able to make a PR to fix this in SSP?

**Comment by danowar2k** [comment]
I don't know if I would be allowed to... See ticket.

**Comment by brendanheywood** [comment]
Well what he says all makes sense, and I've never come across the need for this, so :man_shrugging: 

So why is your idp like this, or is this something custom?

**Comment by danowar2k** [comment]
I don't know if our IDP metadata is handmade or generated. I've avoided the "bug" mainly because the IDP is in house and I asked our SSO people to remove the PEM headers from the IDP certificate. So...at least now I can point to the SAML 2.0 metadata standard and say "Don't put PEM headers in your files, the standard says so".

**Comment by danowar2k** [comment]
I'd say we can close this here, cause there is no real bug, and the mistake was self-produced.

**Comment by brendanheywood** [comment]
Yep ok. It may help if you also point them at various open saml2 tests like this to validate conformance:

http://www.testshib.org/index.html
