### ISSUE TITLE
Customise you do not have an account in Moodle message

### ISSUE THREAD

**Issue by praj** [catalyst/moodle-auth_saml2#274]
**What happened?**

When a user attempts to login via SAML2 but does not have an account in Moodle they are presented with the message:

"You have logged in succesfully as \'{$a}\' but do not have an account in Moodle."

Firstly there is typo, the word _successfully_ is spelled incorrectly.

Secondly, it would be good if we could define this message in the plugin configuration so you don't have to modify the language pack for it as it is something that normally needs adjusting to suit the appropriate action should take (e.g. contacting support etc).

The language pack string is ./lang/en/auth_saml2.php is "nouser".

**Comment by brendanheywood** [comment]
I've just patched the typos, but customizing this should be done in the language gui as that is exactly what it is for.

https://docs.moodle.org/35/en/Language_customisation
