### ISSUE TITLE
Login from Moodle to .Net 

### ISSUE THREAD

**Issue by amir201808** [catalyst/moodle-auth_saml2#277]
Hello,
From .Net to moodle login is working. 
Is there any possibility to log in from **moodle to .net** (i.e. the opp. case) ?
Thanks in advance for  your help. I am using moodle 3.5 version

**Comment by amir201808** [comment]
Is there any possibility we can achieve using using **SAML2 Single sign on** moodle plugin or any other plugin.

**Comment by danmarsden** [comment]
It would be better for you to set up a proper IDP and link both your Moodle and .net applications to the same IDP - There are also some plugins that allow you to use Moodle as the authentication provider to other applications, but the best place to get help with this is in the community forums on moodle.org.

Good luck!
