### ISSUE TITLE
Can't translate "Select a login service" because not a text resource

### ISSUE THREAD

**Issue by fbuland** [catalyst/moodle-auth_saml2#281]
Hi,
**Issue**
When using with multiple IdP, when a user tries to connect, a page is displayed with "Select a login service" title.
With Moodle, we can't translate the "Select a login service" text or modify this text.

In file moodle-auth_saml2-master/lang/en/auth_saml2.php, there is no textual resource for text "Select a login service"

**What is expected:**
Be able to modify or translate the "Select a login service" with Moodle. So add  "Select a login service" text in  moodle-auth_saml2-master/lang/en/auth_saml2.php

Regards,
Franck Buland

**Comment by danmarsden** [comment]
Thanks for the report - looks like it's coming from here:
https://github.com/catalyst/moodle-auth_saml2/blob/046e8a5c1e7bfc3bf7176ad29914b10c5367b970/selectidp.php#L150

Feel free to help us work on this by submitting a pull request with the change! - thanks!
