### ISSUE TITLE
403 error when configuring

### ISSUE THREAD

**Issue by tinalrowe** [catalyst/moodle-auth_saml2#284]
I have installed the plugin on a hosted moodle.

I am following the instructions

Home ► Site administration ► Plugins ► Authentication ► SAML2

1. Set the Idp URL to: https://www.testshib.org/metadata/testshib-providers.xml 
2. Set dual auth to Yes
3. Set auto create users to Yes
4. Click on 'Download SP Metadata'

At point 4 I get a 403 error, forbidden.  I was guessing that has something to do with permissions on the folder, but I can't pretend to understand how servers work.  The permissions on the certificates in the moodledata folders are 0660. 

I have debug set to developer for Moodle 

So I am now out of things I understand.

Any help would be appreciated.

Thanks

Tina

**Comment by danmarsden** [comment]
Hi Tina, 

Unfortunately we are not in a position to provide free installation and configuration support for our plugins. If you are looking for free support the best place to ask for help is in the community forums on moodle.org - I'd recommend you ask for help in the Authentication forum here:
https://moodle.org/mod/forum/view.php?id=42

If you are looking for commercial level support feel free to drop us a private message and we can provide information on our rates etc.

Good luck!
