### ISSUE TITLE
Error after installing latest version

### ISSUE THREAD

**Issue by Richardvi** [catalyst/moodle-auth_saml2#286]
This is the error I'm getting:

Exception - [ARRAY]: The option 'Format' is not a valid string value.

More information about this error

×Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 197 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Source.php: SimpleSAML_Error_UnserializableException thrown
line 161 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML_Auth_Source->initLogin()
line 103 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML\Auth\Simple->login()
line 474 of /auth/saml2/auth.php: call to SimpleSAML\Auth\Simple->requireAuth()
line 324 of /auth/saml2/auth.php: call to auth_plugin_saml2->saml_login()
line 308 of /auth/saml2/auth.php: call to auth_plugin_saml2->loginpage_hook()
line 2622 of /lib/moodlelib.php: call to auth_plugin_saml2->pre_loginpage_hook()
line 12 of /admin/upgradesettings.php: call to require_login()

**Comment by danmarsden** [comment]
@Richardvi can you please provide more information about the Moodle version you are using and what exact version of the saml2 plugin you are using?

**Comment by Richardvi** [comment]
Hi Dan,
The error corrected itself after logging out, logging in with a manual admin account, then log out again and log in with a SAML account.

The Moodle version I'm using is 3.5.

Just to be clear: the error is no longer there.

**Comment by danmarsden** [comment]
thanks for the update - was the saml user you were logging in with a site admin?

Typically we run our upgrades via cli instead of logging in and running them via /admin

**Comment by Richardvi** [comment]
Yes, it was a SAML admin and at the final stage of the update proces the admin got logged out. I could not login with the same account, but that might be a session problem or something. I can not remember if I closed all browsers.

Then, after logging in as a manual admin, I might have finalized the update process. After that, the SAML admin could also log in again.

This is just my two cents.

**Comment by danmarsden** [comment]
relates to old code that isn't in this current release - closing, feel free to report a new issue if you are still having problems.
