### ISSUE TITLE
Try install saml2 plugin and got this error

### ISSUE THREAD

**Issue by mbsa-devteam** [catalyst/moodle-auth_saml2#289]
**What happened?**
I just install moodle 3.5 and try to install SAML2 pluggin next.
And then got this error.

> core plugin/corrupted archive structure
https://docs.moodle.org/35/en/error/core_plugin/corrupted_archive_structure

- I use both upload zip file and install plugin from moodle library methods and still got the same error.
- I install SAML2 Single sign on plugin version 2018071100

**What you expected:**
successful in install SAML2 Single sign on plugin.

**Comment by danmarsden** [comment]
sounds like an issue with your server when using the Moodle plugin installation UI - maybe something to do with permissions or the zip library installed on your server. I expect you will have the same issue when trying to use this UI to install any plugin.

The best place to ask for help with this is in the community forums on moodle.org. Unfortunately we are not able to provide free configuration and installation support for our plugins.

Good luck!

**Comment by mbsa-devteam** [comment]
Is that so?
Thank you! I will try to fix this permission then.
