### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by ledav78** [catalyst/moodle-auth_saml2#291]
We installed the plugin version 2018071100.
Moodle is version 3.5.2 (Build: 20180910)
Server is Windows Server 2012 R2, IIS, PHP 7.5.2.
Database is SQL Server 2012

Our IdP is configured on a F5 Big-IP

When we log into the system using SAML, we never succeed to log into Moodle.
We click on the SAML authentication button and fill our credentials, then we are redirected to the login page and it starts to loop.

You can find attached a saml trace from Firefox (json file) and the log of simplesaml.
[simplesamlphp.log](https://github.com/catalyst/moodle-auth_saml2/files/2450426/simplesamlphp.log)

[SAML-tracer-export-2018-10-05T13_14_57.615Z.zip](https://github.com/catalyst/moodle-auth_saml2/files/2450439/SAML-tracer-export-2018-10-05T13_14_57.615Z.zip)

Are we missing something in the config ?

**Comment by ledav78** [comment]
After a message, on another thread, the solution was to install a newer version of redis.
So in case your in trouble with a similar setup that our, here is some info not documented:
- you need open SSL for Windows https://slproweb.com/products/Win32OpenSSL.html
- you need redis for windows https://github.com/MicrosoftArchive/redis/releases
- you need phpredis for windows https://pecl.php.net/package/redis

**Comment by danmarsden** [comment]
Thanks for following up with the solution for others that might find this via a search.
