### ISSUE TITLE
Latest Plugin (2018071100) will not install on Moodle 3.5.2 +

### ISSUE THREAD

**Issue by morphious51** [catalyst/moodle-auth_saml2#293]
I installed latest release of Moodle from the site today 3.5.2 +

I then attempted to install the SAML plugin. 

It sits on the plugin install screen, then changes to a page that says:
Install plugin from ZIP file
Validating auth_saml2 ...

I let it sit for a couple hours, checked the server to see if the saml2 directory was created under /auth but nothing. 

I have reinstalled Moodle a few times now and ten the plugin with no change. Is this version of the plugin not compatible with 3.5.2 + ? 
![plugin validation](https://user-images.githubusercontent.com/44624485/47756580-55438d00-dc68-11e8-80fe-c887ea92da51.JPG)
 
Thanks

**Comment by danmarsden** [comment]
duplicates #289 and #292 - seems the zip works fine for some people but not others..  we're hoping to update the plugins db soon with a new version, but in the meantime please try getting the code directly from github here.

**Comment by morphious51** [comment]
Where do I get the code from using git? I have tried the command from the plugin installation doc:
git clone git@github.com:CatalystIT-AU/moodle-auth_saml2.git auth/saml2

I also tried:
Git clone git@github.com:catalyst/moodle-auth_saml2.git auth/saml2
 but I get a message:
Permission denied (public key)
Fatal: could not read from the remote repository 
Please make sure you have the correct access rights and that the repository exists.

**Comment by morphious51** [comment]
Thank you for the help Dan I appreciate it! I will open a separate issue if I run into anything further.
