### ISSUE TITLE
SAML2 behind a reverse proxy

### ISSUE THREAD

**Issue by JPaulG** [catalyst/moodle-auth_saml2#298]
Hi there,

We try to set up the plugin behind a reverse proxy and we get the following error message:
_SAML2 exception: Destination in response doesn't match the current URL. Destination is "https://www.reverse-proxy.com/auth/saml2/sp/saml2-acs.php/www.reverse-proxy.com", current URL is "https://www.webserver.com/auth/saml2/sp/saml2-acs.php/www.reverse-proxy.com"._

The URL to the web server is not available directly. The URL through the reverse proxy should be used. (2 main purposes: load balancing and security)

When I look the query sent to the ADFS server, the relay state included in the parameters is wrongly defined with the web server URL:
_“RelayState: https://www.webserver.com/hslp/training/auth/saml2/test.php”_

This URL should be built using the $CFG->wwwroot from Moodle config and not from server variables. 

Did I miss something in the SAML2 configuration? or is it a bug?

Best,

JP

**Comment by JPaulG** [comment]
I identified the following fix:
/auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php
Line 797 $appurl = ($appcfg instanceof \SimpleSAML_Configuration) ? $appcfg->getString('baseurlpath', '') : ''; 
instead of $appurl = ($appcfg instanceof \SimpleSAML_Configuration) ? $appcfg->getString('baseURL', '') : '';

Line 807
                global $CFG;
                $hostname = parse_url($CFG->wwwroot, PHP_URL_HOST);
                $port = '';
Instead of 
                //$hostname = self::getServerHost();
                //$port = self::getServerPort();

Please let me know if it is good solution.

Best,
JP

**Comment by brendanheywood** [comment]
Just noting that the patch above is not ideal, we want to minimize all hacks in the external libs. The correct fix is to set the base url in the config here:

https://github.com/catalyst/moodle-auth_saml2/blob/master/config/config.php#L46-L49

If someone can put that into a pr it would be most welcome

**Comment by mbelge** [comment]
Like @brendanheywood said, the correct way to do it is to set the config in `saml2/config/config.php` like so:

```
$config = array(
    'baseurlpath'       => $wwwroot . '/auth/saml2/sp/',
    'application'       => [
      'baseURL'         => $wwwroot . '/auth/saml2/sp/', 
    ],
    'certdir'           => $saml2auth->get_saml2_directory() . '/',
[...]
```

And then the SimpleSAML lib will produce the proper URL in `saml2/extlib/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php`

**Comment by brendanheywood** [comment]
I've folder that in now, I'd appreciate some tests in varied environments and reporting back if there was any more issues
