### ISSUE TITLE
IdP override label no longer works (version 2019022100)

### ISSUE THREAD

**Issue by peterspicer-catalyst** [catalyst/moodle-auth_saml2#317]
**What happened?**

After upgrading to 2019022100, the IdP override label functionality no longer works.

I have an IdP configured which returns an institution name in its metadata, but our client instead would prefer that it used the "IdP override label" that states 'Login with {service}' rather than the name of the institution.

Even putting this in the metadata configuration, so I have it say `Login with {service} https://link/to/metadata`, still uses the IdP name as provided in the metadata.

**What you expected:**
If I put something in the IdP override label configuration, or I override the IdP name when I add its metadata, I expect this to be what is presented on the login page.

**Comment by dustinbrisebois** [comment]
In addition, the tester (for single xml) and passive mode don't work as expected either, this is most likely due to how the metadata is being handled via the database instead of via config_plugins

**Comment by dustinbrisebois** [comment]
auth.php on line 211 would fix this issue with:

`                // When multiple IdPs are configured, use a different default based on the IdP.
                if ($this->multiidp) {
                    $host = parse_url($idp->entityid, PHP_URL_HOST);
                    $idpname = get_string('idpnamedefault_varaible', 'auth_saml2', $host);
                } else if (!empty($metadata->idpname) && !is_null($metadata->idpname)) {
                    $idpname = $metadata->idpname;
                } else if (empty($idpname) || !empty($conf->idpname)) {
                    $idpname = $conf->idpname;
                } else if (!empty($idp->name)) {
                    $idpname = $idp->name;
                }
`

This does need extensive testing against what the major contributors planned as it may break some stuff - but it works for single xml payloads.

Passive mode and Testing are still broken.
