### ISSUE TITLE
Possible certificate/PHP format issue

### ISSUE THREAD

**Issue by j2s** [catalyst/moodle-auth_saml2#319]
On SAML2 settings page click 'View SP certificate',  see:
_SAML2 auto generated public certificate contents
The path for the cert is here: /xxx/yyy/sitedata/saml2/zzzzzz.crt
Notice: A non well formed numeric value encountered in .../auth/saml2/setuplib.php on line 133_
(x 2)
Visual inspection of page shows no obvious issues.
Regenerating certificate does not help.
Plugin version: 2019022100
PHP  7.2.15.0.0.18.04.2

**Comment by danmarsden** [comment]
could be the old version of the simplesaml lib not being compatible with 7.2 - I've got an untested WIP branch here with an upgraded simplesaml lib if you want to take a look - let us know if this works for you.
https://github.com/catalyst/moodle-auth_saml2/tree/issue308_simplesaml1.16

**Comment by j2s** [comment]
Add in debugging I can see:
... key=validTo val=270920120622Z, 

line 133:
`if (strpos($key, 'valid') !== false && ($val * 1) === $val) {`
The `($val * 1)` is objected to. 
If this is removed then the validTo (and validFrom) values are  rendered in the page as date strings: 'Wednesday, 12 February 10555, 1:03 PM (270920120622Z)'  - however year value is incorrect (10555).

BTW validFrom_time_t & validTo_time_t values do not have zone suffix. 

Not sure how signature should look, or values vetted, so just posting these observations

**Comment by brendanheywood** [comment]
This is fixed now in 6c4e43197d44a6a92089bd69daecc00fbaa79647
