### ISSUE TITLE
Unit test failure test_file_bitmask in totara 10

### ISSUE THREAD

**Issue by kristian-94** [catalyst/moodle-auth_saml2#323]
In a clean totara 10.19, running this test:
` vendor/bin/phpunit totara_core_totara_testcase totara/core/tests/totara_test.php`
We see the following output:

> There was 1 failure:
> 
> 1) totara_core_totara_testcase::test_file_bitmask
> auth/saml2/extlib/simplesamlphp/bin/build-release.sh is not correctly bitmasked, it is using 775
> auth/saml2/extlib/simplesamlphp/bin/check-syntax.sh is not correctly bitmasked, it is using 775
> auth/saml2/tests/idp/simplesamlphp.sh is not correctly bitmasked, it is using 775
> 
> /siteroot/totara/core/tests/totara_test.php:63
> /siteroot/lib/phpunit/classes/base_testcase.php:600
> /siteroot/lib/phpunit/classes/advanced_testcase.php:68
> 
> To re-run:
>  vendor/bin/phpunit totara_core_totara_testcase totara/core/tests/totara_test.php

Need to change file write/read/execute permissions for these three files, fixed in pull 321 https://github.com/catalyst/moodle-auth_saml2/pull/321

**Comment by danmarsden** [comment]
hmm - looks like this broke travis unit tests and we missed it... I've just reverted the patch for now - it's probably more important to have travis tests all passing..

**Comment by danmarsden** [comment]
I've just reported this to Totara - IMO they should be excluding .sh files from that test.

**Comment by kristian-94** [comment]
@danmarsden I think this issue should be opened again. Your recent commit  "Fix #323 adjust bit mask and use bash to trigger sh file in travis" fixes one of the 3 files failing, but the test is still failing overall.

**Comment by danmarsden** [comment]
@kristian-94 - travis has been failing in saml2 for a while - the remaining 7.1 master test failure is unrelated to this change. Closing this again :-) 
It could be related to Pull #325 but I suspect that  test is failing due to a deprecated behat step definition being used in the code - feel free to report that as a separate issue and take a look :-)

**Comment by danmarsden** [comment]
sorry - I think I just realised you were saying this is still failing in a totara unit test branch? - maybe I missed something there...

**Comment by danmarsden** [comment]
Ah - yeah this does relate to pull #325 I think - updating the sinplesaml lib. I've been running that branch in totara 12 and it's been ok

**Comment by danmarsden** [comment]
this should be sorted now - feel free to report a new issue if there are still issues. Thanks.
