### ISSUE TITLE
PHP 7.2 support with upgrade simplesamlphp

### ISSUE THREAD

**Issue by dvdcastro** [catalyst/moodle-auth_saml2#331]
Hello,

We're looking into using PHP 7.2 with this plugin. Please consider upgrading `simplesamlphp` which already fixes many of the present deprecations.

https://github.com/simplesamlphp/simplesamlphp

**Comment by danmarsden** [comment]
this work has been completed as part of issue #308 and Pull #325 - we are running this branch in production on one site but I was hoping to have a few more people test it before we merge into the master branch.

Please let us know if you are able to test that code and if it works for you.

When I deployed this updated code to the prod site I found the authentication stopped working until I logged in and saved the auth_saml2 settings page - I'm not clear if that fixed it or if the meta-data refresh ran during that time and fixed it. It would be good if you could confirm this. We don't really want to merge code in that might result in sites upgrading and breaking their existing authentication.

**Comment by danmarsden** [comment]
... looks like that branch needs a rebase too. I'll try to do that in the next few hours.
