### ISSUE TITLE
Unable to install via zip file

### ISSUE THREAD

**Issue by townshenda** [catalyst/moodle-auth_saml2#336]
When installing from the zip file by dragginf and dropping in Moodle 3.7 I get to the validating install page and it just hangs. I fI come out and go back in to Moodle, the plugin is not installed.
![screenshot 1](https://user-images.githubusercontent.com/52784191/61045671-2ecb1980-a3d3-11e9-8712-241c125b1782.PNG)
![screenshot 2](https://user-images.githubusercontent.com/52784191/61045675-31c60a00-a3d3-11e9-9539-c194e4ffd3b3.PNG)

**Comment by danmarsden** [comment]
this has come up before - see issue #293 - I'm inclined to believe it's either a bug with the moodle form installer or an issue with the config on your site. see issue #293 for alternative install options - if you manage to isolate the issue causing this and find that it's an issue with the zip (it works for me fine) please let us know, but I am closing this for now.

**Comment by townshenda** [comment]
Hi Dan.
No luck with this zip file either. Exactly the same error. Tried using git and got the same error as the other user (Fatal error...)

**Comment by danmarsden** [comment]
The moodle web installer requires a bunch of different things to work. Best place to ask for help with that is the community forums on moodle.org - good luck!
