### ISSUE TITLE
Cant Log in - no error message

### ISSUE THREAD

**Issue by oksim14** [catalyst/moodle-auth_saml2#339]
Hello, I have a trouble to log in.

My situation:
User in moodle exists. Authentication method is set to SAML2.

After click on log in with saml, redirect to IDP (laravel app), log in and redirect back. All seems fine, but user is not logged in and there is no error message. - its empty index moodle page with no user logged in.

Debug log:
`Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7] Session: '192.168.255.12' not valid because we are not authenticated.
Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7] Saved state: '_ddd5ce9492831d963b53d54082d7b2c518ea1dc9d6'
Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7] Sending SAML 2 AuthnRequest to 'http://192.168.255.30:8081/saml/idp/metadata'
Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7] Sending message:
Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7] <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_ddd5ce9492831d963b53d54082d7b2c518ea1dc9d6" Version="2.0" IssueInstant="2019-07-25T12:41:13Z" Destination="http://192.168.255.30:8081/login" AssertionConsumerServiceURL="http://192.168.255.12:8081/auth/saml2/sp/saml2-acs.php/192.168.255.12" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST">
Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7]   <saml:Issuer>http://192.168.255.12:8081/auth/saml2/sp/metadata.php</saml:Issuer>
Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7]   <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" AllowCreate="true"/>
Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7] </samlp:AuthnRequest>
Jul 25 14:41:13 SimpleSAMLphp DEBUG [3bedcc35d7] Redirect to 1129 byte URL: http://192.168.255.30:8081/login?SAMLRequest=jZJbTwIxEIX%2Fyqbve2mXhd0GSBBiJEElgD74Ysp2hCa77drpevn3lkUTNEp8a6bzzZxzMkMUddXwSev2egXPLaAL3upKI%2B8%2BRqS1mhuBCrkWNSB3JV9PrhecRQlvrHGmNBU5Qc4TAhGsU0aTYD4bkUcpZVZC0StYnlJZ9NNtlsqsl%2BRMDraszGgOgsqykH0S3INFT46IH%2BRxxBbmGp3QzpcSWoTJIGTZhjLeo5ymDySYeTdKC9dRe%2BcaHse0YBHt5xHLsihNeJ7kNK7MTnlFky9xU6OxrcGuwb6oEu5Wi19xv6nDhQ8vPnhnMTbHRyhKjJp986OfBMvPyC6Ulkrvzqe1PTYhv9psluHydr0h4%2BFhPu%2Fc2%2FG%2FRdXghBROHDQN49MRw%2BMB3Pjl89nSVKp8Dy6NrYX7WxuNaFdRMnzqWjnUQlUTKS0g%2BiCryrxOLQgHI%2BJsCyQeH7d%2Bv7TxBw%3D%3D&RelayState=http%3A%2F%2F192.168.255.12%3A8081%2Fauth%2Fsaml2%2Flogin.php%3Fwants%26idp%3D1f8c79b62ef88ccf134a54d7724a1170%26passive%3Doff&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=ZODmLZtihdJteF7ZWah95GzA1FN%2FfZmlze8DR6nab%2FMwQjKrIVmb%2FdecckBW%2Bp2zKN1djK3BS0yd6s0JzSV5tgjaLdrpKbhHxhFiMa43vLxjTn3CoqKfsHJBEMuYZSnrJK7mI42fqZI9Vu7AcaY7EeYQL82cB2ngoMGQe91gdoD6WF6MyAKb1etnhPmqTi0RsYhVWcNbvo5n8EJQO21WtNRtZdkLt2Zw2wN1HXxxFRWWycxxhkgKoGMcoWTh%2Fv5QXatUCsV%2BkRVk29gelvTRZkyFFBhUgM4%2BIh%2FMBN8rYe15eo7NoPJiApRhuNt7WZ5chX8Nfx5qR5bjrRGqJHd6HA%3D%3Darray (
)`

Response:

`
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] Received SAML2 Response from 'http://192.168.255.30:8081/saml/idp/metadata'.
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] Has 1 candidate keys for validation.
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] Validation with key #0 succeeded.
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] Has 1 candidate keys for validation.
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] Validation with key #0 failed without exception.
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] Filter config for http://192.168.255.30:8081/saml/idp/metadata->http://192.168.255.12:8081/auth/saml2/sp/metadata.php: array (  0 =>   sspmod_core_Auth_Process_AttributeMap::__set_state(array(     'map' =>     array (      'urn:oid:0.9.2342.19200300.100.1.1' => 'uid',      'urn:oid:0.9.2342.19200300.100.1.10' => 'manager',      'urn:oid:0.9.2342.19200300.100.1.11' => 'documentIdentifier',      'urn:oid:0.9.2342.19200300.100.1.12' => 'documentTitle',      'urn:oid:0.9.2342.19200300.100.1.13' => 'documentVersion',      'urn:oid:0.9.2342.19200300.100.1.14' => 'documentAuthor',      'urn:oid:0.9.2342.19200300.100.1.15' => 'documentLocation',      'urn:oid:0.9.2342.19200300.100.1.2' => 'textEncodedORAddress',      'urn:oid:0.9.2342.19200300.100.1.20' => 'homePhone',      'urn:oid:0.9.2342.19200300.100.1.21' => 'secretary',      'urn:oid:0.9.2342.19200300.100.1.22' => 'otherMailbox',      'urn:oid:0.9.2342.19200300.100.1.25' => 'dc',      'urn:oid:0.9.2342.19200300.100.1.26' => 'aRecord',      'urn:oid:0.9.2342.19200300.100.1.27' => 'mDRecord',      'urn:oid:0.9.2342.19200300.100.1.28' => 'mXRecord',      'urn:oid:0.9.2342.19200300.100.1.29' => 'nSRecord',      'urn:oid:0.9.2342.19200300.100.1.3' => 'mail',      'urn:oid:0.9.2342.19200300.100.1.30' => 'sOARecord',      'urn:oid:0.9.2342.19200300.100.1.31' => 'cNAMERecord',      'urn:oid:0.9.2342.19200300.100.1.37' => 'associatedDomain',      'urn:oid:0.9.2342.19200300.100.1.38' => 'associatedName',      'urn:oid:0.9.2342.19200300.100.1.39' => 'homePostalAddress',      'urn:oid:0.9.2342.19200300.100.1.4' => 'info',      'urn:oid:0.9.2342.19200300.100.1.40' => 'personalTitle',      'urn:oid:0.9.2342.19200300.100.1.41' => 'mobile',      'urn:oid:0.9.2342.19200300.100.1.42' => 'pager',      'urn:oid:0.9.2342.19200300.100.1.43' => 'co',      'urn:oid:0.9.2342.19200300.100.1.44' => 'uniqueIdentifier',      'urn:oid:0.9.2342.19200300.100.1.45' => 'organizationalStatus',      'urn:oid:0.9.2342.19200300.100.1.46' => 'janetMailbox',      'urn:oid:0.9.2342.19200300.100.1.47' => 'mailPreferenceOption',      'urn:oid:0.9.2342.19200300.100.1.48' => 'buildingName',      'urn:oid:0.9.2342.19200300.100.1.49' => 'dSAQuality',      'urn:oid:0.9.2342.19200300.100.1.5' => 'drink',      'urn:oid:0.9.2342.19200300.100.1.50' => 'singleLevelQuality',      'urn:oid:0.9.2342.19200300.100.1.51' => 'subtreeMinimumQuality',      'urn:oid:0.9.2342.19200300.100.1.52' => 'subtreeMaximumQuality',      'urn:oid:0.9.2342.19200300.100.1.53' => 'personalSignature',      'urn:oid:0.9.2342.19200300.100.1.54' => 'dITRedirect',      'urn:oid:0.9.2342.19200300.100.1.55' => 'audio',      'urn:oid:0.9.2342.19200300.100.1.56' => 'documentPublisher',      'urn:oid:0.9.2342.19200300.100.1.6' => 'roomNumber',      'urn:oid:0.9.2342.19200300.100.1.60' => 'jpegPhoto',      'urn:oid:0.9.2342.19200300.100.1.7' => 'photo',      'urn:oid:0.9.2342.19200300.100.1.8' => 'userClass',      'urn:oid:0.9.2342.19200300.100.1.9' => 'host',      'urn:oid:1.2.840.113549.1.9.1' => 'email',      'urn:oid:1.2.752.194.10.2.2' => 'sisSchoolGrade',      'urn:oid:1.2.752.194.10.2.1' => 'sisLegalGuardianFor',      'urn:oid:1.2.752.194.10.3' => 'sisOrgDepartment',      'urn:oid:1.2.752.194.10.2.4' => 'sisSchoolUnitCode',      'urn:oid:1.3.6.1.4.1.2428.90.1.1' => 'norEduOrgUniqueNumber',      'urn:oid:1.3.6.1.4.1.2428.90.1.11' => 'norEduOrgSchemaVersion',      'urn:oid:1.3.6.1.4.1.2428.90.1.12' => 'norEduOrgNIN',      'urn:oid:1.3.6.1.4.1.2428.90.1.2' => 'norEduOrgUnitUniqueNumber',      'urn:oid:1.3.6.1.4.1.2428.90.1.3' => 'norEduPersonBirthDate',      'urn:oid:1.3.6.1.4.1.2428.90.1.4' => 'norEduPersonLIN',      'urn:oid:1.3.6.1.4.1.2428.90.1.5' => 'norEduPersonNIN',      'urn:oid:1.3.6.1.4.1.2428.90.1.6' => 'norEduOrgAcronym',      'urn:oid:1.3.6.1.4.1.2428.90.1.7' => 'norEduOrgUniqueIdentifier',      'urn:oid:1.3.6.1.4.1.2428.90.1.8' => 'norEduOrgUnitUniqueIdentifier',      'urn:oid:1.3.6.1.4.1.2428.90.1.9' => 'federationFeideSchemaVersion',      'urn:oid:1.3.6.1.4.1.24552.500.1.1.1.13' => 'sshPublicKey',      'urn:oid:1.3.6.1.4.1.250.1.57' => 'labeledURI',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.1' => 'eduPersonAffiliation',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.11' => 'eduPersonAssurance',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.10' => 'eduPersonTargetedID',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.13' => 'eduPersonUniqueId',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.16' => 'eduPersonOrcid',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.2' => 'eduPersonNickname',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.3' => 'eduPersonOrgDN',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.4' => 'eduPersonOrgUnitDN',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.5' => 'eduPersonPrimaryAffiliation',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.6' => 'eduPersonPrincipalName',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.7' => 'eduPersonEntitlement',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.8' => 'eduPersonPrimaryOrgUnitDN',      'urn:oid:1.3.6.1.4.1.5923.1.1.1.9' => 'eduPersonScopedAffiliation',      'urn:oid:1.3.6.1.4.1.5923.1.2.1.2' => 'eduOrgHomePageURI',      'urn:oid:1.3.6.1.4.1.5923.1.2.1.3' => 'eduOrgIdentityAuthNPolicyURI',      'urn:oid:1.3.6.1.4.1.5923.1.2.1.4' => 'eduOrgLegalName',      'urn:oid:1.3.6.1.4.1.5923.1.2.1.5' => 'eduOrgSuperiorURI',      'urn:oid:1.3.6.1.4.1.5923.1.2.1.6' => 'eduOrgWhitePagesURI',      'urn:oid:1.3.6.1.4.1.5923.1.5.1.1' => 'isMemberOf',      'urn:oid:1.3.6.1.4.1.25178.1.2.1' => 'schacMotherTongue',      'urn:oid:1.3.6.1.4.1.25178.1.2.2' => 'schacGender',      'urn:oid:1.3.6.1.4.1.25178.1.2.3' => 'schacDateOfBirth',      'urn:oid:1.3.6.1.4.1.25178.1.2.4' => 'schacPlaceOfBirth',      'urn:oid:1.3.6.1.4.1.25178.1.2.5' => 'schacCountryOfCitizenship',      'urn:oid:1.3.6.1.4.1.25178.1.2.6' => 'schacSn1',      'urn:oid:1.3.6.1.4.1.25178.1.2.7' => 'schacSn2',      'urn:oid:1.3.6.1.4.1.25178.1.2.8' => 'schacPersonalTitle',      'urn:oid:1.3.6.1.4.1.25178.1.2.9' => 'schacHomeOrganization',      'urn:oid:1.3.6.1.4.1.25178.1.2.10' => 'schacHomeOrganizationType',      'urn:oid:1.3.6.1.4.1.25178.1.2.11' => 'schacCountryOfResidence',      'urn:oid:1.3.6.1.4.1.25178.1.2.12' => 'schacUserPresenceID',      'urn:oid:1.3.6.1.4.1.25178.1.2.13' => 'schacPersonalPosition',      'urn:oid:1.3.6.1.4.1.25178.1.2.14' => 'schacPersonalUniqueCode',      'urn:oid:1.3.6.1.4.1.25178.1.2.15' => 'schacPersonalUniqueID',      'urn:oid:1.3.6.1.4.1.25178.1.2.17' => 'schacExpiryDate',      'urn:oid:1.3.6.1.4.1.25178.1.2.18' => 'schacUserPrivateAttribute',      'urn:oid:1.3.6.1.4.1.25178.1.2.19' => 'schacUserStatus',      'urn:oid:1.3.6.1.4.1.25178.1.2.20' => 'schacProjectMembership',      'urn:oid:1.3.6.1.4.1.25178.1.2.21' => 'schacProjectSpecificRole',      'urn:oid:2.16.840.1.113730.3.1.1' => 'carLicense',      'urn:oid:2.16.840.1.113730.3.1.2' => 'departmentNumber',      'urn:oid:2.16.840.1.113730.3.1.216' => 'userPKCS12',      'urn:oid:2.16.840.1.113730.3.1.241' => 'displayName',      'urn:oid:2.16.840.1.113730.3.1.3' => 'employeeNumber',      'urn:oid:2.16.840.1.113730.3.1.39' => 'preferredLanguage',      'urn:oid:2.16.840.1.113730.3.1.4' => 'employeeType',      'urn:oid:2.16.840.1.113730.3.1.40' => 'userSMIMECertificate',      'urn:oid:2.5.4.0' => 'objectClass',      'urn:oid:2.5.4.1' => 'aliasedObjectName',      'urn:oid:2.5.4.10' => 'o',      'urn:oid:2.5.4.11' => 'ou',      'urn:oid:2.5.4.12' => 'title',      'urn:oid:2.5.4.13' => 'description',      'urn:oid:2.5.4.14' => 'searchGuide',      'urn:oid:2.5.4.15' => 'businessCategory',      'urn:oid:2.5.4.16' => 'postalAddress',      'urn:oid:2.5.4.17' => 'postalCode',      'urn:oid:2.5.4.18' => 'postOfficeBox',      'urn:oid:2.5.4.19' => 'physicalDeliveryOfficeName',      'urn:oid:2.5.4.2' => 'knowledgeInformation',      'urn:oid:2.5.4.20' => 'telephoneNumber',      'urn:oid:2.5.4.21' => 'telexNumber',      'urn:oid:2.5.4.22' => 'teletexTerminalIdentifier',      'urn:oid:2.5.4.23' => 'facsimileTelephoneNumber',      'urn:oid:2.5.4.24' => 'x121Address',      'urn:oid:2.5.4.25' => 'internationaliSDNNumber',      'urn:oid:2.5.4.26' => 'registeredAddress',      'urn:oid:2.5.4.27' => 'destinationIndicator',      'urn:oid:2.5.4.28' => 'preferredDeliveryMethod',      'urn:oid:2.5.4.29' => 'presentationAddress',      'urn:oid:2.5.4.3' => 'cn',      'urn:oid:2.5.4.30' => 'supportedApplicationContext',      'urn:oid:2.5.4.31' => 'member',      'urn:oid:2.5.4.32' => 'owner',      'urn:oid:2.5.4.33' => 'roleOccupant',      'urn:oid:2.5.4.34' => 'seeAlso',      'urn:oid:2.5.4.35' => 'userPassword',      'urn:oid:2.5.4.36' => 'userCertificate',      'urn:oid:2.5.4.37' => 'cACertificate',      'urn:oid:2.5.4.38' => 'authorityRevocationList',      'urn:oid:2.5.4.39' => 'certificateRevocationList',      'urn:oid:2.5.4.4' => 'sn',      'urn:oid:2.5.4.40' => 'crossCertificatePair',      'urn:oid:2.5.4.41' => 'name',      'urn:oid:2.5.4.42' => 'givenName',      'urn:oid:2.5.4.43' => 'initials',      'urn:oid:2.5.4.44' => 'generationQualifier',      'urn:oid:2.5.4.45' => 'x500UniqueIdentifier',      'urn:oid:2.5.4.46' => 'dnQualifier',      'urn:oid:2.5.4.47' => 'enhancedSearchGuide',      'urn:oid:2.5.4.48' => 'protocolInformation',      'urn:oid:2.5.4.49' => 'distinguishedName',      'urn:oid:2.5.4.5' => 'serialNumber',      'urn:oid:2.5.4.50' => 'uniqueMember',      'urn:oid:2.5.4.51' => 'houseIdentifier',      'urn:oid:2.5.4.52' => 'supportedAlgorithms',      'urn:oid:2.5.4.53' => 'deltaRevocationList',      'urn:oid:2.5.4.54' => 'dmdName',      'urn:oid:2.5.4.6' => 'c',      'urn:oid:2.5.4.65' => 'pseudonym',      'urn:oid:2.5.4.7' => 'l',      'urn:oid:2.5.4.8' => 'st',      'urn:oid:2.5.4.9' => 'street',    ),     'duplicate' => false,     'priority' => 50,  )),)
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] Session: doLogin("192.168.255.12")
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] Received message:
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_c92c84904a8fa8b102d280a1f9682a72e75b2f17d6" Version="2.0" IssueInstant="2019-07-25T12:42:28Z" Destination="http://192.168.255.12:8081/auth/saml2/sp/saml2-acs.php/192.168.255.12">
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]   <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">http://192.168.255.30:8081/saml/idp/metadata</saml:Issuer>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]   <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <ds:SignedInfo>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <ds:Reference URI="#_c92c84904a8fa8b102d280a1f9682a72e75b2f17d6">
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         <ds:Transforms>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]           <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]           <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         </ds:Transforms>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         <ds:DigestValue>hxgfmolzlaKI0cGtz9ZOpzXk8FQ=</ds:DigestValue>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       </ds:Reference>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     </ds:SignedInfo>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <ds:SignatureValue>t2I+4AgumiS8p+uvGlgSRqMJrVfG2mEkNvf4zBB1xsKPUcAdUXo/KZhV11TiMW3r9uDZ/UvWvKZa+dDgjlYVCS5yOYP9Jr4DVHpIgRIibAHLXa6iT77qTxmvVzQvcZS7U/YaCt/MxfiO7eB6ExUr/tFLkYSOOPqKqv5Fv9RmO9Lq7JahpjdS9o+FQICEjaHGdwjYXcqQY0oobHXeR3gLczHMN3NY5Pc6c8vwHKJd+FfO5xN3wFTR0/02Gi6r8oHBnJmWZpH44xJch+wuM+7rZxrS3NWIOXvTKUGRimlGJlFbiHZ7FKAk8DjJPi91Elal9Vy+L+5YeyssBH61OVzPWLrd5yO4nsKJb9ba/MgP+JnVX61hbZKM3XJBoNDCCCdyEYNfZfFJYWfNxR4njjZVTwfuS00NEggovHcJJb25hZLK+yfl2jYTbfMxpXx7LDyWYD+6RU/iFCsZKzj10R7uR4lk5n8RsMgjfjbJ15bL+wZFa6dV+EYYt85wvbyiuPpI</ds:SignatureValue>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <ds:KeyInfo>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <ds:X509Data>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         <ds:X509Certificate>MIIE2TCCA0GgAwIBAgIJAKtb2ZOh212LMA0GCSqGSIb3DQEBCwUAMIGCMQswCQYDVQQGEwJTSzERMA8GA1UECAwIU2xvdmFraWExEzARBgNVBAcMCkJyYXRpc2xhdmExDDAKBgNVBAoMA0NHQzENMAsGA1UECwwERmlucTEPMA0GA1UEAwwGTWRldmVsMR0wGwYJKoZIhvcNAQkBFg5nYWxsaWttQGNnYy5zazAeFw0xOTA3MTgxMjIzNTVaFw0yOTA3MTcxMjIzNTVaMIGCMQswCQYDVQQGEwJTSzERMA8GA1UECAwIU2xvdmFraWExEzARBgNVBAcMCkJyYXRpc2xhdmExDDAKBgNVBAoMA0NHQzENMAsGA1UECwwERmlucTEPMA0GA1UEAwwGTWRldmVsMR0wGwYJKoZIhvcNAQkBFg5nYWxsaWttQGNnYy5zazCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAPIL1m12Y3J1glLf+1bI77u/hpk21oYS7/H2GUX4EbTpYlpzuOC+ZBvqxwOP/4HFP2WYsbSW1sfI3VHb1CXLmG5c9ZaW1c8Sdcy3FJ8RIVYltLmn4/uu1B9SCcZNeJ99WNWsorr1vwRiGjoMeX+ZaLA6vF8fatVsRJuh5JEJE3e1FqS7Hp5Z5GVkMh/6swF4kB7rpGhOwMR9S6pZ0p4ORu0lj4ZlQ3EbiSO2P7nGjgaYxpWIgsj0YWNp9p0ttFW1PHE7FPzkigRIssbmuus7o3uFUl6nh0oiZmwvwvHPf+6RNbGBrd5BxcsNoKH+MesK38pF6ZeGrt6mYj7XAOse/lOmsnQI7Re50yUuL0ZOSCKik+LP1zYtaKS4kRWo5tk5iu25XzHbMHK8YZfuNWMtq1Tnqu9fDopKgd+ywCpDNsg8OGtPRmpenLVrj56Mdubb2CTN4jk1vYXag6VHiGkIvDeosM0/YPbwtMNvyckBz7aozqgGQzkFWbbd8e/pbbylowIDAQABo1AwTjAdBgNVHQ4EFgQUsw1Ssw7UqZFKrhMMyL56VnP88FYwHwYDVR0jBBgwFoAUsw1Ssw7UqZFKrhMMyL56VnP88FYwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAYEAlH9i61DwbuCvG5VoYPVQPmJlW6LgxXoZB3OHTYe8rTOGK0qNssWL9+plKXDnH3Ob/T24UWxzjdkWwKp8FX/s7vDUQUbnsYIWNx2EWnvGJPEi2M8ILDZjSJJOVzAaj3PfvVH0zi21ZiKMl5c8uI4fgmV0kl5HLwrVk3mHWkTDVnQfi3AlILN3ZPCNV6pZ1EhpgJiE1g99IOIAfjQa5jT9Us6+QRMnJasL+bncOPMYzYRzIcZZGJ8YGhfCRth8ITv27kYsLgGH+alHr0CH6riLMKt6mOoTCwChJ2c7rSNm5consRuGUMczr7aDEOmHRKhXZO9KhUXAf95N3oeVIXmnLpZh/9EPAS2rZbWiPkpvyZVRXFhnmiOB7FVD77iexNKwIX+RzDS7q+FNTQbHocqamvrqSq28I7iRSQRNzWpOIAvewlgsvnQZNTXhDR9OlnID5UhnC8p+zFBJRIo/s2LMOSX5I5d8vf+h57uNT0kyJ0QYmf01OrDhEvFNEojtTkVQ</ds:X509Certificate>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       </ds:X509Data>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     </ds:KeyInfo>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]   </ds:Signature>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]   <samlp:Status>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]   </samlp:Status>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]   <Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="_9dc405a6e4233b9ccb7176789bbaef6c7f6e0a2e0a" Version="2.0" IssueInstant="2019-07-25T12:42:28Z">
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <Issuer>http://192.168.255.30:8081/saml/idp/metadata</Issuer>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <Subject>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">riaditel@misko.sk</NameID>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         <SubjectConfirmationData InResponseTo="_ddd5ce9492831d963b53d54082d7b2c518ea1dc9d6" NotOnOrAfter="2019-07-25T12:43:28Z" Recipient="http://192.168.255.12:8081/auth/saml2/sp/saml2-acs.php/192.168.255.12"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       </SubjectConfirmation>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     </Subject>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <Conditions NotBefore="2019-07-25T12:42:28Z" NotOnOrAfter="2019-07-25T12:43:28Z">
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <AudienceRestriction>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         <Audience>http://192.168.255.12:8081/auth/saml2/sp/metadata.php</Audience>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       </AudienceRestriction>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     </Conditions>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <AttributeStatement>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         <AttributeValue>riaditel@misko.sk</AttributeValue>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       </Attribute>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <Attribute Name="http://schemas.xmlsoap.org/claims/CommonName"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <Attribute Name="http://schemas.microsoft.com/ws/2008/06/identity/claims/role"/>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     </AttributeStatement>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     <AuthnStatement AuthnInstant="2019-07-25T12:32:28Z" SessionIndex="_some_session_index">
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       <AuthnContext>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]         <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]       </AuthnContext>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]     </AuthnStatement>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7]   </Assertion>
Jul 25 14:42:28 SimpleSAMLphp DEBUG [3bedcc35d7] </samlp:Response>
`

But what is funny, I can see 2 cookies in browser after redirect back from idp:

MDL_SSP_AuthToken - _a8313bc06d3efe538d0f07338df8779fbded316b31
MDL_SSP_SessID - 1c2bd3047a824233fa146c1a47010b4d

So, it all looks fine, but moodle just wont log me in. Can you help please?

**Comment by danmarsden** [comment]
Hi there,

unfortunately we don't have the resources to provide free Moodle support for configuring and installing all our plugins. If you are looking for commercial level support feel free to get in touch via the contacts page on our website, alternatively you could ask for help in the community forums on moodle.org - the authentication forum here would be a good start: https://moodle.org/mod/forum/view.php?id=42
