### ISSUE TITLE
SAML2 exception: ACSPARAMS in Php72 and Moodle3.7

### ISSUE THREAD

**Issue by cvnniranjanreddy** [catalyst/moodle-auth_saml2#353]
I am using Moodle3.7 and Installed the Saml2 plugin (Branch: PHP72Support), Configurtation and everything is fine. 

When I test the Integration with below URL, then I am getting **SAML2 exception: ACSPARAMS** 

URL: https://lmsdomain.com/auth/saml2/sp/saml2-acs.php/lmsdomain.com.

Below is the simplesamlphp log information

Sep 18 20:30:27 SimpleSAMLphp ERROR [TR94c92c41] Error creating session: Headers already sent.
Sep 18 20:30:27 SimpleSAMLphp WARNING [TR94c92c41] Unable to find the SAML 2 binding used for this request.array (
)
Sep 18 20:30:27 SimpleSAMLphp WARNING [TR94c92c41] Request method: 'GET'array (
)
Sep 18 20:30:27 SimpleSAMLphp WARNING [TR94c92c41] Content-Type: ''array (
)

Can you please help in understanding where the issue is and how we can fix it. 

Regards,
Niranjan

**Comment by danmarsden** [comment]
Hi Niranjan,

The php 7.2 support branch has now landed in the master branch, and this sounds like it might be a configuration issue - unforunately we are not in a position to provide free support for setting up the plugin, you could try asking for help in the moodle community forums, or alternatively if you would like commercial support to help set it up feel free to contact us privately for a quote (see our contact details in the readme file here.)

If after further investigation you discover this relates to a bug in the plugin feel free to create a new issue with more specific information so we can take a look.

good luck!
