### ISSUE TITLE
version.php: required minimum Moodle version seems to be wrong

### ISSUE THREAD

**Issue by danowar2k** [catalyst/moodle-auth_saml2#357]
**What happened?**

After installing auth_saml2 (2019022100) to a Moodle 3.2.x instance multiple problems surface.
This leads me to suspect that the required Moodle version for this plugin should be changed.
The official requirement at the moment is still 2014051200 (2.7).

Errors that cam up until now include:

* When the IDP provides an icon, the variable $idp['icon'] is set to a string. Moodle 3.2.x expects an instance of pix_icon there. See also here: https://github.com/catalyst/moodle-auth_saml2/issues/79#issuecomment-533528311
* I then tried to login via the dedicated login page /login/index.php and got this error:

```
Fehler: Call to a member function export_for_template() on string

Weitere Informationen über diesen Fehler

×Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 130 of /auth/classes/output/login.php: Error thrown
line ? of unknownfile: call to core_auth\output\login->core_auth\output\{closure}()
line 135 of /auth/classes/output/login.php: call to array_map()
line 4363 of /lib/outputrenderers.php: call to core_auth\output\login->export_for_template()
line 205 of /lib/outputrenderers.php: call to core_renderer->render_login()
line 365 of /login/index.php: call to renderer_base->render()
```

**What you expected:**

Well, I expected to be able to use the plugin, to be able to access the frontpage without errors and the dedicated login page, too. Let's see where errors appear next when I add quick fixes.

**Comment by danowar2k** [comment]
The second error seems to be because of the same thing. Moodle 3.2.x core code excerpt:

/auth/classes/output/login.php:
 ```
       $identityproviders = array_map(function($idp) use ($output) {
            $idp['icon'] = $idp['icon']->export_for_template($output);
            if ($idp['url'] instanceof moodle_url) {
                $idp['url'] = $idp['url']->out(false);
            }
            return $idp;
        }, $this->identityproviders);

```

**Comment by danowar2k** [comment]
Found the line in Moodle's /lib/upgrade.txt where the change is documented:

https://github.com/moodle/moodle/blob/6735197cc2ec37f42da45a37abad41af835a2c82/lib/upgrade.txt#L389-L396

**Comment by danmarsden** [comment]
yeah - we'll be bumping that requires when the php7.2 branch merges anyway - thanks for the report.

**Comment by danmarsden** [comment]
In fact - we had already done this, so I suspect you were using an older version of the code.
see: commit: 4e89c4111c128e65e53ca76c58d68102e8360135#diff-5bbd3ccd25214f9956eea7e9f714bc08

We do have some slight challenges setting the requires version because the master code supports t12 and higher which uses Moodle 3.3 as a base, but we also have a requirement of using PHP 7. Theoretically we should only support 3.4 and higher in the master branch because Moodle 3.3 supports PHP 5.6 and the master branch doesn't, but I'm not quite sure we need to bother implementing an "if totara require X" if Moodle require version X to manage this right now. Especially since php 5 is now out of support and Moodle 3.3 is also out of support.

We may need to change this at some point - and use different requires versions depending on if the site is a moodle or totara, but not yet.

Thanks!

**Comment by danowar2k** [comment]
Well, up above I said I used version 2019022100. That is the last release of auth_saml2 in this repository. We only use releases and not "master builds". So sure, that commit is newer but hasn't been in a release yet.

Sorry, but I don't know the terminology that much so I don't know what you're referring to with "t12". Is that Totara 1.2?

Does Totara have something by which it indicates it is "Totara" and not "Moodle"? If it does, you could use that indicator and just do an "if" in the version.php...

**Comment by danmarsden** [comment]
yes - the latest code is always in the github repository here. we do not always publish new versions to the moodle.org plugins db.

We'll try to look at updating the moodle.org plugins db version at some point in future, but in the meantime you can get the latest code by using the download button here in the github repo.

**Comment by danowar2k** [comment]
But is it necessary to update the Moodle.org plugin repository? You could always release a new version on github and not propagate that to Moodle.org....Or is that forbidden?

**Comment by danmarsden** [comment]
We can't keep everyone happy :-)

We don't rely on the releases here in github ourselves - and there aren't that many moodle plugin devs that publish github "releases" - so you probably shouldn't depend on that happening.

If you want the latest code, it's available in the master branch which should be considered "stable" for all Moodle versions 3.5 and higher. If you want code for an unsupported Moodle release then you should be using the 27_34STABLE branch which we mainly keep up to date for Totara support as it is based on an older version of Moodle, but I don't see us spending any time creating builds for unsupported Moodle releases either in the plugins db, or regularly as github builds here.

thanks for the feedback anyway - we'll keep it in mind.

**Comment by danowar2k** [comment]
I see. I didn't know that
> there aren't that many moodle plugin devs that publish github "releases"
. That makes more sense, then.

Thanks for the info, though!

I think we'll just try to use the commits in master where you upgrade the version.php ;-) and indicate that in our repository with comments or something...
