### ISSUE TITLE
Login Redirect after authentication

### ISSUE THREAD

**Issue by Mutisy4** [catalyst/moodle-auth_saml2#359]
Hello,

I would like  to know if its possible to redirect a user after the SSO authentication is successful to a different page. I have created a different dashboard where i am displaying all my courses. I would like to redirect authenticated users there.

Any assistance will be appreciated

**Comment by brendanheywood** [comment]
I would generally call this an anti-feature, if you want to link to somewhere in particular then just link to it. All authentication plugins take great pains to authenticate and then continue back to where they should have gone. So fix this on whatever page they are linking in from instead
