### ISSUE TITLE
Broken idp match after upgrading to 2019022100

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-auth_saml2#362]
When upgrading to v2019022100 where a new way of managing multiple was introduced. We hit an issue where the code treats metadataurl differently. So the plugin can't match existing idps from DB to existing files saved on  the disk, because it can't find them by md5 hash of IDP URL.

**Comment by dmitriim** [comment]
If you have already upgraded then, you have to resave plugin settings and purge the site caches (just in case).

**Comment by danmarsden** [comment]
Took me a bit to realise that it was the "validate" function that was doing the save of the xml meta data but looks good to me thanks for tracking that one down!

**Comment by dmitriim** [comment]
yeah! :)
