### ISSUE TITLE
Login fails the first time, successful the second time

### ISSUE THREAD

**Issue by josemariabolanos** [catalyst/moodle-auth_saml2#366]
Login and auth are working for the app, but we are experiencing a strange login issue that is well documented on their forums
Currently users will have to login though okta, which fails once, but then when brought to the login page, using the 'Okta Button' login flow will allow for successful auth and JIT account creation
We updated the plugin to version 2019100400 (from the master branch) but the issue remains.

**Comment by KineoMichaelT** [comment]
Follow up here:  This is a duplicate issue of [338](https://github.com/catalyst/moodle-auth_saml2/issues/338).  We arrived at the exact same solution independently.  This issue can be closed, but davosmith's proposed fix should be added.
