### ISSUE TITLE
Exception - Call to a member function item() on bool

### ISSUE THREAD

**Issue by ertborTek** [catalyst/moodle-auth_saml2#368]
When member function `processRefNode()` of class `XMLSecurityDSig` (xmlseclibs) validates a SAML assertion response, the assumed attribute name for the response identifier is `ID`.  However, evaluating `XPath::filterAttrName($idKey)` against an element in `$this->idKeys` does not return a value, resulting in the XPath expression `... @= ...`, which is invalid.  The member function `filterAttrName` uses an invalid regular expression to filter `$idkey`, returning an empty value.  The expression (`/\w\d\s-_:\./`) used to filter the value contains an invalid range `\s-_`, which was once allowable with earlier versions of PHP (i.e., earlier than 7.3).

Here is a stack trace you might see running PHP 7.3 and Moodle 3.7.
```
	Error code: generalexceptionmessage
	* line 501 of /auth/saml2/extlib/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php: Error thrown
	* line 591 of /auth/saml2/extlib/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php: call to RobRichards\\XMLSecLibs\\XMLSecurityDSig->processRefNode()
	* line 65 of  /auth/saml2/extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php: call to RobRichards\\XMLSecLibs\\XMLSecurityDSig->validateReference()
	* line 624 of /auth/saml2/extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Assertion.php: call to SAML2\\Utils::validateElement()
	* line 300 of /auth/saml2/extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Assertion.php: call to SAML2\\Assertion->parseSignature()
	* line 38 of  /auth/saml2/extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Response.php: call to SAML2\\Assertion->__construct()
	* line 578 of /auth/saml2/extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Message.php: call to SAML2\\Response->__construct()
	* line 76 of  /auth/saml2/extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php: call to SAML2\\Message::fromXML()
	* line 31 of  /auth/saml2/extlib/simplesamlphp/modules/saml/www/sp/saml2-acs.php: call to SAML2\\HTTPPost->receive()
	* line 32 of  /auth/saml2/sp/saml2-acs.php: call to require()
```

In `auth/saml2/extlib/simplesamlphp/vendor/robrichards/xmlseclibs/src/Utils/XPath.php`, if you modify the regular expression defined by the constant `EXTENDED_ALPHANUMERIC` with an escaped dash (`-`), i.e., change

	const EXTENDED_ALPHANUMERIC = '\w\d\s-_:\.';
	
to

	const EXTENDED_ALPHANUMERIC = '\w\d\s\-_:\.';

the generated XPath expression will be valid.  This fix is already in the the xmlseclibs library so bringing that up to date should resolve the issue.

**Comment by danmarsden** [comment]
xmlseclibs now 3.0.4 in master and 27_34Stable branch - thanks for the report!
