### ISSUE TITLE
upcoming security release for simplesamlphp

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-auth_saml2#369]
https://groups.google.com/forum/#!topic/simplesamlphp-announce/2odMqz63z7k

we'll need to update our versions pretty quick too.

**Comment by jtsafran** [comment]
@danmarsden I was just coming here to report this.  Glad you all are on top of it!

If you need any help testing, please let me know.  I have a few dev/test sites that are configured against ADFS, Okta, and WSO2 (Ellucian Ethos Identity rebranded) that we can test against.  

Thank you for the awesome plugin and being on top of this coming SSPHP bug!

**Comment by danmarsden** [comment]
Feel free to grab that existing branch and give any feedback on testing/ any errors you see - we are seeing some php lint issues with the symfony framework but I've got it running on one site so far.

Also need to work out why those behat failures are occuring....

**Comment by danmarsden** [comment]
latest simplesaml-1.17.6-v4 branch is now passing tests - we need to test this updated branch in a few more sites before we merge into master - let us know if you get a chance to do this!

All going well, we'll then apply the security patch on top when it is released.

**Comment by Richardvi** [comment]
Thanks for picking this up, was a bit worried...

**Comment by jtsafran** [comment]
@danmarsden Downloading and installing it, now.  Will have a follow up in a few hours!

**Comment by danmarsden** [comment]
simplesaml-1.17.7 branch here in github includes the latest branch (based on master) with the upgrade to 17.7 that includes the security fix.

I haven't had a chance to test this and I'm out of the office this morning, but someone else in the team might test and merge it in.

**Comment by jtsafran** [comment]
Dan,

1.17.6 tests went well.  No issues that I am seeing as far as functionality.  The only thing that looked off is the SSPHP version was showing as "master" in the plugin.  Isn't the master branch of SSPHP the 18 RC?

I'll pull down and test functionality of the 1.17.7 version shortly.

-Jesse

**Comment by danmarsden** [comment]
1.17.7 now merged into Master (Moodle 3.5 and higher, Totara 12 and higher) - this has been rolled out to a few sites and no adverse issues seen so far.

new patch in testing for the older Totara branches in the 27_34-xmlsec branch - not tested very widely yet.

**Comment by danmarsden** [comment]
27_34 branch now merged in as well - tested ok in a few sites, and minor change to this branch, just updating the xmlseclib - will be interesting to see the full details when the embargo is over!
