### ISSUE TITLE
Typos lead to failed request

### ISSUE THREAD

**Issue by danowar2k** [catalyst/moodle-auth_saml2#385]
**What happened?**

Server response:
The requested URL /auth/saml2/avilableidps.php was not found on this server.

Reason: Typos in the source code, see:
https://github.com/catalyst/moodle-auth_saml2/search?q=avilableidps&unscoped_q=avilableidps

**Comment by brendanheywood** [comment]
What are the reproduction steps for this?

**Comment by brendanheywood** [comment]
Fixed
