### ISSUE TITLE
SAML2 auto-logon?

### ISSUE THREAD

**Issue by linkkoh** [catalyst/moodle-auth_saml2#386]
How do I go about setting it up so that it automatically logs in when the person goes to the site, I tried the passive but I get an error

**Comment by brendanheywood** [comment]
isPassive is the opposite of what you want, all you want is the 'forced login' at the saml level which removes the normal moodle login page, and you probably also want to set 'forcelogin' at the site level /admin/settings.php?section=sitepolicies
