### ISSUE TITLE
Failure Signing Data

### ISSUE THREAD

**Issue by ghigini** [catalyst/moodle-auth_saml2#387]
Hi everyone

**What happened?**
I have configured your plugin on a clean moodle 3.5.9. I have configured your plugin with the xml provided by the ADFS admin. Then i have sent to the ADFS admin the the xml generated by your plugin. Then, when i test the authentication method i get the following errors:

Exception - Failure Signing Data: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt - SHA256

Exception - Failure Signing Data: error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib - SHA256

Exception - Failure Signing Data: error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error - SHA256

They happen at random and the latter is the most common one.

My server has all the enviroment check passed except the https 

To make the authentication work i have turned off the following setting: cookiesecure.
I don't have a certificate for than site, so i can use only the http protocol for now

Please provide as many of the following as applies:
* stacktrace of the error

line 197 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Source.php: SimpleSAML\Error\UnserializableException thrown
line 165 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML\Auth\Source->initLogin()
line 108 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML\Auth\Simple->login()
line 72 of /auth/saml2/test.php: call to SimpleSAML\Auth\Simple->requireAuth()

(this stacktrace is common for all the errors)

* screen shots

* a dump of the error log with both moodle debugging on full and saml debugging on as well
The saml debugging file is empty and there are no other messages available

**What you expected:**
I expect the authentication to work

Regards,
Federico

**Comment by ghigini** [comment]
I have resolved the issue. The problem was the autogenerated certificate.
Following the simplesamlphp configuration guide i have generated a new certificate.
I have used the following command
`openssl req -newkey rsa:3072 -new -x509 -days 3652 -nodes -out saml.crt -keyout saml.pem`

Then i have replaced the old certificate with the new one in the <moodledata>/saml folder.

**Comment by nadavkav** [comment]
I experienced the same issue with Moodle 3.9.2 and auth_saml2 2020110500
