### ISSUE TITLE
Unable to login again via unsolicited SSO after logging out

### ISSUE THREAD

**Issue by davosmith** [catalyst/moodle-auth_saml2#389]
This may be related to the particular configuration for one of our customers, but I'm seeing an issue with SimpleSAML\Session instances not registering with core_shutdown_manager when they are retrieved from memcache.

A few more details:

* When a new SAML session object is created, it registers with the Moodle shutdown handler (inside the __construct() function), to make sure the data is saved at the end of the request
* When an existing SAML session is retrieved from memcache (because there is already a cookie with a reference to this session) the function to register with the Moodle shutdown handler is not called
* This means that although the authentication passes and the relevant data is added to the SAML session object, that SAML session object is not saved back into memcache.
* When the page redirects to complete the login, the SAML session object is loaded from memcache, without the details that indicate the authentication has passed (because they were not saved).

This means the authentication fails and drops the user back to the login page.

I believe the solution is to copy the call to \core_shutdown_manager::register_function() from the __construct() function of SimpleSAML\Session to the unserialize() function of the same class (I'm not sure if there is anything else that also needs transferring between those functions).

**Comment by brendanheywood** [comment]
To clarify, when you say memcache you mean the moodle session handler is memcache? The saml session is in a custom store which is inside the moodle database by default but there is also support for redis. Can you reproduce this with any moodle session handler (eg the default db one?) or only memcache?

**Comment by davosmith** [comment]
I've not been able to directly reproduce the problem other than on the customer's site.

They have some custom settings in auth/saml2/config/config.php, to set:
$config['store.type'] = 'memcache';
$config['memcache_store.servers'] = [[['hostname' => 'IP ADDRESS NOT SHOWN HERE']]];

However, the heart of the problem still seems to be that when SimpleSAML\Session is unserialized, rather than created via new, the shutdown handler is not registered, so the session is not saved.

**Comment by brendanheywood** [comment]
You should never manually touch the config/config.php file, all config is managed in code and in admin settings, the whole design of this plugin was around never having to be exposed to the simplesamlphp config directly:

https://github.com/catalyst/moodle-auth_saml2#why-is-it-better

Note that the SSP code has been touched to work with moodle shutdown 

https://github.com/catalyst/moodle-auth_saml2/blob/master/extlib/simplesamlphp/lib/SimpleSAML/Session.php#L153-L159

For the record I really dislike the way SSP relies on shutdown handlers for normal code execution, it makes it very easy to have race conditions.

Beyond this I can't help, this isn't a bug in this plugins code. If they really want to use memcache then I'd suggest they make a new 'moodle memcache store' like the redis one. But we've long ditched memcache across the board, redis is better as a store, memcache is designed to be a cache not a store.

**Comment by davosmith** [comment]
Thanks for the feedback - fully understand your position on this.

The solution I outlined is working for the customer at the moment, so I won't change it, but will bear in mind your advice for future improvements.

**Comment by brendanheywood** [comment]
If you can reproduce the issue with the default db store and / or can provide a pull request I'm happy to reopen this
