### ISSUE TITLE
Configure auth saml2 help. (PFX cert)

### ISSUE THREAD

**Issue by msomoza-vsf** [catalyst/moodle-auth_saml2#391]
Hi all,

Hope this is the right place for asking for some help and thanks in advance.

I have an ADFS server using SAML2 for login with some C# websites. The SAMLResponse is encrypted with a pfx certify.

What i expect is login directly from one of this sites already logged in to Moodle using this plugin. It´s doable?
I already configured the relaying party for the moodle site, created the pfx certify and created also a Claim with the sAMAccountName.

In the plugin i have set:

- IdP metadata xml OR public xml URL : https://XXXXXXXXX/FederationMetadata/2007-06/FederationMetadata.xml 
- Mapping IdP : sAMAccountName
- Mapping Moodle : Username

What do i need to make this work?

Thank you for the support && congrats for this amazing tool you made.

Best regards,

Manuel

**Comment by brendanheywood** [comment]
Yes this should be possible, please have a read of this:

https://github.com/catalyst/moodle-auth_saml2#debugging

**Comment by msomoza-vsf** [comment]
Hi Brendan,
I feel like im really close from login in...

I´m doing some tests trying to connect from auth/saml2/test.php and clicking int the login button with the user already signed in in the ADFS system, the site is redirecting me to my ADFS site ( https://adfs.*******/adfs/ls/?SAMLRequest=********** ) with an error ... 

I have enabled and disabled the debug options in the settings page but im still not able to find the path of any useful log file in my moodle server. ( simplesamlphp.log is always empty).

Can you give me some advice?

Thank you!

**Comment by brendanheywood** [comment]
If you turn on full logging this turns up in the web server error log. You can also divert this to a log file in the saml settings. I can't help without seeing the exact error
