### ISSUE TITLE
Some Help Configuring SAML in G Suite

### ISSUE THREAD

**Issue by Sarony11** [catalyst/moodle-auth_saml2#406]
**What happened?**

I am with a bit of shame for asking this but I have not seen clear documentation for configuring this plugin with Google Suite. I have done my best, but I am unable to make it work so I would like to ask for some help.

I have already configured several services (Jira, Confluence, etc) using SAML in Google Site, but always following good documentation and probably I am lacking some terminology or deep knowledge in how SAML is working.

I would thanks a lot some steps to follow or what configuration do I need to use on any side.

Hint: I am for sure that ACS URL, Entity ID and/or Start URL from G Suite are wrong. :P

G Suite Configuration
![imagen](https://user-images.githubusercontent.com/42748053/77421143-955e5f00-6dcb-11ea-8ab2-c51ec5e5e28b.png)
![imagen](https://user-images.githubusercontent.com/42748053/77421168-a1e2b780-6dcb-11ea-9b9e-a51bd8f62fb5.png)

Moodle Plugin Configuration
* XML Google App pasted
* Select IdP Available
* Mapping configuration

**What you expected:**

**Comment by brendanheywood** [comment]
You were not too far off it I think. On my dev box the metadata url is:

http://moodle.local/auth/saml2/sp/metadata.php

Open your equivalent and look at the xml. The first few lines are:
```
<md:EntityDescriptor entityID="http://moodle.local/auth/saml2/sp/metadata.php" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
```

so the entity id is http://moodle.local/auth/saml2/sp/metadata.php

and further down is

```
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://moodle.local/auth/saml2/sp/saml2-acs.php/moodle.local" index="0"/>
```

The 'ACS' url is this:

http://moodle.local/auth/saml2/sp/saml2-acs.php/moodle.local

The start url usually doesn't matter, but it should be your / home page not the manual moodle login page.

**Comment by Sarony11** [comment]
Thanks @brendanheywood for your fast response :)

I am still having problems

So if do not bother you, I am going to be a little more extense this time.

# My Google Config #

ACS URL:  http://mymoodle.local/auth/saml2/sp/saml2-acs.php/mymoodle.local #from Moodle SP Metada
Entity ID: https://mymoodle.local/auth/saml2/sp/metadata.php #from Moodle SP Metada
Start URL: http://mymoodle.local/my/ #It is the URL after login

NameID: Basic Information - Primary Email #becuase I want the accounts created based on email
NameID Format: Unspecified # I do not really know what to put here, if Unspecified, Email, Entity or what could be, so help here.

# My Moodle Plugin Config # 
Here I pasted the XML from Google SAML
![imagen](https://user-images.githubusercontent.com/42748053/77528454-488f8c80-6e8e-11ea-907b-edc1137f3c77.png)

I click on and activate the IdP in **Select the Available IdPs**
![imagen](https://user-images.githubusercontent.com/42748053/77528765-c3f13e00-6e8e-11ea-97ce-715d2da2b6f0.png)

![imagen](https://user-images.githubusercontent.com/42748053/77528671-a6bc6f80-6e8e-11ea-99e6-e9935fdd373c.png)

With this, I guest I allow to access using the local users (my Admin user) and also log in with my IdP configured, but even with this option, in the Moodle login screen does not appear any other way apart from the local one. You may check it here (https://http://34.244.240.106)
![imagen](https://user-images.githubusercontent.com/42748053/77552175-7cc97400-6eb3-11ea-8239-589e2578ff0c.png)

I do not know if this is right.
![imagen](https://user-images.githubusercontent.com/42748053/77552734-332d5900-6eb4-11ea-912a-e5e6c6c5ac0b.png)

I do not know if this is right.
![imagen](https://user-images.githubusercontent.com/42748053/77552354-b7331100-6eb3-11ea-8749-c8aaef6d229b.png)

And finally my mapping configuration
![imagen](https://user-images.githubusercontent.com/42748053/77552433-d2058580-6eb3-11ea-8e5b-851edb75ab5b.png)
![imagen](https://user-images.githubusercontent.com/42748053/77552454-da5dc080-6eb3-11ea-8451-67cd2114aa9b.png)
![imagen](https://user-images.githubusercontent.com/42748053/77552490-e34e9200-6eb3-11ea-9444-e09d216f75ff.png)

The rest I think is in default.

Thanks, thanks and many thanks for your help.

**Comment by brendanheywood** [comment]
Sorry this fell through the cracks and I hope you sorted it either way. It isn't clear from the above what your actual symptoms / problem was? Most of the settings mentioned are business level decisions are should not affect whether saml is working or not, just how moodle behaves and the saml assertion is received. I'll close this but if you had a specific question please ask away
