### ISSUE TITLE
Honor the $CFG->allowemailaddresses setting

### ISSUE THREAD

**Issue by porcospino** [catalyst/moodle-auth_saml2#412]
Hello

We have an IdP that authenticates users from multiple domains.  I have a requirement that users who are in a particular domain (let's say example.edu) should have Moodle accounts automatically created, but users whose accounts belong to any other domain should not.

But we still want to allow some users who are not part of example.edu to log in to Moodle.  We would do this by creating a Moodle account for them.

There is related logic here

https://github.com/catalyst/moodle-auth_saml2/blob/7241eaa54e9078df4ef1b475e5b7a19e55b2bfaa/auth.php#L586

Would you be interested in a PR that allows us to set "allowed domains" for automatic provisioning, but does not block users who already have a Moodle account from logging in?

**Comment by danmarsden** [comment]
Isn't this already possible using the allowemailaddresses core setting?

**Comment by brendanheywood** [comment]
thanks @porcospino
