### ISSUE TITLE
Behat hook gives error on any Behat failure on Windows systems

### ISSUE THREAD

**Issue by sammarshallou** [catalyst/moodle-auth_saml2#416]
On a Windows system, when you run Behat and any Behat scenario fails (not related to auth_saml2), if you have auth_saml2 installed, there is a spurious 'Failed hooks' error caused by auth_saml2 - even if the plugin isn't being tested and isn't even enabled.

It is caused by this function which attempts to take a screenshot and save it into /tmp:

https://github.com/catalyst/moodle-auth_saml2/blob/master/tests/behat/behat_auth_saml2.php#L47

I am not sure it should really be doing that as part of this plugin, since it seems to run for all Behat tests systemwide. Might be better to remove that function?

The actual error is:

--- Failed hooks:

    AfterStep # behat_auth_saml2::take_screenshot_after_failure()
      Warning: file_put_contents(/tmp/behat_screenshots.base64): failed to open stream: No such file or directory in C:\Users\(my user account)\workspace\ou-moodle2\auth\saml2\tests\behat\behat_auth_saml2.php line 56

**Comment by timhunt** [comment]
$CFG->behat_faildump_path FTW. An individual plugin definitely should not be hacking this.

**Comment by sammarshallou** [comment]
Thanks Dan for merging this, the issue should now be fixed.
