### ISSUE TITLE
When support name is empty it fails to generate sp metadata and gives unhelpful error

### ISSUE THREAD

**Issue by alexmorrisnz** [catalyst/moodle-auth_saml2#429]
**What happened?**
I found this on a client site where the support contact name was empty, auth_saml2 will give this error when visiting /auth/saml2/sp/metadata.php
`Exception - "givenName" must be a string and cannot be empty.
Stack trace:
    line 155 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Utils/Config/Metadata.php: InvalidArgumentException thrown
    line 217 of /auth/saml2/locallib.php: call to SimpleSAML\Utils\Config\Metadata::getContact()
    line 45 of /auth/saml2/sp/metadata.php: call to auth_saml2_get_sp_metadata()`

**What you expected:**
Perhaps a more helpful error message if possible?
Or in the config.php where it falls back to noreplyaddress for the technical contact if something similar can be done for the name

**Comment by bmauser** [comment]
I lost some time with this.. a more helpful error message would be nice. Support contact data should be set in admin/settings.php?section=supportcontact

**Comment by brendanheywood** [comment]
I've fixed this so it simply always works with some default text
