### ISSUE TITLE
Single Logout doesn't work

### ISSUE THREAD

**Issue by codeyourdream** [catalyst/moodle-auth_saml2#430]
We're using this plugin with Drupal. On Drupal end there's DrupalAuth for SimpleSAMLphp module.
During IdP-initiated SAML Single Logout the problem is that when Moodle receives the request from the IdP (Drupal) it doesn't log out the user, the cookies are not getting updated.

We checked that Drupal sends the request to Single Logout Service and found that SimpleSAMLphp on Moodle end writes into the logs that the session is getting logged out (so the request seems to be correct) and changes something in its data, but Moodle session remains unchanged.

**Comment by e-med** [comment]
Did you ever get any response or resolution for this? We are having the same issue.

**Comment by codeyourdream** [comment]
No response, no solution 🤷‍♂️

**Comment by brendanheywood** [comment]
Front channel SLO is now fully implemented, many thanks to @e-med for sponsoring this and helping with debugging and testing :)
