### ISSUE TITLE
Need tag for version 2019110701 

### ISSUE THREAD

**Issue by ahelton-ips** [catalyst/moodle-auth_saml2#434]
Downloaded version 2019110701 from Moodle plugin directory for plugin. However, we are adjusting our project to manage plugins via composer, and want to point to the source code. 

Is there a tag for the version I am missing? 

Thank you!

**Comment by danmarsden** [comment]
Hi there, like the majority of other moodle plugins, we use git branches rather than tags or releases.

Please see the readme for our supported branches.

Thanks!
