### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by olemde** [catalyst/moodle-auth_saml2#438]
timezone data are not synched

We are using your saml2 plugin. Until now it worked perfectly. There was no need for timezone data in the moodles user profil. Now it is and we realised that the timezone data from our IdP is not used to update users profil.
Is the plugin not able to do this?
Do we have to provide the timezone in a special format?

I am not an IT expert but moodle user, so i can only handover your information to my IT colleagues. Anyhow i thank you already for an answer.
br
Ole

**Comment by brendanheywood** [comment]
hi @olemde 

This would be a nice feature. This is actually part of core, and the mapping between the auth plugin and the user fields would be shared across all the different auth plugins. So this should be in the moodle tracker not here. I've just made a tracker for you, I'd suggest you watch that and vote for it:

https://tracker.moodle.org/browse/MDL-69341

If you would like to sponsor that improvement please contact us and link to this issue / tracker:

https://www.catalyst-au.net/contact-us
