### ISSUE TITLE
Can SAML be used to provide OAuth tokens to services such as OneDrive

### ISSUE THREAD

**Issue by scotthardwick** [catalyst/moodle-auth_saml2#447]
Hopefully easy question that someone here might have some input on.  I had looked at using the Moodle OAuth way of connecting our Microsoft azure AD accounts, but this plugin does it better and cleaner in the way that we really want.

However, the Moodle OneDrive repository (https://docs.moodle.org/39/en/OneDrive_repository) seems to hinge upon the Oauth connector (https://docs.moodle.org/39/en/OAuth_2_Microsoft_service).

Any ideas on how to get OneDrive as a repository AND use Auth_SAML2?

Thanks for any suggestions!

**Comment by brendanheywood** [comment]
Not sure, to my knowledge if you want to use the various office integrations they all hinge heavily on oauth tokens. I'm sure its possible but likely not out of the box

**Comment by brendanheywood** [comment]
Some light reading:

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-saml-bearer-assertion

**Comment by iamCristYe** [comment]
https://github.com/cirrusidentity/simplesamlphp-module-authoauth2 Maybe helpful?
