### ISSUE TITLE
Help with Moodle config

### ISSUE THREAD

**Issue by taselian** [catalyst/moodle-auth_saml2#448]
**What happened?**

Moodle 3.8+ with Master Branch SAML2 plugin

I am unsure of what to add to the config file, as detailed in your directions. What do I put between the apostrophes in the additional code needed for configuration? I feel like an  idiot for asking. I just don't know what more to do to get this to work. I followed the directions at https://docs.moodle.org/39/en/Redis_cache_store and set up  the store. 

![lfi2 config](https://user-images.githubusercontent.com/69809248/90416528-6fca3e80-e067-11ea-9c27-0b7def84316a.png)

The cache exists in the system but I still get an error. 
![error-lfi2](https://user-images.githubusercontent.com/69809248/90416853-dcddd400-e067-11ea-8a63-a024b208ef8a.png)

Any help would be appreciated. Thank you!

**Comment by brendanheywood** [comment]
hi @taselian 

The redis store specifically for saml2 is optional and only really for large scale high performance clusters and unrelated to the redis cache store. If you do not need it then don't configure it at all and I'd remove all 3 of those config items. For 99% of setups you should not need to touch the moodle config.php at all

It should be moot, but to answer your question directly, if you use single quotes you don't need to escape the \ but you do if you use double quotes
