### ISSUE TITLE
Unable to load private key from file

### ISSUE THREAD

**Issue by louman** [catalyst/moodle-auth_saml2#451]
**What happened?**

Hi there, I'm trying to install the plugin for a client however I'm running into the error `Unable to load private key from file`.

![Screen Shot 2020-09-04 at 9 10 06 am](https://user-images.githubusercontent.com/116700/92182247-8f969a80-ee8e-11ea-9a1d-6696f9b00440.png)

Have checked and openssl is installed and enabled but it looks like the certificate is not being generated?

Also, when I go to the login page, the SSO button is not displayed even though `dual login` is enabled and `Display IdP link` is YES.

Moodle version: 3.8
Plugin version: master
OS: Windows

**Comment by brendanheywood** [comment]
Have you read through all the gotchas, maybe this one?

https://github.com/catalyst/moodle-auth_saml2#openssl-errors-during-certificate-regeneration
