### ISSUE TITLE
Official 3.9 Support

### ISSUE THREAD

**Issue by BerengarWLehr** [catalyst/moodle-auth_saml2#464]
The README.md states that the master-branch supports Moodle 3.5-3.8
Are there any experiences with moodle 3.9 for this plugin?

**Comment by brendanheywood** [comment]
We are currently upgrading the simplesamlphp internal lib and we will publish a 3.9 version in the plugins dir after that.

I believe it is currently working in 3.9 for some of our clients as-is already, I've personally tested it on 3.10 / master on my local dev

**Comment by hdagheda** [comment]
Official 3.9 support has been added.
