### ISSUE TITLE
PHP lint fails

### ISSUE THREAD

**Issue by alexmorrisnz** [catalyst/moodle-auth_saml2#467]
**What happened?**
PHP lint fails after the simplesamlphp library update yesterday in PR #465.  
Failing on php 7.2.24

```
PHP Parse error:  syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST) in server/auth/saml2/.extlib/simplesamlphp/vendor/symfony/config/Tests/Fixtures/ParseError.php on line 8\nxargs: /usr/bin/php7.2: exited with status 255; aborting
```

https://github.com/catalyst/moodle-auth_saml2/blob/master/.extlib/simplesamlphp/vendor/symfony/config/Tests/Fixtures/ParseError.php is the file causing the error

**What you expected:**
PHP lint to not fail

**Comment by brendanheywood** [comment]
@Anupamatd  / @jwalits can you please make sure that when you merge things in that the linked issues are also closed
