### ISSUE TITLE
PHP unit tests fail in 3.9 if run as a testsuite

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-auth_saml2#469]
Steps to replicate:

1. Get a vanilla 3.9
2. Pull auth_saml2 plugin code in.
3.  php admin/tool/phpunit/cli/init.php
4. Run core tests ./vendor/bin/phpunit --stop-on-failure --testsuite core_testsuite
5. Get the failure

This happens because PHPMailer gets auto-loaded from auth_saml2 plugin and it has a different (higher) version to what's in core.   

```

Time: 21.34 minutes, Memory: 297.00 MB

There was 1 failure:

1) core_moodlelib_testcase::test_email_to_user_attachment with data set "cachedir" ('/var/lib/sitedata/moodle-test/cache')
Failed asserting that 'This is a multi-part message in MIME format.\n
\n
--b1_NQnOschkfbWNggpTPMVlFmZmaXXR77vq99fKNsmqAEM\n
Content-Type: multipart/alternative;\n
 boundary="b2_NQnOschkfbWNggpTPMVlFmZmaXXR77vq99fKNsmqAEM"\n
\n
--b2_NQnOschkfbWNggpTPMVlFmZmaXXR77vq99fKNsmqAEM\n
Content-Type: text/plain; charset=UTF-8\n
Content-Transfer-Encoding: quoted-printable\n
\n
=0ATest attachment path=0A\n
--b2_NQnOschkfbWNggpTPMVlFmZmaXXR77vq99fKNsmqAEM\n
Content-Type: text/html; charset=UTF-8\n
Content-Transfer-Encoding: quoted-printable\n
\n
Test attachment path\n
\n
--b2_NQnOschkfbWNggpTPMVlFmZmaXXR77vq99fKNsmqAEM--\n
\n
--b1_NQnOschkfbWNggpTPMVlFmZmaXXR77vq99fKNsmqAEM\n
Content-Type: text/plain; name=hello.txt\n
Content-Transfer-Encoding: base64\n
Content-Disposition: attachment; filename=hello.txt\n
\n
SGVsbG8=\n
\n
--b1_NQnOschkfbWNggpTPMVlFmZmaXXR77vq99fKNsmqAEM--\n
' contains "Content-Type: text/plain; name="hello.txt"".

/var/www/project/moodle/lib/tests/moodlelib_test.php:111
/var/www/project/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "core_moodlelib_testcase" lib/tests/moodlelib_test.php

FAILURES!
Tests: 2069, Assertions: 39356, Failures: 1, Skipped: 2.
```

**Comment by Anupamatd** [comment]
Hi,

This PHP unit tests fail came again due to recent update simplesamlphp to 1.19.1 with below commit:
https://github.com/catalyst/moodle-auth_saml2/commit/d0dfa3bc8f697f7fa9fa1314163d40cc84cbca17

Thanks,
Anu

**Comment by dmitriim** [comment]
@Anupamatd  this was the fix https://github.com/catalyst/moodle-auth_saml2/commit/1c40898b1688f79561461c9f388858f6e8425c10

**Comment by Anupamatd** [comment]
Thank you @dmitriim - will try this https://github.com/catalyst/moodle-auth_saml2/commit/1c40898b1688f79561461c9f388858f6e8425c10.
I thought this was the fix https://github.com/catalyst/moodle-auth_saml2/pull/471/commits/6285e03932f021e991ac274dee68e3e85abb0403

**Comment by dmitriim** [comment]
Oh. Maybe you are right. Or maybe both?

**Comment by Anupamatd** [comment]
Hey @dmitriim - This fix (https://github.com/catalyst/moodle-auth_saml2/commit/6285e03932f021e991ac274dee68e3e85abb0403) fixed issue in my local 

Do i need to also remove composer files from compiled extlib/simplesamlphp (https://github.com/catalyst/moodle-auth_saml2/commit/1c40898b1688f79561461c9f388858f6e8425c10)?

**Comment by dmitriim** [comment]
I'd recommend it.

**Comment by Anupamatd** [comment]
Thank you @dmitriim - will remove that.

**Comment by Anupamatd** [comment]
Hey @dmitriim - Created a PR - https://github.com/catalyst/moodle-auth_saml2/pull/611
Please review and merge.
Thank you.
