### ISSUE TITLE
Okta and Moodle metadata issue

### ISSUE THREAD

**Issue by taselian** [catalyst/moodle-auth_saml2#473]
We are trying to create a single sign-on for Okta and Moodle with SAML 2 plugin. 

When I sign in through Okta, I receive this error: SAML2 exception: Cannot retrieve metadata for IdP 'http://www.okta.com/exk8mmqsjwtXSpPLD2p7' because it isn't a valid IdP for this SP.

![2020-10-22_idperror](https://user-images.githubusercontent.com/69809248/96936131-559f4900-147a-11eb-89bf-a96616bf0b6a.png)

When I sign in through the SAML button on Moodle, I get the same error. However, if I'm already logged into Okta, I can click the app button and it sends me to Moodle with no issue.

We can't log in directly through Moodle or Okta, but if we're already logged into Okta, we can access Moodle.

Here is our IdP metadata link: https://littelfuse.okta.com/app/exk8mmqsjwtXSpPLD2p7/sso/saml/metadata
Our SP metadata link: https://lfi.ascendislms.com/auth/saml2/sp/metadata.php

What am I missing? Thanks for any help you can give. ~April

**Comment by mccork91** [comment]
@taselian  - did you find a resolution to the problem - we have also found the same error today with the SAML plugin and OKTA?

**Comment by taselian** [comment]
> @taselian - did you find a resolution to the problem - we have also found the same error today with the SAML plugin and OKTA?

No, I haven't as of yet.

**Comment by mccork91** [comment]
@taselian - I would suggest reviewing the OKTA specific configuration recommended on https://github.com/catalyst/moodle-auth_saml2

In addition try downloading the latest version of the plugin from GITHUB here rather than the Moodle plugins Contrib library.

That might help

**Comment by taselian** [comment]
> @taselian - I would suggest reviewing the OKTA specific configuration recommended on https://github.com/catalyst/moodle-auth_saml2
> 
> In addition try downloading the latest version of the plugin from GITHUB here rather than the Moodle plugins Contrib library.
> 
> That might help

Thanks for getting back to me. I updated the plugin, as suggested, but I received the same error. 

I sent the Okta mapping suggestions to the developer and he sent the following screenshot back to me:
![image011](https://user-images.githubusercontent.com/69809248/97039116-c39e4b80-1520-11eb-9ad0-8af19ba03b00.png)

Maybe the Okta labels aren't quite the same as the mapping? I'm not sure. I do know that when I look at the IdP xml the Entity ID is okta.com/lotsofnumbersgohere rather than the suggested https://example.com/auth/saml2/sp/metadata.php
--

**Comment by taselian** [comment]
Update: We flipped on the Assertion Encryption, and it works kinda. I can log in through the SAML button on the Moodle sign-in page. If I'm already logged into Okta, I can click the Moodle app button and it logs me into Moodle. However, if I try a cold login (not signed into either) and try logging through the Okta login page, then hit the app button, I still get the same error. 

I hope that makes sense.

**Comment by hbowers72** [comment]
Hi @taselian -  did you get a resolution to this?  We are having the same issue with our log into Moodle, via our OKTA instance, using SAML2.  However, we can log in using SAML2/OKTA via the Moodle page.  We have tried all the steps mentioned in this thread.

**Comment by adishare** [comment]
![image](https://user-images.githubusercontent.com/40617809/98950362-7b74b680-252b-11eb-9dae-131004dcd349.png)

same here, okta - moodle issue

**Comment by iv-enovation** [comment]
It looks like we managed to configure Okta to work with auth_saml2. Here is what we did:
1) in /auth/saml2/config/config.php:
    #'timezone' => class_exists('core_date') ? core_date::get_server_timezone() : null,                                                                                                             
    'timezone' => 'Europe/Dublin', 
Notes: this may be our installation specific, but apparently the time mismatch is a valid reason to reject an IdP response. It was clearly visible in simplesamlphp.log that reported events are far beyond a frame of NotBefore and NotOnOrAfter

2) in /auth/saml2/config/authsources.php:
    #$idp = md5($idpentity->entityid);
    $idp = $idpentity->entityid; 
Notes: This was the fix for the IdP-initiated login

3) In Moodle in the plugin configuration:
    dual login -> "off"
    alternative logout url -> https://example.okta.com/login/signout
Notes: with the Dual login "on" the IdP-initiated login ends on the Moodle login page, with a user not logged in. The alternative login URL seems mandatory to end the Okta's session

**Comment by brendanheywood** [comment]
I think this branch should fix this bug, please give it a whirl and let me know:

https://github.com/catalyst/moodle-auth_saml2/pull/487/files
