### ISSUE TITLE
Moodle 3.9 support?

### ISSUE THREAD

**Issue by Urpokarhu1** [catalyst/moodle-auth_saml2#474]
Hello,

When you will release Moodle 3.9 version at 

https://moodle.org/plugins/auth_saml2/

that supports SAML 2.0 ? The version avaible at moodle.org doesn't contain newest security updates and is missing Auth Proc Filter Hooks

**Comment by danmarsden** [comment]
@Urpokarhu1 can you please stop asking this in our repos? We dont regularly release in the plugins db, latest support is available in github so you may need to adjust your scripts to support git.

Unfortunately a bug in moodles zip handling prevents us from uploading saml2 in the plugins db too, so until HQ resolves this we cant update it anyway.

**Comment by Urpokarhu1** [comment]
Hello,

thanks for the reply, if I switch our scripts to using Github how can I know which branch is stable/production version? And how can I know what Moodle version it supports?

**Comment by danmarsden** [comment]
Probably best to ask those sorts of questions in the moodle forums. Thanks!

**Comment by brendanheywood** [comment]
@Urpokarhu1 see: https://github.com/catalyst/moodle-auth_saml2#branches

**Comment by brendanheywood** [comment]
p.s. please go vote for this: https://tracker.moodle.org/browse/MDLSITE-4781
