### ISSUE TITLE
Language strings

### ISSUE THREAD

**Issue by RussellEngland** [catalyst/moodle-auth_saml2#494]
Hey chaps :)

Is it possible to change the language strings for the the login form without editing the code? Or use Moodle language strings? 

For example, on the login page, we want to change the "Remember me" text on the login screen for various languages.

Which looks like is in this file

                    <label for="remember_me" class="pure-checkbox">
                    <input id="remember_me" type="checkbox" tabindex="5"
                            {{ rememberMeChecked ? 'checked="checked"' }} name="remember_me" value="Yes"/>
                        <small>{{ 'Remember me'|trans }}</small>
                    </label>

Which looks like uses the translations in this file

/auth/saml2/extlib/simplesamlphp/dictionaries/login.translation.json

Although it looks like the simplesaml site says the code will need to be edited.

https://simplesamlphp.org/docs/stable/simplesamlphp-maintenance#section_9

**Comment by brendanheywood** [comment]
All strings used should be 100% moodle strings. I'm not even sure this question makes sense, the login page above would be on the IdP side, not on the SP side. Are you using simplesamlphp as your idp?

**Comment by RussellEngland** [comment]
ohhhhhhhhh, really sorry, I'm an idiot. It's displaying the login form from the SSO not Moodle.

Cheers.
