### ISSUE TITLE
Does the current plugin release support Moodle 3.9.x or 3.10.x ?

### ISSUE THREAD

**Issue by mlewis1dps** [catalyst/moodle-auth_saml2#517]
The last supported version is listed as Moodle 3.7.x. Is there a plan to update or test the SAML plugin against newer releases?

**Comment by danmarsden** [comment]
please see the github readme:
https://github.com/catalyst/moodle-auth_saml2#branches

the master branch supports 3.5 and higher - 3.10 isn't mentioned in the readme specifically but it should work fine.

We do not update the moodle.org plugins db regularly - the latest version is always in github and you should check the readme file as we usually state which moodle versions are supported there.

(the Moodle.org plugins db also has a bug which prevents us uploading the latest saml2 plugin. https://tracker.moodle.org/browse/MDLSITE-6263)
