### ISSUE TITLE
Error on logout from SP

### ISSUE THREAD

**Issue by ahelton-ips** [catalyst/moodle-auth_saml2#520]
**What happened?**
We have a Moodle site that uses saml2 as SP. 
When a user logs out of our site, they will see this screen.
![image](https://user-images.githubusercontent.com/59488858/106034256-b1dcbf00-60a0-11eb-96a0-52521778568b.png)

It seems that the '`doLogout`' function in SimpleSaml/Session.php is called before the sp/saml2-logout.php calls '`registerLogoutHandler`' function. The '`doLogout`' function unsets the `$this->authdata[$authority]` before '`registerLogoutHandler`' asserts that `isset($this->authData[$authority])`

**What you expected:**
User would be logged out without error.

**Comment by brendanheywood** [comment]
Side note: regardless of the error under the hood, you appear to have $CFG->debugdisplay on, which should never be on in production
