### ISSUE TITLE
Failed to sign the local Moodle certificate

### ISSUE THREAD

**Issue by dqu002** [catalyst/moodle-auth_saml2#524]
We have moodle 3.8 installed on AWS EC2. I'm trying to get saml2 plugin work but getting the following error:
"Exception - Failure Signing Data: error:0907B068:PEM routines:PEM_READ_BIO_PRIVATEKEY:bad password read - SHA256"

I cleared the private certificate key password and regenerated the certificate, I got another error:
"Exception - Failure Signing Data: error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error - SHA256"

Can anyone please shed light why I'm getting these type of errors? The log simplesamlphp.log doesn't help much.

**Comment by brendanheywood** [comment]
Can you please provide a full stack trace? This seems like an issue with openssl, what version of openssl do you have installed? I wonder if its related to this bug:

https://github.com/openssl/openssl/issues/9695

**Comment by dqu002** [comment]
I got it fixed now. I manually generated the cert and key files, replaced into metadata file. Then uploaded onto idp, sso is working now.

Just for anyone who is interested:
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650 -nodes

**Comment by dqu002** [comment]
> 
> 
> Can you please provide a full stack trace? This seems like an issue with openssl, what version of openssl do you have installed? I wonder if its related to this bug:
> 
> [openssl/openssl#9695](https://github.com/openssl/openssl/issues/9695)

Thanks Brendan for your reply. 

Yes openssl version is bit low in EC2, i.e. 1.0.2k. If I manually run openssl to generate cert/key, it's actually working. But if I generate cert through GUI, the key is always in error. 

FYI, I also tried when using bitnami debian image, openssl version is 1.1.1d. I can use GUI to generate certificate without any issue.

**Comment by brendanheywood** [comment]
Glad you sorted it :)

**Comment by rajohns08** [comment]
@dqu002, how did you replace the SAML2 SP metadata in moodle? I only see options to "View Service Provider Metadata" and "Download SP Metadata" in the SAML2 moodle settings page.
