### ISSUE TITLE
node_modules included for SimpleSAMLphp?

### ISSUE THREAD

**Issue by sammarshallou** [catalyst/moodle-auth_saml2#527]
Since the last update of the SimpleSAMLphp library in .extlib, the node_modules has been included. It wasn't included in the previous versions.

Is this actually needed or is it like Moodle where it's an artefact of the build process and doesn't need to be in the repo? Because it's 11k files, it has a non-negligible effect on deployments etc.

I tried deleting it on our system and I can still log in but I realise this is not a very thorough test and maybe there is some reason it's needed. :) However, in case not, I'll submit a pull request.

**Comment by kabalin** [comment]
I think this should be closed as being addressed in #528 ?

**Comment by danmarsden** [comment]
Yep
