### ISSUE TITLE
Aks with users

### ISSUE THREAD

**Issue by VansaLatam** [catalyst/moodle-auth_saml2#531]
Hi, this plugin allow to synchronize users automatically with de IdP? If possible, could you tell me how?

Thanks for this plugin.

**Comment by brendanheywood** [comment]
You can either create users on demand which is one of the settings, or if you want a batch synchronization then then is best done with either the auth_ldap sync and then saml on top, or another integration which provisions accounts. The saml spec doesn't provide any way to synchronize accounts outside of an authentication flow.
