### ISSUE TITLE
Exception - The configuration is invalid: Setting secure cookie on plain HTTP is not allowed

### ISSUE THREAD

**Issue by isotopeee** [catalyst/moodle-auth_saml2#542]
**What happened?**

I'm getting this error: Exception - The configuration is invalid: Setting secure cookie on plain HTTP is not allowed

![13 213 30 253_moodle_login_index php(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/17417116/116776946-0c215d80-aa9e-11eb-85b8-b1c52e604d1f.png)

Here's the error on Test settings screen with debugging enabled:

![13 213 51 238_moodle_auth_saml2_test php(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/17417116/116783744-0c801f80-aac3-11eb-80be-021255bb3175.png)

I'm testing on a sandbox site so the site isn't on HTTPS, is it required to be on HTTPS?

What do I need to do if I don't want to install an SSL certificate? I don't want to waste my time installing an SSL certificate in our test instances as we're just trying out Moodle.

**Comment by danmarsden** [comment]
You could try turning off the secure cookie setting under HTTP Security: 
https://docs.moodle.org/en/HTTP_security

But - we don't support the use of saml2 over http only - we reccommend that you run ssl certs on all webservers - not just production systems. I would also advise you look into automating your ssl cert management using lets encrypt.

thanks,
