### ISSUE TITLE
Error while setting IdP metadata url „Huge input lookup“

### ISSUE THREAD

**Issue by mrkskwsnck** [catalyst/moodle-auth_saml2#543]
**Where did it happen?**

System: Moodle 3.9.5+ (Build: 20210312)
Plug-in: SAML2 (Build: 2021040100)

**What happened?**

When I try so set the IdP metadata public xml URL (https://www.aai.dfn.de/fileadmin/metadata/dfn-aai-edugain+idp-metadata.xml), the plug-in answers „no it can′ be done“ with the following error (also see Screenshot):

```
The IdP XML isn't valid<br>Error (4) line 1 char 1: Start tag expected, '<' not found <br>Error (1) line 535000 char 339: internal error: Huge input lookup
```

![image](https://user-images.githubusercontent.com/486983/116853172-e3ac7700-abf5-11eb-991c-aee79265ef32.png)

Apart from the above message, there is no stacktrace nor log lines. However, I don′t think the XML document is not valid. My guess is its size of 46 MB could be the issue here, which is huge, indeed.

Also, I stumbled over the issue https://github.com/catalyst/moodle-auth_saml2/issues/519 which seems to be similar, but with a different error. So, I doubled the `memory_limit` in `php.ini` from 128M to 256M, already.

**What you expected:**

The IdP metadata public xml URL (https://www.aai.dfn.de/fileadmin/metadata/dfn-aai-edugain+idp-metadata.xml) should be set successfully.

**Comment by mrkskwsnck** [comment]
It turns out: _Size really matters._

I was able to fix my issue by passing the [option constant](https://www.php.net/manual/en/libxml.constants.php) `LIBXML_PARSEHUGE` to LibXML, that says…

>  Sets XML_PARSE_HUGE flag, which relaxes any hardcoded limit from the parser. This affects limits like maximum depth of a document or the entity recursion, as well as limits of the size of text nodes. 

See my patch below.

```diff
diff --git a/classes/admin/setting_idpmetadata.php b/classes/admin/setting_idpmetadata.php
index d31e7550..a1cf8785 100644
--- a/classes/admin/setting_idpmetadata.php
+++ b/classes/admin/setting_idpmetadata.php
@@ -219,7 +219,7 @@ class setting_idpmetadata extends admin_setting_configtextarea {

         $rawxml = $idp->rawxml;

-        if (!$xml->loadXML($rawxml)) {
+        if (!$xml->loadXML($rawxml, LIBXML_PARSEHUGE)) {
             $errors = libxml_get_errors();
             $lines = explode("\n", $rawxml);
             $msg = '';
```

I don′t know whether this is worth a PR. I would prefer to leave the LibXML defaults, as long a minority of users stumble over this issue only. But what about a hint and a checkbox (to parse huge) in the plug-in settings page? #featurerequest

**Comment by brendanheywood** [comment]
@mrkskwsnck wow that is some hectic xml :)

I'm not fussed either way, allowing PARSEHUGE isn't easily abused as its admin only so I'm fine to see this land if you make a pr

**Comment by mrkskwsnck** [comment]
@brendanheywood Thanks for your feedback. So, I just created the PR (see https://github.com/catalyst/moodle-auth_saml2/pull/564).

**Comment by brendanheywood** [comment]
thanks @mrkskwsnck
