### ISSUE TITLE
Could not find the metadata of an IdP with entity ID 'https://xxxx.my.salesforce.com'

### ISSUE THREAD

**Issue by Bq6mzBQlpX323V9v** [catalyst/moodle-auth_saml2#547]
Dears

Is there any way to configure the plugin without the IdP metadata? Is it mandatory?  Mine IdP hasn't provided anything except the configuration that leads to my website, which seems to be working correctly (I get a correct SAML response) but when I try to login there's an error: _SAML2 exception: Cannot retrieve metadata for IdP 'https://xxxx.my.salesforce.com' because it isn't a valid IdP for this SP_ or _SAML2 exception: Could not find the metadata of an IdP with entity ID 'https://xxxx.my.salesforce.com'_

Trying the _auth/saml2/test.php_ page just got:
     SP name: webname
     Which IdP will be used? d41d8cd98f00b204e98
     You are not logged in: Login | isPassive test

- If I try the **login option**, there's a new page that says: Select your identity provider (but no providers at all to select)
- I the **isPassive test,** then _SimpleSAML\Error\BadRequest: BADREQUEST('%REASON%' => 'Missing idpentityid to discovery service response handler')_

The IdP is a Salesforce one (https//xxxx.my.salesforce.com).   
Moodle version is 3.10.3
Plugin version is the latest stable. 

This is my first time with SAML and I'm a bit lost. 

Any help would be greatly appreciated.

Fabian

**Comment by danmarsden** [comment]
Hi Fabian, 

Saml definitely requires the sharing of metadata.
A google search suggests this is the document you should be looking at:
https://help.salesforce.com/articleView?id=sf.identity_provider_enable.htm&type=5

It states:
To download an XML file with metadata about your identity provider, click Download Metadata. Your service provider can use the metadata to connect to Salesforce.
Grab that xml file and paste the contents into the metadata in the Moodle config.

If you're still stuck and you are looking for "free" help, you might need to ask in the moodle.org community forums, or give your salesforce support contact a go.

Catalyst is a Moodle Partner and we can provide a range of support services around Moodle - feel free to reach out via the contact information in the readme here if you would like commercial level support with your site.

Good luck!

**Comment by Bq6mzBQlpX323V9v** [comment]
Thanks a lot Dan. Much appreciated. I've asked for the metadata and just in case that fails, I contacted Catalyst to get help for this issue or other that may arise in the future.
