### ISSUE TITLE
View Service Provider Metadata and Download SP Metadata generate empty page

### ISSUE THREAD

**Issue by mspall** [catalyst/moodle-auth_saml2#552]
On the saml2 configuration page I use the View Service Provider Metadata and Download SP Metadata links and they both generate an empty page. I am testing this plugin on a vanilla Moodle 3.9 site with just this plugin. Environment is PHP 7.4, PHP-FPM, and Apache 2.4. No errors show in the php-fpm or apache logs.

**Comment by kabalin** [comment]
Just to confirm on 3.11 php7.4 this page contains metadata in XML format. Try to set [DEBUG_DEVELOPER](https://docs.moodle.org/311/en/Debugging#Enabling_debugging) level in Moodle and navigate to the page to see if there is any error output.

**Comment by mspall** [comment]
Thank you for your reply. I figured it out. I was using code from Jan 13th, the day before the bug fix, and I thought I was using the latest. Updating fixed the issue.
