### ISSUE TITLE
User authorisation failure should trigger \core\event\user_login_failed

### ISSUE THREAD

**Issue by kabalin** [catalyst/moodle-auth_saml2#563]
It is important to trigger `\core\event\user_login_failed` when login is not successful for whatever reason.

**Comment by brendanheywood** [comment]
If saml login fails, then they never reach moodle at all. So under what conditions would this trigger?

**Comment by kabalin** [comment]
> If saml login fails, then they never reach moodle at all. So under what conditions would this trigger?

In pretty much all cases when we reach `handle_blocked_access`, but also when user is suspended, user does not exist (and no autocreate), email taken, wrong auth type, etc.

**Comment by brendanheywood** [comment]
Yeah of course, that makes sense
