### ISSUE TITLE
Move commits from MOODLE_39_STABLE into master

### ISSUE THREAD

**Issue by andrewmadden** [catalyst/moodle-auth_saml2#572]
master branch needs the improvements to the testing that were added to the MOODLE_39_BRANCH

**Comment by danmarsden** [comment]
master branch has been deprecated. - it's only still here because we're waiting on AU to fix pipelines - it's slated to be deleted.

**Comment by danmarsden** [comment]
I've just reverted that PR - it will break AU Pipelines for sites that are using the "master" branch on older versions of Moodle.

**Comment by Peterburnett** [comment]
Ah, is the readme stale?

**Comment by Peterburnett** [comment]
Nope im just a dummy, there is breaking changes, needs to be a batch cherry-pick @andrewmadden
