### ISSUE TITLE
To be able to match by unique custom user profiles fields 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-auth_saml2#577]
Would be nice to be able to match users by unique custom user profile fields along with username, email and user idnumber.

**Comment by brendanheywood** [comment]
Can't it be the existing setting but extend the dropdowns to include all extra saml attributes or moodle custom profile fields which are of type text?

**Comment by dmitriim** [comment]
that exactly what I have done sp far see https://github.com/catalyst/moodle-auth_saml2/pull/603
