### ISSUE TITLE
Error on site: Exception - Call to undefined method core\ip_utils::is_ip_in_subnet_list()

### ISSUE THREAD

**Issue by jmayermsi** [catalyst/moodle-auth_saml2#580]
Getting this error when enabling the plugin on Moodle 34.

Exception - Call to undefined method core\ip_utils::is_ip_in_subnet_list()

Any suggestions?

**Comment by danmarsden** [comment]
@jmayermsi, please see here for the correct branches to use for different Moodle versions:
https://github.com/catalyst/moodle-auth_saml2#branches

Please note - Moodle has not supported 3.4 for over 2 years, and we don't provide support for unsupported releases here either.
