### ISSUE TITLE
GCMEncryption

### ISSUE THREAD

**Issue by lselanne** [catalyst/moodle-auth_saml2#582]
GCMEncryption would need to be added as part of SAML2 authentication plugin.

The GCMEncryption is currently not available in the SAML2 plugin, but according to https://github.com/simplesamlphp/saml2/issues/179 discussion, it has been added as part of simplesamlphp.

More information: https://wiki.shibboleth.net/confluence/display/IDP4/GCMEncryption

**Comment by danmarsden** [comment]
We are currently using v1.18.8 and it sounds like that landed in v 1.19 and higher - we should update to a newer library at some point, but there is a bit of work involved there in getting that right and testing it - feel free to reach out privately if you would like to fund the work required.

**Comment by danmarsden** [comment]
@lselanne - if you were able to test the pull request #604 which contains an update to simplesaml to see if it fixes your issue that would be great!

**Comment by lselanne** [comment]
> @lselanne - if you were able to test the pull request #604 which contains an update to simplesaml to see if it fixes your issue that would be great!

Great news. Unfortunately I can't test this since it would need many third parties involvement.

**Comment by danmarsden** [comment]
I'm closing this off as it relates to simplesamlphp which we have since upgraded - feel free to report another issue if you have issues with saml2's implementation of simplesamlphp
