### ISSUE TITLE
Could GitHub releases for each version be maintained

### ISSUE THREAD

**Issue by trenta** [catalyst/moodle-auth_saml2#584]
Our method of deployment relies on GitHub releases. The last release for this project is 2019022100. Can this be updated to include the new versions of the module please?

Cheers

Trent

**Comment by danmarsden** [comment]
Hi there!

our method of deployment does not use Github releases (we use git submodules/subtrees etc) we also maintain and support a very large number of plugins and do not have plans to move to generating releases in github. We do have plans to look at auto-deploying updates to the moodle.org plugins db as per:
https://moodle.org/mod/forum/discuss.php?d=423251#p1705237

I'm not aware of many plugin developers relying on github releases for their plugins - you might want to consider adopting a different deployment strategy or tie into the plugin releases that come from the moodle.org plugins database.

thanks!
