### ISSUE TITLE
Unit Test Failure in MWP 3.11.1 - auth_test.php > null instead of string given

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-auth_saml2#588]
When running the unit test suite for this plugin when installed in a MWP 3.11.1 site test throw errors.

Error received is:
`TypeError: Argument 1 passed to tool_tenant\local\auth\saml2\manager::complete_login_hook() must be of the type string, null given`

"Full" stack trace: 
```
/var/www/workplace/xxxxxxxxxxx/manager.php:78
/var/www/workplace/lib/moodlelib.php:8000
/var/www/workplace/auth/saml2/classes/auth.php:616
/var/www/workplace/auth/saml2/tests/auth_test.php:476
/var/www/workplace/lib/phpunit/classes/advanced_testcase.php:80
```

There is a callback in `classes/auth.php` that passes a null in certain situations, code below:
```        component_class_callback('\tool_tenant\local\auth\saml2\manager', 'complete_login_hook',
            [$SESSION->saml2idp ?? null, $uid, $user]);
```

However the callback signature expects that value to be a string.  An easy fix seem to be passing an empty string instead.
I'll make a patch that does this

**Comment by kabalin** [comment]
Interesting, we did not have any phpunit errors in Workplace CI. Thanks for fixing this.

**Comment by danmarsden** [comment]
I suspect you may need to improve your unit test runs - also see: https://tracker.moodle.org/browse/WP-2774
