### ISSUE TITLE
Moodle SAML2 issue after SSO login

### ISSUE THREAD

**Issue by feweissman** [catalyst/moodle-auth_saml2#599]
Get main moodle page opens with an error message 

Exception - Call to undefined function mcrypt_module_open()

More information about this error (no info given)

Expected to seen my main page with 2 courses

**Comment by danmarsden** [comment]
mcrypt was removed from PHP - you can manually install it or update to a more recent version of auth_saml2 that does not include a requirement for mcrypt.
