### ISSUE TITLE
variant mapping

### ISSUE THREAD

**Issue by effebi68** [catalyst/moodle-auth_saml2#60]
Is it possible to map an attribute w.r.t. another one?

In particular, we should populate our Moodle database with students' external e-mail address and teachers' internal one (in this case, we discriminate between students and teachers by checking the presence of another field in the response from our IdP).

Best regards.

**Comment by brendanheywood** [comment]
No all the mappings are treated the same and the config settings for this are the same across all moodle auth plugins.

What you want could probably be implemented fairly easily by hacking update_user_profile_fields()

**Comment by effebi68** [comment]
In the end we dealt with our problem with a SQL trigger.
