### ISSUE TITLE
including settings.php file executes huge amounts of code

### ISSUE THREAD

**Issue by timhunt** [catalyst/moodle-auth_saml2#616]
**What happened?**

On my Behat site, where I have no interest in using this plugin, I get this when going to admin notifications:

Exception - Warning: openssl_csr_sign(): cannot get CSR from parameter 1 in [dirroot]\auth\saml2\setuplib.php on line 79

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 157 of \lib\behat\lib.php: Exception thrown
    line ? of unknownfile: call to behat_error_handler()
    line 79 of \auth\saml2\setuplib.php: call to openssl_csr_sign()
    line 64 of \auth\saml2\setup.php: call to create_certificates()
    line 1062 of \auth\saml2\auth.php: call to require_once()
    line 298 of \auth\saml2\settings.php: call to auth_plugin_saml2->get_ssp_version()
    line 85 of \lib\classes\plugininfo\auth.php: call to include()
    line 134 of \admin\settings\plugins.php: call to core\plugininfo\auth->load_settings()
    line 8857 of \lib\adminlib.php: call to require()
    line 821 of \admin\index.php: call to admin_get_root()

**What you expected:**

1) If the plugin is being using, then it should not cause fatal erros.

2) Building the admin tree should not execute lots of code. If admin settings need fancy initialisation, then that should be lazy-loaded. This is a performance bug.

**Comment by timhunt** [comment]
In my case, it is dying because of these errors (which are not reported unless I stick in print_objects) I am not going to make a separate issue for this, but 

3) create_certificates needs proper error handling. 

for me the call to `$privkey = openssl_pkey_new($opensslargs);` is generating these errors:

<ul>
<li>error:02001003:system library:fopen:No such process</li>
<li>error:2006D080:BIO routines:BIO_new_file:no such file</li>
<li>error:0E064002:configuration file routines:CONF_load:system lib</li>
<li>error:02001003:system library:fopen:No such process</li>
<li>error:2006D080:BIO routines:BIO_new_file:no such file</li>
<li>error:0E064002:configuration file routines:CONF_load:system lib</li>
</ul>

No idea what that means or how to get around it :-(

Possibly that suggests

4) If this plugin needs stuff in order to work, implement a proper environment check https://docs.moodle.org/dev/Environment_checking

**Comment by brendanheywood** [comment]
+1 for the admin tree performance bug, I'll add that to the queue

I'm not sure about point 4 I've never seen that, this plugin already does declare that it needs the openssl libs so no idea what's going on with that

https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/environment.xml#L11

**Comment by timhunt** [comment]
The openSSL library is installed, but openssl_csr_new is returning null here https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/setuplib.php#L78 (which is not checked).

**Comment by timhunt** [comment]
Re the windows config thing, a colleague has now told me the magic trick:

### Windows configuration for OpenSSL

If you are running Moodle locally on a Windows machine, then on various Moodle screens including the admin page you may see errors related to the auth_saml2 plugin. For example:

    Warning: openssl_csr_sign(): cannot get CSR from parameter 1 in C:\Users\sm449\workspace\ou-moodle2\auth\saml2\setuplib.php

This means you have not defined an openssl.cnf file.

There are two ways to resolve this problem (you only need to do one of these, the first is probably more sensible):

* Set the OPENSSL_CONF environment variable to point to the full path and location of an openssl.cnf file (e.g. C:\tools\php73\extras\ssl\openssl.cnf) and restart Apache.
* (for PHP versions <= 7.3) Make a copy of that openssl.cnf file in the location C:\usr\local\ssl\openssl.cnf.

**Comment by katerynadegtyariova** [comment]
Added PR to skip full initialization upon building the admin tree:
https://github.com/catalyst/moodle-auth_saml2/pull/620

**Comment by brendanheywood** [comment]
I've also copied that chunk into the readme:

https://github.com/catalyst/moodle-auth_saml2#windows-configuration-for-openssl

**Comment by timhunt** [comment]
Awesome. Thanks.
