### ISSUE TITLE
Simple saml lib is on unstable trunk and should be on a stable eg 1.14

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_saml2#62]
* [x] upgrade to 1.14
* [x] update the docs to make this cleaner ongoing
* [x] show the SSP version number somewhere in the config settings

https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.14/lib/SimpleSAML/Configuration.php#L328

**Comment by nhoobin** [comment]
This is associated with pull request #66.
