### ISSUE TITLE
MNet integration has been removed in Totara 14+

### ISSUE THREAD

**Issue by SashaAnastasi** [catalyst/moodle-auth_saml2#626]
This affects installations using moodle-auth_saml2/MOODLE_35_STABLE.

`auth_saml2_locallib_testcase::test_is_email_taken` now causes a dml_write_exception during phpunit tests since the value of user.mnethostid is now hardcoded to be 1, with a check constraint to enforce this.
```
TL-28140   The MNet integration has been removed
                   The MNet integration in Totara was deprecated in Totara 13, and has now
                   been removed.
                   The user.mnethostid column has been removed from the database. Any custom
                   plugins still referencing the field will need to be updated.
```

**Comment by danmarsden** [comment]
Thanks @SashaAnastasi - Brendan and I had a conversation about this and we've decided there's little benefit to us testing MNET within the saml2 code - especially if it would require us to maintain separate versions of the code, I'm going to drop this patch into our latest branch as well for MOODLE_39_STABLE so it's consistant across our supported versions. Eventually HQ will also deprecate/remove mnet as they've been warning for so long....
