### ISSUE TITLE
Failed PHPunit tests on Moodle 4.0. auth_saml2\event\cert_regenerated Object (...) 

### ISSUE THREAD

**Issue by sumaiyamannan** [catalyst/moodle-auth_saml2#637]
**What happened?**
PHPUnit tests fail after changes on 16 Dec from moodle upstream

Error received:
-------------------------------------
There was 1 failure:

1) tool_admin_presets\local\action\export_test::test_export_execute with data set "Export settings and plugins, excluding sensible" (false)
Failed asserting that auth_saml2\event\cert_regenerated Object (...) is an instance of class "\tool_admin_presets\event\preset_exported".

/var/www/html/admin/tool/admin_presets/tests/local/action/export_test.php:151
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:91

**What you expected:**
The PHPUnit test should have passed.

**Comment by danmarsden** [comment]
this one seems to have resolved itself.
