### ISSUE TITLE
How to fill in attributes like the Department?

### ISSUE THREAD

**Issue by ratnavis** [catalyst/moodle-auth_saml2#654]
We have a Moodle 3.11 and auth_saml2 plug-in working together. But in addition to the mandatory e-mail, first name and surname we want to feed say Department from the IDp to Moodle. We can't find an interface to do that.

What are we missing?

P.S. This is the same question as https://moodle.org/mod/forum/discuss.php?d=430876.  We are working together in the same project.

**Comment by danmarsden** [comment]
Usually the IDP's default configuration will not be sending across anything other than email/firstname/lastname to Moodle - I'd reccomend you follow up in your moodle.org post including information on the IDP you are using and someone using that same IDP may be able to provide some further tips.
thanks!
