### ISSUE TITLE
Single Logout process

### ISSUE THREAD

**Issue by Tassleh0ff** [catalyst/moodle-auth_saml2#660]
Hi, first of all thank for this plugin which is awesome, It's the first time I use SAML for federation and works perfectly.

I have a couple of questions regarding the logout process because I found no informations so far:

- in case of SP initiated logout do I simply have to activate the option "Attempt IdP Signout"?
In this case the plugin send a POST request to the IdP with all data required by the SAML protocol?

- in case of an IDP initiated logout I assume the IdP should use the logout url inside the exchanged metadata, is it right?
I that case the plugin (SP) will automatically send a POST request to the IdP with the data required by the SAML protocol?

Sorry for dumb questions but this is my first experience with a plugin like this.

**Comment by brendanheywood** [comment]
> first of all thank for this plugin which is awesome

Welcome :)

> in case of SP initiated logout do I simply have to activate the option "Attempt IdP Signout"?
In this case the plugin send a POST request to the IdP with all data required by the SAML protocol?

Yes, just tick the box and after you log out of moodle it will redirect to the idp to logout of it. 

> in case of an IDP initiated logout I assume the IdP should use the logout url inside the exchanged metadata, is it right?
I that case the plugin (SP) will automatically send a POST request to the IdP with the data required by the SAML protocol?

Almost, when the Idp initiates logout it the idp posts the the sp. There are different bindings for this and support for single logout is quite varied across idp's, so with boths questions just test and see.
