### ISSUE TITLE
WantAssertionsSigned property

### ISSUE THREAD

**Issue by Tassleh0ff** [catalyst/moodle-auth_saml2#661]
I found this pull request that added WantAssertionsSigned property to the plugin.
https://github.com/catalyst/moodle-auth_saml2/pull/585

I noticed the plugin I installed from Moodle was a version prior to the merge of this new feature into the main branch, so I updated throught git and I got the new option "Want assertions signed", but if I change it from default value (No) to Yes and save the configuration, my metadata does not change and there's no WantAssertionsSigned field in the xml.

Do I need to change some other options or add something in the config.php or any other file?
Thanks for any information :)

**Comment by alexmorrisnz** [comment]
Hi @Tassleh0ff can you regenerate the metadata and see if it has updated with the field?
Visiting the url `/auth/saml2/sp/metadata.php?regenerate=1` will regenerate the file

**Comment by Tassleh0ff** [comment]
Worked perfectly, now the metadata contains the WantAssertionsSigned parameter.
Thanks!
