### ISSUE TITLE
Option to customize entityId of service provider

### ISSUE THREAD

**Issue by sr258** [catalyst/moodle-auth_saml2#674]
We need to customize the entity id that is used by the plugin (for itself, so the service provider). The plugin generates the entity ID using the hostname of the Moodle instance, but we need to override it. We haven't found any way of doing this. Is this possible through an undocumented setting?

**Comment by brendanheywood** [comment]
You should be able to do that with the spentityid settings:

https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/settings.php#L169-L174
