### ISSUE TITLE
Undefined variable in auth.php

### ISSUE THREAD

**Issue by dominicchinkh** [catalyst/moodle-auth_saml2#676]
The variable `$key` is undefined at [here](https://github.com/catalyst/moodle-auth_saml2/blob/a535b1981c49413008ef222eeef96326676b7739/classes/auth.php#L619).

Way to reproduce this issue: Set the case matching configuration to CASE INSENSITIVE and login.

**Comment by brendanheywood** [comment]
@doctorlard maybe this is related to your recent pr?

**Comment by doctorlard** [comment]
Hi @brendanheywood, I'm on leave for the next 2-3 weeks, so feel free to yoink/rebase/merge as needed for the other branches.

**Comment by danmarsden** [comment]
thanks for the report - we've fixed this up and triggered the process to re-publish a new release to the moodle.org plugins db with this change. It should land in the plugins db within the next hour or so.

thanks!
