### ISSUE TITLE
Specify a url to end up at after logout

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_saml2#68]
* [x] Create a new optional config item for a url

* [x] It should redirect to that url (or default to '/') here:
    https://github.com/catalyst/moodle-auth_saml2/blob/master/logout.php#L34

* [x] and here it should just set the global $redirect and let core do the redirect:
    https://github.com/catalyst/moodle-auth_saml2/blob/master/auth.php#L405

**Comment by praj** [comment]
Per the Moodle plugins page, I have the code changes if you want me to contribute them?

**Comment by brendanheywood** [comment]
Yes please open pull request and I'll review, thanks @praj :)

**Comment by iv-enovation** [comment]
hi i did this work today so created the pull request https://github.com/catalyst/moodle-auth_saml2

**Comment by brendanheywood** [comment]
thanks heaps!

**Comment by praj** [comment]
Yep that's great and matches the changes I'd made - thanks!
