### ISSUE TITLE
"RequestedAttribute" in the metadata file.

### ISSUE THREAD

**Issue by FxBoul** [catalyst/moodle-auth_saml2#688]
Hello,
there is no  "RequestedAttribute" in the metadata file.
Is there a way to configure this ? I can't figure it.
Thank you for your help.
Brgds/Fx

**Comment by brendanheywood** [comment]
Notes to self:

http://docs.oasis-open.org/security/saml-protoc-req-attr-req/v1.0/saml-protoc-req-attr-req-v1.0.html

This looks to be supported by SSP so will be a code wiring job

**Comment by brendanheywood** [comment]
So just confirming the code we are working on now:
1) we will add an admin setting exposing attributes that should be requested
2) this will be exposed in the Moodle SP xml metadata

I just need to confirm that these are only needed in the SP metadata or are they also need in the authentication request?

**Comment by FxBoul** [comment]
Hello,
Sounds good,
What are the authentication requests ?
