### ISSUE TITLE
PHP 8 not working due to SimpleSAMLphp 1.19.1

### ISSUE THREAD

**Issue by sammarshallou** [catalyst/moodle-auth_saml2#690]
The library doesn't work correctly in PHP 8.x because SimpleSAMLphp requires 1.19.2+ to work in PHP 8.0.x and auth_saml2 includes 1.19.1. (So close!)

https://simplesamlphp.org/docs/1.19/simplesamlphp-changelog

I am attempting to bodge our local installation, based on a diff between public releases of 1.19.1 and 1.19.5, because the process described in the UPGRADE.md was too complicated for me :) This seems to be have 'worked' ie our automated tests work so it is probably good enough for release here if we have to, but frankly I might have messed something up so I thought I should probably file an issue here (rather than try to submit my bodge).

**Comment by danmarsden** [comment]
I've just had a look through 1.19.5 and it looks like the problematic external dependencies that we've needed to work around in the recent builds have been removed/fixed so we might be able to just use the official 1.19.5 build and then drop our custom changes on top. I'll give that a go.

**Comment by danmarsden** [comment]
thanks @sammarshallou I've merged that update to 1.19.5 in now.
