### ISSUE TITLE
Moodle home page always shows, must click Login link

### ISSUE THREAD

**Issue by gregjor** [catalyst/moodle-auth_saml2#717]
Moodle version 4.0.2 (fresh install from github)
auth_saml 2022081800 (fresh install from github)

Guest logins turned off.
Dual login disabled (No)
Creating new users not allowed
No other auth plugins enabled

I have Moodle SAML SSO working with our IDP, but when I go to the Moodle site in a new private browser window I always get a near-blank home page and have to click the Login link to get to the IDP login page. This happens even when I put `?saml=on` in the URL.

We want all visitors to the site to go straight to the IDP login page unless `?saml=off` is in the URL.

This works on another Moodle install we have running Moodle 3.10.4 and auth_saml 2020110500. I have compared the Moodle auth and auth_saml plugin settings side-by-side and can't see anything different. I think I'm missing something obvious.

**Comment by danmarsden** [comment]
Force login?
https://docs.moodle.org/400/en/Site_security_settings#Force_users_to_login

**Comment by gregjor** [comment]
Force login did it. Thanks!
