### ISSUE TITLE
multiple SAML2 instances in Workplace

### ISSUE THREAD

**Issue by danielavetica** [catalyst/moodle-auth_saml2#735]
Not actually a bug, as much as a FRQ maybe? 

I tried to add multiple instances of SAML2 to a workplace environment, as the plugin got the label "multi-tenancy".

However, I couldn't add multiple SAML2 IDP's to a single workplace environment....
Or am I missing something / doing something wrong?

I expected it to be something like the OAUTH2: 
a screen where I can add a new saml config, and then on the next screen the settings / mapping...

is this something that's available? or in the pipeline?

**Comment by danmarsden** [comment]
@danielavetica please see: https://docs.moodle.org/311/en/Multi-tenancy_authentication#SAML

**Comment by danielavetica** [comment]
Hi Dan, 

Thx for the heads-up, but it's not quite as i intended. this however might not be the place to go over extensive on the _workplace_ part, so we might better e-mail eachother about it? 
i'm reachable at d.dubbeldam@avetica.nl, can you send me your mailadres so we can dive into this a bit more  'private'. Thank you in advance!

**Comment by danmarsden** [comment]
Better place to ask for help is probably the workplace partner forums... we don't typically provide private help/support via email for free and the HQ workplace team did the multi tenancy stuff in saml2 themselves and just sent us the PR.

From what I understand, you add all the idps to the main config page then you can control which idps show for each tenant on the tenant config pages.
