### ISSUE TITLE
Should the mobile app work?

### ISSUE THREAD

**Issue by thepurpleblob** [catalyst/moodle-auth_saml2#742]
Since we have changed to SAML2 authentication nobody can login using the app. "Invalid login".

When I think about it - I'm not sure how this should work as the app isn't talking to the IdP. 

Am I missing something?

**Comment by thepurpleblob** [comment]
As usual - answered my own question (although I'm not sure it was obvious).

Site administration > Mobile app > Mobile authentication > Login type... set for SSO.

**Comment by danmarsden** [comment]
:-) - hope you managed to have a good break! :-)
