### ISSUE TITLE
Errors in saml-acs.php

### ISSUE THREAD

**Issue by peachmom** [catalyst/moodle-auth_saml2#75]
Installed plugin on Moodle 3.1. Configured my SAML2 connection (to auth0). Tried testing settings and I am always getting these two errors:

line 21 of /auth/saml2/extlib/simplesamlphp/modules/saml/www/sp/saml2-acs.php: SimpleSAML_Error_Error thrown
line 35 of /auth/saml2/sp/saml2-acs.php: call to require()

What am I missing?

**Comment by ardianferdianto** [comment]
hi @peachmom did you find any solution for this? i'm facing same issues right now
