### ISSUE TITLE
Replace Deprecated PHP 8.1 function strftime()

### ISSUE THREAD

**Issue by gustavoparolin** [catalyst/moodle-auth_saml2#765]
Hello Dev Team,

I hope this message finds you well. I am writing to bring your attention to an important issue regarding the plugin SAML2 Single sign on. 

When updating from Moodle 3.9 to Moodle 4.1, we updated PHP to 8.1.
Then we encountered a critical error related to a deprecated PHP function, specifically "strftime()".

`Deprecated: Function strftime() is deprecated in /var/www/html/auth/saml2/.extlib/simplesamlphp/lib/SimpleSAML/Logger/FileLoggingHandler.php on line 120
`

As of PHP 8.1, the "strftime()" function has been marked as deprecated, which means it will no longer be supported from now on. It is crucial for us to update the plugin and replace this deprecated function with an alternative that aligns with the latest PHP standards.

I kindly request the development team to address this issue promptly by updating the plugin and modifying the mentioned line of code. This will not only ensure the smooth functioning of our website but also keep it compatible with upcoming PHP versions.

For further information regarding the deprecation of "strftime()" function, you can refer to the official PHP documentation at: https://www.php.net/manual/en/function.strftime.php

Thank you for your attention to this matter, and we appreciate your efforts in resolving this issue. 

Best regards,

Gustavo Parolin

**Comment by danmarsden** [comment]
looks like that comes from the simplesamlphp lib - we try not to modify that library where we can, but I'd suspect this is fixed in the newer version of simplesamlphp which we'll likely update to at some point.

**Comment by sarahjcotton** [comment]
Confirming this is fixed in the latest version of simplesamlephp: https://simplesamlphp.org/docs/2.0/simplesamlphp-upgrade-notes-2.0.html
