### ISSUE TITLE
simplesamlphp out-of-the-box admin page

### ISSUE THREAD

**Issue by tommysghid** [catalyst/moodle-auth_saml2#78]
I had installed your saml2 plugin in Moodle. All works fine there. I saw the saml2/config/config.php saml configuration file even though if one were to use saml out-of-the-box instead of integrated it would be saml2/extlib/simplesamlphp/config/config.php. 

But last night, I tried to find the version number for the simplesamlphp that you embed in your plugin (without luck btw). So I tried to browse the out-of-the-box simplesamlphp admin page. (I have set up simpelsamlphp with Moodle and other web apps by installing saml traditionally. So I knew it existed and I know the directory structure somewhate.) While the page didn't work, it output errors. I do not have error messaging turned on in Moodle. So this is good and bad. 

It is good that there isn't an unmanned configuration page for simplesamlphp associated with your plugin available to someone with knowledge and bad intent. But it is bad as the errors output were fatal php errors that exposed directory URLs. 

Still needing the simplesamlphp version number you used and seeing the errors I tried to troubleshoot the error messages. It all had to do with the _include.php file and the _autoload.php file. THey could not find the config.php file. 

So I changed the following two lines in auth/saml2/extlib/simplesamlphp/www/_include.php:
1)
require_once(dirname(dirname(__FILE__)).'/lib/_autoload.php') by pointing it to the auth/saml2/_autoload.php

and 

2)
//$configdir = SimpleSAML\Utils\Config::getConfigDir(); initially by hardcoding the path to the correct cofig.php file (auth/saml2/config/config.php) and then by creating a Linux environment variable named SIMPLESAMLPHP_CONFIG_DIR

These errors went away and the auth/saml2/extlib/simplesamlphp/www/index.php page loaded but it, too, had errors. This time it came from auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Configuration.php line 106. Again, the configuration file could not be found. So, just to test, I hardcoded $filename there as auth/saml2/config/config.php. It threw en error on the Moodle API call to get_site_identifier(); 

So I just stopped trying to figure it out. 

Is there a more graceful way to hide or disable the out-of-the-box saml admin page (instead of showing errors in preventing people from accessing it)? 

And where do you expose the version of simplesamlphp you are using? 

Orrrrrr have I missed some nuance/detail of the installation that would have fixed all of this/prevented all of this?

Thanks.

**Comment by tommysghid** [comment]
To be clear(er?) without doing anything but installing your plugin and without Moodle debugging/PHP error messaging turned on this is what gets printed out to the out-of-box simplesamlphp admin page:
Fatal error: Uncaught exception 'Exception' with message 'Unable to load Composer autoloader' in .../auth/saml2/extlib/simplesamlphp/lib/_autoload.php:18 Stack trace: #0 .../auth/saml2/extlib/simplesamlphp/www/_include.php(32): require_once() #1 .../auth/saml2/extlib/simplesamlphp/www/index.php(3): require_once('...') #2 {main} thrown in .../auth/saml2/extlib/simplesamlphp/lib/_autoload.php on line 18

I've edited out the absolute paths as I don't know them exposed.

**Comment by brendanheywood** [comment]
Ok there is a few unrelated things so lets break it down:

1) Getting the version number of simplesaml - do you actually need this available in a GUI? If so I'm curious why you need to know, SSP should be viewed as an internal dependency. In the file system you can see the version here:

https://github.com/catalyst/moodle-auth_saml2/blob/deb59eb494a0786776b249e3d7eb6a0919152173/extlib/simplesamlphp/lib/SimpleSAML/Configuration.php#L328

But it would be trivial to show this on the moodle admin page which I have logged here #80

2) The SSP admin page, as you said, should not be available, and isn't. I don't want to remove it's code to make it easier to upgrade SSP (ie leave as many files as possible intact)

3) Exposing php errors in the browser including stack traces and paths: This has absolutely nothing to do with this plugin and you need to fix this in your php config. Moodle also has a setting for this, you should set both. As an aside while I agree you should not be exposing stuff like this, knowing a file path doesn't really expose anything particularly vulnerable.

**Comment by tommysghid** [comment]
Thanks for the response. 

I don't know about your development experiences but some of mine require detailed documentation. So if simplesamlphp is installed I need to know the version so I can document it for security review. It is like any other versioning. Some software packages are upgraded for particular reasons--some security related and some not. So versioning is important. Regardless I am required to provide such versioning of all software I install.  I mean there are several versions of simplesamlphp after all. It is like Moodle itself. It needs PHP and PHP needs certain PHP modules of particular versions to work. Some people might say it is a Moodle thing. Some might say it is a PHP internal issue. But on some projects I work on it is neither, in the case of openssl, mcrypt, etc. If Moodle and/or PHP rely on it for functionality sometimes I need to know what version of openssl is built and used by Moodle/PHP. Sometimes I have had to build those modules for PHP from scratch. If the correct version is not used depending upon the security audit/review/test, my work does not pass security tests and is delayed until it does. 

After all I saw that version number in your code comments. But it sounds like you have plans  to upgrade it from time-to-time. Even PHP and Moodle expose the internal versions of dependent software etc. But maybe this is just my work. Sorry to be a pain. 

Also I hear you about the php.ini file and errors. Sure. But I don't control the server in all regards. So I just cannot turn that off. And it is off in Moodle as I said while it writes errors to the error log on the server. But just because the out-of-box simplesamlphp page errors out doesn't mean it isn't available in my opinion. Anyway I will update the one line I did before so something less telling will show up if someone stumbles upon that page. I think it says "You haven't set up your config pages. Refer to . . . ." or something like that. It is much better than expose where things are installed on my server. And it is a little more graceful way to handle "disabling" that page as well, in my opinion. 

Anyway thanks for your response.

**Comment by brendanheywood** [comment]
Yeah the security audit makes total sense. And exposing that in the gui is on the todo list now.

> Also I hear you about the php.ini file and errors

Ok but you need to be aware that even if that setting is on in moodle, there are plenty of bits of code that are in moodle but which don't bootstrap the moodle code and so won't honor that setting. So if any of these fail you'll still expose things. This includes parts of my saml plugin, so even if everything was coded correctly and something unrelated went screwy, like say an out of memory issue, then you'd still get an error message to the browser. There is no way to fix this 100% correctly other that at the php level. I'm surprised that in an environment like yours which is so security aware this hasn't been set this already as a baseline regardless of which php app we are talking about.

Anyway apart from the version number, I don't think there is anything actionable here, so I'm going to close it. If I've got something wrong feel free to reopen or make new issues, thanks for the feedback :)

**Comment by brendanheywood** [comment]
Turns out this was added very recently anyway:

![image](https://cloud.githubusercontent.com/assets/187449/22633753/6a35f018-ec78-11e6-94e3-5774c8dfb39c.png)
