### ISSUE TITLE
"Deprecated: Creation of dynamic property" warnings with PHP 8.2

### ISSUE THREAD

**Issue by LMachucaORT** [catalyst/moodle-auth_saml2#781]
PHP Deprecated:  Creation of dynamic property auth_saml2\admin\setting_button::$label is deprecated in auth/saml2/classes/admin/setting_button.php on line 52
PHP Deprecated:  Creation of dynamic property auth_saml2\admin\setting_button::$href is deprecated in auth/saml2/classes/admin/setting_button.php on line 53

PHP Deprecated:  Creation of dynamic property auth_plugin_saml2::$spname is deprecated in auth/saml2/classes/auth.php on line 111
PHP Deprecated:  Creation of dynamic property auth_plugin_saml2::$certpem is deprecated in auth/saml2/classes/auth.php on line 112
PHP Deprecated:  Creation of dynamic property auth_plugin_saml2::$certcrt is deprecated in auth/saml2/classes/auth.php on line 113
PHP Deprecated:  Creation of dynamic property auth_plugin_saml2::$metadatalist is deprecated in auth/saml2/classes/auth.php on line 119

**Comment by sammarshallou** [comment]
We see this too, I'll submit a fix shortly.

**Comment by gemguardian** [comment]
@sammarshallou - I wonder if there is a timeline on when to saml2 php 8.2 version will be available?

**Comment by sammarshallou** [comment]
@gemguardian No use asking me, that's down to Catalyst. We are using it here in PHP 8.2; according to our customisation notes we only have the published plugin, plus PR #789 which is the one linked here, (And one other local change which is because our login IdP has a bug, not related to PHP 8.2.)

**Comment by gemguardian** [comment]
@sammarshallou thank you for the information, sorry I mixed up names thought you worked for Catalyst. @danmarsden then I am tagging you - do you have any idea if Catalyst will commit the pull request ?

**Comment by danmarsden** [comment]
just merged it in.. there's a bit of a backlog on pull requests in here at the moment - hard to find someone internally with the time to test and review stuff on non-chargeable time these days... and my work day should have been long over by now too!! :-)

Thanks for the pr Sam (and for the reminder @gemguardian) :-)

**Comment by gemguardian** [comment]
@danmarsden thank you. Fully understand :)
