### ISSUE TITLE
Deprecated: SimpleSAML\Session implements the Serializable interface

### ISSUE THREAD

**Issue by danitome24** [catalyst/moodle-auth_saml2#782]
When logging in and logging out on Moodle with SAML2 activated I can see these warnings:

```
Deprecated: SimpleSAML\Session implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/auth/saml2/.extlib/simplesamlphp/lib/SimpleSAML/Session.php on line 29
```

**Comment by danmarsden** [comment]
you have an older version of the saml2 plugin installed - we've recently upgraded simplesamlphp to 2.0.5 which doesn't contain that file. - please grab the latest version from the MOODLE_39_STABLE branch here in github thanks.
