### ISSUE TITLE
The bundled psr breaks moodle 4.4

### ISSUE THREAD

**Issue by wizhippo** [catalyst/moodle-auth_saml2#815]
See https://moodle.org/mod/forum/discuss.php?d=458481#p1841215

The bundles psr are old and overriding the psr that moodle 4.4 requires which are newer.

**Comment by shaikhfati** [comment]
Dear Team,

I feel I too have the similar problem.

After I upgraded Moodle Version 4.33 to Version 4.4. I am getting error on logout.

**This page isn’t working 
www.newserver.qmedcourses.in is currently unable to handle this request.
HTTP ERROR 500**

When I On the "DIsplay Debug Message " on Debugging page I am getting following error messages.

Debug Message on logout page

**Fatal error: Declaration of DI\Container::get(string $id): mixed must be compatible with Psr\Container\ContainerInterface::get($id) in moodledata_path/moodle44/lib/php-di/php-di/src/Container.php on line 124**

Debug Message through out the site

**Callback before_http_headers in auth_saml2 component should be migrated to new hook callback for core\hook\output\before_http_headers
line 7459 of /lib/moodlelib.php: call to debugging()
line 7523 of /lib/moodlelib.php: call to {closure}()
line 47 of /lib/classes/hook/output/before_http_headers.php: call to get_plugins_with_function()
line 1369 of /lib/outputrenderers.php: call to core\hook\output\before_http_headers->process_legacy_callbacks()
line 116 of /index.php: call to core_renderer->header()**

Please help me resolve the problem.

Thanks & regards
Fatima Shaikh

**Comment by kabalin** [comment]
@shaikhfati this issue was addressed at #810, you need to update your code to the latest state.

**Comment by BjoernLudwig** [comment]
We have the same issue here. I am wondering if there will be a proper bugfix release for the plugin . The "solution" to copy some code to somewhere seems pretty hacky to me. If there will be no release and the only solution will stay to copy code, could someone provide some specific directions on what to copy where please? I'd be happy to extend the documentation in a subsequent pull request with these advices.

Thanks in advance and keep up the awesome work!

**Comment by wizhippo** [comment]
Manfully updated  to latest fixed it.
