### ISSUE TITLE
Dual login setting Description last paragraph closing tag wrong

### ISSUE THREAD

**Issue by Mohan-tech1** [catalyst/moodle-auth_saml2#821]
**What happened?**
**Dual login setting ** Description last paragraph closing tag wrong
Please provide as many of the following as applies:
Close the last paragraph properly

![image](https://github.com/catalyst/moodle-auth_saml2/assets/73571625/c4b1cf71-0afa-4575-883e-367bf7e33150)

**What you expected:**
![image](https://github.com/catalyst/moodle-auth_saml2/assets/73571625/b1adc302-452e-4af2-83e2-f9e5954b6fe7)

**Comment by danmarsden** [comment]
thanks for the PR! :-)
