### ISSUE TITLE
Errors and deprecations on PHP < 8.0

### ISSUE THREAD

**Issue by rikardow** [catalyst/moodle-auth_saml2#823]
Hi, thanks for the great work on this plugin

We found some errors and deprecations in the codebase when using versions of PHP behind 8.0, here's the list

#### Warnings

1. **File:** auth/saml2/.extlib/simplesamlphp/lib/SimpleSAML/Locale/Translate.php  
   **Line:** 71  
   **Message:** Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$configuration was used and possibly changed (by reference) on line 66.

2. **File:** auth/saml2/.extlib/simplesamlphp/lib/SimpleSAML/Session.php  
   **Line:** 29  
   **Message:** When the magic __serialize() and __unserialize() methods are available and the code base does not need to support PHP < 7.4, the implementation of the Serializable interface can be removed.

3. **File:** auth/saml2/.extlib/simplesamlphp/templates/selectidp-dropdown.php  
   **Line:** 39  
   **Message:** Closures / anonymous functions only have access to $this if used within a class or when bound to an object using bindTo(). Please verify.

4. **File:** auth/saml2/.extlib/simplesamlphp/templates/selectidp-dropdown.php  
   **Line:** 40  
   **Message:** Closures / anonymous functions only have access to $this if used within a class or when bound to an object using bindTo(). Please verify.

5. **File:** auth/saml2/.extlib/simplesamlphp/templates/selectidp-links.php  
   **Line:** 42  
   **Message:** Closures / anonymous functions only have access to $this if used within a class or when bound to an object using bindTo(). Please verify.

6. **File:** auth/saml2/.extlib/simplesamlphp/templates/selectidp-links.php  
   **Line:** 43  
   **Message:** Closures / anonymous functions only have access to $this if used within a class or when bound to an object using bindTo(). Please verify.

7. **File:** auth/saml2/.extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/XML/Chunk.php  
   **Line:** 18  
   **Message:** When the magic __serialize() and __unserialize() methods are available and the code base does not need to support PHP < 7.4, the implementation of the Serializable interface can be removed.

8. **File:** auth/saml2/.extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/XML/saml/AttributeValue.php  
   **Line:** 20  
   **Message:** When the magic __serialize() and __unserialize() methods are available and the code base does not need to support PHP < 7.4, the implementation of the Serializable interface can be removed.

9. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/config/Resource/ClassExistenceResource.php  
   **Line:** 184  
   **Message:** Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$previous was used and possibly changed (by reference) on line 152.

10. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/var-dumper/Resources/functions/dump.php  
    **Line:** 27  
    **Message:** Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$var was used and possibly changed (by reference) on line 20.

11. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/polyfill-intl-normalizer/Normalizer.php  
    **Line:** 93  
    **Message:** INI directive 'mbstring.func_overload' is deprecated since PHP 7.2 and removed since PHP 8.0.

12. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/yaml/Parser.php  
    **Line:** 90  
    **Message:** INI directive 'mbstring.func_overload' is deprecated since PHP 7.2 and removed since PHP 8.0.

13. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/yaml/Inline.php  
    **Line:** 71  
    **Message:** INI directive 'mbstring.func_overload' is deprecated since PHP 7.2 and removed since PHP 8.0.

14. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/mime/RawMessage.php  
    **Line:** 19  
    **Message:** When the magic __serialize() and __unserialize() methods are available and the code base does not need to support PHP < 7.4, the implementation of the Serializable interface can be removed.

15. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/routing/CompiledRoute.php  
    **Line:** 19  
    **Message:** When the magic __serialize() and __unserialize() methods are available and the code base does not need to support PHP < 7.4, the implementation of the Serializable interface can be removed.

16. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/routing/Route.php  
    **Line:** 20  
    **Message:** When the magic __serialize() and __unserialize() methods are available and the code base does not need to support PHP < 7.4, the implementation of the Serializable interface can be removed.

17. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/dependency-injection/TypedReference.php  
    **Line:** 37  
    **Message:** Since PHP 7.0, functions inspecting arguments, like func_get_arg(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$name was used and possibly changed (by reference) on line 33.

18. **File:** auth/saml2/.extlib/simplesamlphp/vendor/twig/twig/src/Profiler/Profile.php  
    **Line:** 19  
    **Message:** When the magic __serialize() and __unserialize() methods are available and the code base does not need to support PHP < 7.4, the implementation of the Serializable interface can be removed.

#### Errors

1. **File:** auth/saml2/.extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Exception/RuntimeException.php  
   **Line:** 12  
   **Message:** The interface Throwable cannot be implemented directly, extend the Exception class instead.

2. **File:** auth/saml2/.extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Exception/InvalidArgumentException.php  
   **Line:** 9  
   **Message:** The interface Throwable cannot be implemented directly, extend the Exception class instead.

3. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/framework-bundle/Console/Descriptor/Descriptor.php  
   **Line:** 341  
   **Message:** Using \parent inside a class without parent is deprecated since PHP 7.4 and removed since PHP 8.0.

4. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/var-dumper/Caster/ResourceCaster.php  
   **Line:** 73  
   **Message:** Function mysql_get_host_info() is deprecated since PHP 5.5 and removed since PHP 7.0.

5. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/var-dumper/Caster/ResourceCaster.php  
   **Line:** 73  
   **Message:** Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead.

6. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/var-dumper/Caster/ResourceCaster.php  
   **Line:** 74  
   **Message:** Function mysql_get_proto_info() is deprecated since PHP 5.5 and removed since PHP 7.0.

7. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/var-dumper/Caster/ResourceCaster.php  
   **Line:** 74  
   **Message:** Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead.

8. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/var-dumper/Caster/ResourceCaster.php  
   **Line:** 75  
   **Message:** Function mysql_get_server_info() is deprecated since PHP 5.5 and removed since PHP 7.0.

9. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/var-dumper/Caster/ResourceCaster.php  
   **Line:** 75  
   **Message:** Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead.

10. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/polyfill-intl-idn/bootstrap.php  
    **Line:** 133  
    **Message:** The constant \INTL_IDNA_VARIANT_2003 is deprecated since PHP 7.2 and removed since PHP 8.0.

11. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/polyfill-intl-idn/bootstrap.php  
    **Line:** 136  
    **Message:** The constant \INTL_IDNA_VARIANT_2003 is deprecated since PHP 7.2 and removed since PHP 8.0.

12. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/error-handler/ErrorHandler.php  
    **Line:** 455  
    **Message:** Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$type was changed on line 404.
    
 Thank you very much for your efforts

**Comment by danmarsden** [comment]
Looks like you are using an older release of the plugin - please make sure you are using the latest version avaiable here in github - the version available in the plugins db is a little old as the auto-publishing to plugins db is currently broken here.
