### ISSUE TITLE
Errors and deprecations on PHP > 8.0

### ISSUE THREAD

**Issue by rikardow** [catalyst/moodle-auth_saml2#824]
Hi, thanks for the great work on this plugin

We found some errors and deprecations in the codebase when using versions of PHP above 8.0, here's the list

#### Warnings

1. **File:** auth/saml2/.extlib/simplesamlphp/lib/SimpleSAML/Logger/FileLoggingHandler.php  
   **Line:** 120  
   **Message:** Function strftime() is deprecated since PHP 8.1; Use date() or IntlDateFormatter::format() instead.

2. **File:** auth/saml2/.extlib/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php  
   **Line:** 99  
   **Message:** Using ${d['entity_id']} (variable variables) in strings is deprecated since PHP 8.2, use {${expr}} instead.

3. **File:** auth/saml2/.extlib/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php  
   **Line:** 202  
   **Message:** Using ${d['entity_id']} (variable variables) in strings is deprecated since PHP 8.2, use {${expr}} instead.

4. **File:** auth/saml2/.extlib/simplesamlphp/modules/oauth/libextinc/OAuth.php  
   **Line:** 313  
   **Message:** Function openssl_free_key() is deprecated since PHP 8.0.

5. **File:** auth/saml2/.extlib/simplesamlphp/modules/oauth/libextinc/OAuth.php  
   **Line:** 342  
   **Message:** Function openssl_free_key() is deprecated since PHP 8.0.

6. **File:** auth/saml2/.extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php  
   **Line:** 939  
   **Message:** Using ${var} in strings is deprecated since PHP 8.2, use {$var} instead. Found: ${state['saml:sp:IdP']}.

7. **File:** auth/saml2/.extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php  
   **Line:** 940  
   **Message:** Using ${var} in strings is deprecated since PHP 8.2, use {$var} instead. Found: ${state['core:SP']}.

8. **File:** auth/saml2/.extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/DOMDocumentFactory.php  
   **Line:** 34  
   **Message:** Function libxml_disable_entity_loader() is deprecated since PHP 8.0.

9. **File:** auth/saml2/.extlib/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/DOMDocumentFactory.php  
   **Line:** 51  
   **Message:** Function libxml_disable_entity_loader() is deprecated since PHP 8.0.

10. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/config/Util/XmlUtils.php  
    **Line:** 55  
    **Message:** Function libxml_disable_entity_loader() is deprecated since PHP 8.0.

11. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/config/Util/XmlUtils.php  
    **Line:** 63  
    **Message:** Function libxml_disable_entity_loader() is deprecated since PHP 8.0.

12. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/config/Util/XmlUtils.php  
    **Line:** 73  
    **Message:** Function libxml_disable_entity_loader() is deprecated since PHP 8.0.

13. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php  
    **Line:** 648  
    **Message:** Function libxml_disable_entity_loader() is deprecated since PHP 8.0.

14. **File:** auth/saml2/.extlib/simplesamlphp/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php  
    **Line:** 650  
    **Message:** Function libxml_disable_entity_loader() is deprecated since PHP 8.0.

#### Errors

1. **File:** auth/saml2/.extlib/simplesamlphp/lib/SimpleSAML/Error/Assertion.php  
   **Line:** 65  
   **Message:** The constant \ASSERT_QUIET_EVAL is removed since PHP 8.0.

Thank you very much for your efforts

**Comment by danmarsden** [comment]
appears to be the same issue as #823 - you are not using the latest code. - please use the MOODLE_39_STABLE branch here in github which contains an update to the simplesamlphp lib and does not have the files mentioned in this comment.
