### ISSUE TITLE
Undefined strings for tmp directory

### ISSUE THREAD

**Issue by michael-milette** [catalyst/moodle-auth_saml2#850]
**What happened?**

During an upgrade of the plugin (most recent version last updated in November 2024 on GitHub) in Moodle 4.1 (English), I noticed that strings are undefined / undefined:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/66af1383-c23d-4644-98ac-9982d587625d">

Here is a list of the missing strings:

- tempdir
- tempdirdefault
- tempdir_help

Let me know if you have any questions.

Best regards,

Michael Milette

**Comment by danmarsden** [comment]
Those strings appear to.be there to me.. do you have local changes to the lang string file that have caused a merge conflict which wasn't fixed properly?

**Comment by danmarsden** [comment]
@Limekiller @keevan the tempdirdefault value there doesn't look like it should have landed in the lang strings to me. We should pull that out too.

**Comment by keevan** [comment]
Thanks for catching that one @danmarsden, I've pushed a PR which should fix this in 404 and 39 branches.

**Comment by danmarsden** [comment]
Cool thanks!

**Comment by michael-milette** [comment]
> Those strings appear to.be there to me.. do you have local changes to the lang string file that have caused a merge conflict which wasn't fixed properly?

I have no local changes to the strings. It was working fine before I upgraded the plugin from a version from October 2023.

**Comment by danmarsden** [comment]
yeah - sorry @michael-milette you were correct they were missing in one of the branches - @keevan pushed a fix through last night though so it should be sorted now.

thanks!
