### ISSUE TITLE
"Use HTTPS for logins" not used to determine Entity ID for SP in SAML communications

### ISSUE THREAD

**Issue by johnsims-optiv** [catalyst/moodle-auth_saml2#88]
When the config.php file has wwwroot set to 'http://foo.bar' and the "Use HTTPS for logins" setting is enabled, the assertion sent from the LMS (SP) to the IdP uses the HTTP address, not the HTTPS address. This causes the request to the IdP to fail with an error message that "The SAML message signature could not be validated. "

**Comment by brendanheywood** [comment]
This may seem harsh, but do not use the HTTPS for login setting in moodle, it's horrible security hole. That "feature" in moodle should have been deprecated years ago and will be shortly. In this day and age there is zero reason to not serve only over https all the time.

See also a near duplicate: #44 

And the moodle tracker: Deprecate loginhttps ( https://tracker.moodle.org/browse/MDL-42834 )
