### ISSUE TITLE
Support isPassive SAML mode

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_saml2#9]
Ie if anon, then bounce to the IdP always but just to check and then come back even if they aren't logged in.

Otherwise know in CAS as 'gateway'

https://wiki.jasig.org/display/CAS/gateway

or in shibboleth as 'lazy session'

or 'is passive' in SAML

https://wiki.shibboleth.net/confluence/display/SHIB2/isPassive
- [ ] change the dual login checkbox to a drop down with 'Dual auth' / 'Force to IdP' and 'Dual auth with isPassive mode'

**Comment by roperto** [comment]
Closed with #183 moodle[:32] and #184 moodle[33:].

Published on https://moodle.org/plugins/pluginversions.php?plugin=auth_saml2
