### ISSUE TITLE
Uninstall directions / possibly critical bug in release 2017021600

### ISSUE THREAD

**Issue by Apex-Oil** [catalyst/moodle-auth_saml2#90]
Something went wrong with the update and I do not have the patience to track down what it si exactly but I am rather confident a full uninstall and re-install will fix it.  Can you provide me a location that has the full list of instructions to remove the integration of SAML2 from my site so I may start from scratch?

**Comment by brendanheywood** [comment]
I'd prefer to debug it to make sure there isn't a wider issue affect lots of people. The plugin stores state in 3 places:

1) in the config tables, and key store which are removed on uninstall by moodle core
2) in sitedata/saml2/ - these files are not removed on uninstall
3) the auth type of your users

Note that moodle will not let you uninstall it if there is still users mapped to an auth plugin. So if you want to uninstall then you have to remap your users, then uninstall the plugin as normal, and then optionally delete the saml2 dir. But I think this would just cause more issues.

If you are having cert issues you can just regenerate from the gui, or just delete the saml2 dir and it will recreate it and then you'll have to re-exchange the new metadata with idp.

But still none of this should be required and it a worry, if it broke after the upgrade it is more likely to be a code issue so a re-install won't achieve anything. What symptoms do you get, and can you provide a trace of your error log with both saml debugging and moodle debugging on full?

**Comment by brendanheywood** [comment]
I've just re-reviewed everything that went out in that release yesterday and there was a couple settings that should not have shipped. I have just rolled them back and rereleased a new version. Can you please try again?

**Comment by brendanheywood** [comment]
I assuming this has sorted your issue, please re-open if it did not
