### ISSUE TITLE
Help wanted mapping saml attributes to moodle fields

### ISSUE THREAD

**Issue by patkarrjr** [catalyst/moodle-auth_saml2#91]
Folks,

New to the SAML2 and Moodle integration. Been hitting a wall in trying to get this thing up and running.

Current process and issue:

Login using my iDP and have no issues in authenticating BUT I get redirected to update my profile.
Firstname, surname, and email address are empty instead of populating with iDP information. 
The test done in the authentication plugin does pull the correct data i.e.:

****************  Start **********************
Authed!
array(6) {
  ["givenname"]=>
  array(1) {
    [0]=>
    string(3) "Pat"
  }
  ["sn"]=>
  array(1) {
    [0]=>
    string(4) "Karr"
  }
  ["urn:idauto.net:saml:attribute:employeetype"]=>
  array(1) {
    [0]=>
    string(8) "Employee"
  }
  ["urn:idauto.net:saml:attribute:physicalDeliveryOfficeName"]=>
  array(1) {
    [0]=>
    string(24) "Department of Technology"
  }
  ["mail"]=>
  array(1) {
    [0]=>
    string(23) "pat.karr@mcallenisd.net"
  }
  ["uid"]=>
  array(1) {
    [0]=>
    string(5) "pkarr"
  }
}

*******************  End  ***********************

If I enter the data manually on the update screen and save, an email is sent to me and once I verify, the user account is filled with the three fields being requested.

I don't want users to have to enter their own information thus I need to make it seamless to them using SAML2.

I know that the permissions to write to the database are there due to being able to add the data manually via the update screen. I'm not sure if the integration between SAML2 and Moodle database use different authentication mechanisms.

Any help would be greatly appreciated.

Pat

**Comment by patkarrjr** [comment]
failed to mention that I'm running ver 2016041300 and moodle 3.2

**Comment by brendanheywood** [comment]
You need to configure a mapping between the fields that saml returns and the moodle fields, eg given the data dump you provided above something like this:

![image](https://cloud.githubusercontent.com/assets/187449/23107379/7436dd42-f750-11e6-888c-4de4277dbc12.png)
