### ISSUE TITLE
Store idp xml in namespaced file

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_saml2#95]
There is some crossover with implementing multiple idps #5 - when you change the idp url we reset the idp.xml file and refetch it. In https://github.com/catalyst/moodle-local_datacleaner/issues/25 we are going to implement a way for the the data cleaner to set CFG variables to different things for different environments, but ideally we want the two plugins to be loosely coupled.

The problem is that if the cleaner just sets the auth plugins config items, it is not resetting the idp xml files which is what actually matters. So one way could be to have a dedicated cleaner plugin for auth_saml, which is fine but probably overkill. A second easier way is that we just save the idp.xml file under a name which is derived from the idp's url, eg idp-google.com.xml and that way we can store multiple idp xml files side by side, similar to what we can already do with the sp side.

**Comment by roperto** [comment]
Implemented.
