### ISSUE TITLE
"Exception - Missing or in ." when using ADFS

### ISSUE THREAD

**Issue by cmisbach** [catalyst/moodle-auth_saml2#97]
Hello,

We are setting up SAML2 and the IdP is ADFS and is being configured by a partner, so we don't have access to it. We are using their Public Metadata URL in our configuration and they believe that it is set correctly for our relying party. We have tested the SP successfully with the shibboleth test IdP. Below is the debugging error we are getting in Moodle:

Exception - Missing or in .

More information about this error

Debug info: 
Error code: generalexceptionmessage
Stack trace:
```
line 277 of /auth/saml2/extlib/saml2/src/SAML2/Assertion.php: Exception thrown
line 246 of /auth/saml2/extlib/saml2/src/SAML2/Assertion.php: call to SAML2_Assertion->parseSubject()
line 92 of /auth/saml2/extlib/saml2/src/SAML2/EncryptedAssertion.php: call to SAML2_Assertion->__construct()
line 371 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php: call to SAML2_EncryptedAssertion->getAssertion()
line 550 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php: call to sspmod_saml_Message::decryptAssertion()
line 524 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php: call to sspmod_saml_Message::processAssertion()
line 120 of /auth/saml2/extlib/simplesamlphp/modules/saml/www/sp/saml2-acs.php: call to sspmod_saml_Message::processResponse()
line 35 of /auth/saml2/sp/saml2-acs.php: call to require()
```

Any indication what this error might mean and what we should tell the IdP admin?

Thank you

**Comment by brendanheywood** [comment]
Can you please turn on full saml debugging and dump your error log here

https://github.com/catalyst/moodle-auth_saml2#debugging

**Comment by praj** [comment]
I had a similar issue with an ADFS integration.

Debugging should give you the specifics of the error e.g.

```
Decryption with key #0 failed with exception: 
Missing <saml:NameID> or <saml:EncryptedID> in <saml:Subject>.
```

A few quick things to check on the ADFS side:

* Check that that the moodle certificate from auth/saml2 has been added to the Trusted Root Certificate Authorities store (when checking the Relying Party it will indicate if this is not the case).

* There needs to be a rule that sets an Outgoing Claim Rule for Name ID e.g. from SAM-Account-Name for the subject (you'll see something like Missing <saml:NameID> or <saml:EncryptedID> in <saml:Subject> if this isn't the case.

**Comment by cmisbach** [comment]
Thank you all for your responses. The certificate has been added to the store. We did not get any of the Missing errors you listed. The SAM-Account-Name is set to NameID in ADFS.  I have the mapped Attribute set as "NameID" in the plugin in Moodle. Attached is the debugging.


[SamlDebug3:6.txt](https://github.com/catalyst/moodle-auth_saml2/files/831603/SamlDebug3.6.txt)

**Comment by brendanheywood** [comment]
Closing, there is a new feature will when turned on makes the name id appear as though it was a normal attribute called 'nameid'
