### ISSUE TITLE
You have logged in succesfully but we could not find your 'Name ID' attribute to associate you to an account in Moodle.

### ISSUE THREAD

**Issue by faithlucid** [catalyst/moodle-auth_saml2#99]
Hello,
we are trying to setup saml authentication between moodle saml2 plugin and ADFS3 and we are getting this error.
SimpleSAMLphp version is 1.14.10 .
Moodle version is 3.2 .
My authsources.php config is:
$config = array(
    $saml2auth->spname => array(
        'saml:SP',
        'entityID' => "$wwwroot/auth/saml2/sp/metadata.php",
        'idp' => $saml2auth->config->entityid,
        'NameIDPolicy' => null,
        'OrganizationName' => array(
            'en' => $SITE->shortname,
ADFS3 is sending NameID claim and in the saml2 gui config we are maping that to Username but still getting this error.
We tried also with schemas url http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier but the same.We've test the config and it gave "auth!" .
Do you have any hints for us regarding this?
I will also paste below some logs:

[Thu Mar 09 06:46:08.249501 2017] [proxy_fcgi:error] [pid 31326:tid 140269722785536] [client 195.238.88.10:59527] AH01071: Got error 'PHP message: SimpleSAMLphp DEBUG [a163d2d88b] Loading state: '_aaaf9b50b6e3db657222cfad6c29826661a2b4b437'\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Received SAML2 Response from 'http://federation.mydomain.com/adfs/services/trust'.\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Has 1 candidate keys for validation.\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Validation with key #0 failed without exception.\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Decrypted message:\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] <Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="_83aee92f-b6ef-418f-a37e-0da928ac3a4b" IssueInstant="2017-03-09T06:46:09.352Z" Version="2.0">\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   <Issuer>http://federation.mydomain.com/adfs/services/trust</Issuer>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     <ds:SignedInfo>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       <ds:Reference URI="#_83aee92f-b6ef-418f-a37e-0da928ac3a4b">\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]         <ds:Transforms>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]           <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]           <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]         </ds:Transforms>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]         <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]         <ds:DigestValue>Qu5xSRN0Bq70oXTRU+VRkDlBfDjxOReOWjW5vjPb7Fo=</ds:DigestValue>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       </ds:Reference>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     </ds:SignedInfo>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     <ds:SignatureValue>...==</ds:SignatureValue>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       <ds:X509Data>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]         <ds:X509Certificate>...\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       </ds:X509Data>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     </KeyInfo>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   </ds:Signature>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   <Subject>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     <NameID>adm_dac</NameID>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       <SubjectConfirmationData InResponseTo="_aaaf9b50b6e3db657222cfad6c29826661a2b4b437" NotOnOrAfter="2017-03-09T06:51:09.352Z" Recipient="https://mydomain.com/auth/saml2/sp/saml2-acs.php/mydomain.com"/>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     </SubjectConfirmation>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   </Subject>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   <Conditions NotBefore="2017-03-09T06:46:09.352Z" NotOnOrAfter="2017-03-09T07:46:09.352Z">\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     <AudienceRestriction>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       <Audience>https://mydomain.com/auth/saml2/sp/metadata.php</Audience>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     </AudienceRestriction>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   </Conditions>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   <AuthnStatement AuthnInstant="2017-03-09T06:46:09.290Z" SessionIndex="_83aee92f-b6ef-418f-a37e-0da928ac3a4b">\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     <AuthnContext>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]       <AuthnContextClassRef>urn:federation:authentication:windows</AuthnContextClassRef>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     </AuthnContext>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   </AuthnStatement>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] </Assertion>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Decryption with key #0 succeeded.\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Has 1 candidate keys for validation.\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Validation with key #0 succeeded.\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Filter config for http://mydomain.com/adfs/services/trust->https://mydomain.com/auth/saml2/sp/metadata.php: array (  0 =>   sspmod_core_Auth_Process_AttributeMap::__set_state(array(     'map' =>     array (      'urn:oid:0.9.2342.19200300.100.1.1' => 'uid',      'urn:oid:0.9.2342.19200300.100.1.10' => 'manager',      'urn:oid:0.9.2342.19200300.100.1.11' => 'documentIdentifier',      'urn:oid:0.9.2342.19200300.100.1.12' => 'documentTitle',      'urn:oid:0.9.2342.19200300.100.1.13' => 'documentVersion',      'urn:oid:0.9.2342.19200300.100.1.14' => 'documentAuthor',      'urn:oid:0.9.2342.19200300.100.1.15' => 'documentLocation',      'urn:oid:0.9.2342.19200300.100.1.2' => 'textEncodedORAddress',      'urn:oid:0.9.2342.19200300.100.1.20' => 'homePhone',      'urn:oid:0.9.2342.19200300.100.1.21' => 'secretary',      'urn:oid:0.9.2342.19200300.100.1.22' => 'otherMailbox',      'urn:oid:0.9.2342.19200300.100.1.25' => 'dc',      'urn:oid:0.9.2342.192...\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Deleting state: '_aaaf9b50b6e3db657222cfad6c29826661a2b4b437'\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Session: doLogin("mydomain.com")\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] Received message:\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b] <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_577287a3-e005-45c8-a98e-ce1a977168da" Version="2.0" IssueInstant="2017-03-09T06:46:09.352Z" Destination="https://mydomain.com/auth/saml2/sp/saml2-acs.php/mydomain.com" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="_aaaf9b50b6e3db657222cfad6c29826661a2b4b437">\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://federation.mydomain.com/adfs/services/trust</Issuer>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   <samlp:Status>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]     <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>\nPHP message: SimpleSAMLphp DEBUG [a163d2d88b]   </samlp:Status>\nPHP me

Thank you.

**Comment by cristianocumer** [comment]
Could you paste the screenshots of your ADFS configuration?

**Comment by faithlucid** [comment]
i am not managing this..so i can get some details maybe..i know for sure that now it is on sha1 and it sends NameID.

**Comment by faithlucid** [comment]
we tried also on sha2 but the result is the same.
also..what i am not figuring out is why it is trying to map to an existing moodle username attribute instead of autocreating users.so I am misunderstanding what this plugin really does.

**Comment by cristianocumer** [comment]
Hello,

this is our claim config:

AllowedAuthenticationClassReferences : {}
AutoUpdateEnabled                    : False
DelegationAuthorizationRules         : 
EncryptionCertificateRevocationCheck : CheckChainExcludeRoot
PublishedThroughProxy                : False
IssuanceAuthorizationRules           : @RuleTemplate = "AllowAllAuthzRule"
                                        => issue(Type = "http://schemas.microsoft.com/authorization/claims/permit", Value = "true");
                                       
                                       
SigningCertificateRevocationCheck    : CheckChainExcludeRoot
WSFedEndpoint                        : 
AdditionalWSFedEndpoint              : {}
ClaimsProviderName                   : {}
IssuanceTransformRules               : @RuleName = "Temporary transient SessionID"
                                       c1:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname"]
                                        && c2:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant"]
                                        => add(store = "_OpaqueIdStore", types = ("http://scientificnet.org/internal/sessionid"), query = 
                                       "{0};{1};{2};{3};{4}", param = "useEntropy", param = c1.Value, param = c1.OriginalIssuer, param = 
                                       "", param = c2.Value);
                                       
                                       @RuleTemplate = "MapClaims"
                                       @RuleName = "Send SessionID as NameID"
                                       c:[Type == "http://scientificnet.org/internal/sessionid"]
                                        => issue(Type = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier", Issuer = 
                                       c.Issuer, OriginalIssuer = c.OriginalIssuer, Value = c.Value, ValueType = c.ValueType, 
                                       Properties["http://schemas.xmlsoap.org/ws/2005/05/identity/claimproperties/format"] = 
                                       "urn:oasis:names:tc:SAML:2.0:nameid-format:transient");
                                       
                                       @RuleTemplate = "LdapClaims"
                                       @RuleName = "Send UPN, GivenName, Surname, E-Mail Address"
                                       c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname", Issuer == 
                                       "AD AUTHORITY"]
                                        => issue(store = "Active Directory", types = 
                                       ("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn", 
                                       "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname", 
                                       "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname", 
                                       "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"), query = 
                                       ";userPrincipalName,givenName,sn,mail;{0}", param = c.Value);
                                       
                                       @RuleName = "Send Description, Department"
                                       c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname", Issuer == 
                                       "AD AUTHORITY"]
                                        => issue(store = "Active Directory", types = ("Description", "Department"), query = 
                                       ";description,department;{0}", param = c.Value);

**Comment by cristianocumer** [comment]
In moodle we map this:

http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn 

to the username 

and we have also Auto create users set to yes

**Comment by faithlucid** [comment]
interesting.so regarding the auto create users i basicaaly understaind that there should not be any user in moodle created in order for this to work?
I will have a chat now with our ADFS managing collegue and will get back with som findings (if any :))
thanks

**Comment by cristianocumer** [comment]
Hi @faithlucid 

no need to pre-create users. Just be sure to send the samAccountName or the UPN and use this one as username

**Comment by faithlucid** [comment]
ok.will try this.

**Comment by faithlucid** [comment]
so...we made some tests and if we try to send from AFDS something else than NameID we are getting the error "Exception - Missing or in ." .
We tried with samacountanme and upn the for both we received Decryption with key #0 failed with exception: Missing <saml:NameID> or <saml:EncryptedID> in <saml:Subject> in the logs.

**Comment by faithlucid** [comment]
the moodleapp certificate is in adfs trusted root. (i saw the other issue post regarding this)

**Comment by faithlucid** [comment]
hello,any news about? have you been able to reproduce this? thank you.

**Comment by brendanheywood** [comment]
Can you please go to:

host/auth/saml2/test.php

This page is completely outside the normal Moodle authentication and is a standalone test.

Then click on 'Login', you should go to the idp as normal, login and then come back to this page. It should now show you a complete dump of all the key value attributes that saml has returned. Whatever key holds you username then use that in the moodle saml config page.

**Comment by faithlucid** [comment]
will try this,thanks.

**Comment by faithlucid** [comment]
it only gives me:
Authed!
array(0) {
}

**Comment by brendanheywood** [comment]
Well then there is your problem, your idp isn't returning anything at all! You probably need to configure some attributes to be released.

**Comment by cristianocumer** [comment]
```
Authed!
array(6) {
  ["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"]=>
  array(1) {
    [0]=>
    string(15) "xxxxxxx@unibz.it"
  }
  ["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"]=>
  array(1) {
    [0]=>
    string(15) "Cristiano Maria"
  }
  ["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"]=>
  array(1) {
    [0]=>
    string(5) "Cumer"
  }
  ["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"]=>
  array(1) {
    [0]=>
    string(29) "xxxxxxxxxxxx@unibz.it"
  }
  ["Description"]=>
  array(1) {
    [0]=>
    string(12) "Division ICT"
  }
  ["Department"]=>
  array(1) {
    [0]=>
    string(27) "Faculty of Computer science"
  }
}
```

**Comment by brendanheywood** [comment]
I don't think there is anything actionable here code wise so I'm closing this

**Comment by santimoral** [comment]
Key to solve my problem. Thank you!

**Comment by faithlucid** [comment]
thanks for the help! i know...late response :) For now we switched to oauth2.will see if we need federation again.
